### ISSUE TITLE
Flash drive is read only after burning ISO

### ISSUE THREAD

**Issue by lluiscab** [resin-io/etcher#1048]
- **Etcher version:** latest
- **Operating system and architecture:** Xubuntu 14.04
- **Do you see any meaningful error information on DevTools?**

When I burn an ISO to any flash drive, it gets mounted as read only, to make it writtable, I need to format it with windows or use gparted. I'd like an option to disable this so I can edit the burned ISO.

**Comment by jviotti** [comment]
Hi @lluiscab ,

We don't do any manipulation to the image contents, therefore if certain partitions of it are read only it means that's the way it was set by the image publisher itself (on the image partition table). We could of course provide an option to do this, but it might be necessary for a partition to be read only for the OS to work correctly. How would we know that? 

For that reason I think this should be left to the user to do (understanding any potentially implications).
