### ISSUE TITLE
Error: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by daturach** [resin-io/etcher#1064]
Hello

I am running the version you sent me on Friday last week while debugging an issue with MySQL.
Etcher-1.0.0-beta.18+4f621f6-win32-x64-MYSQL-FIX
Windows 7, French

Today, I am not able to burn an img file. I am getting this error message when clicking on "Flash":
![etcher_path_error](https://cloud.githubusercontent.com/assets/9865568/22439180/f7d52a78-e72e-11e6-8577-c9c1edacd67b.png)

Can you help?
Thanks

**Comment by jviotti** [comment]
Hey there @daturach,

Sorry to hear you're still having issue. The path issue you get is weird. Can you open DevTools (Ctrl+Alt+I), go to the "Console" pane, type `require('electron').remote.process.argv`, press Enter and report back the results?

**Comment by daturach** [comment]
Result is:
`["D:\test\Etcher\Etcher.exe"]`

**Comment by jviotti** [comment]
OK, cool. Can you try editing the file called `resources/app/lib/child-writer/renderer-utils.js` on line 46 from:

```javascript
return path.join(CONSTANTS.PROJECT_ROOT, electron.remote.process.argv[1]);
```

To:

```javascript
return path.join(CONSTANTS.PROJECT_ROOT, electron.remote.process.argv[0]);
```

? 

Let me know if that's enough to make it work, otherwise I'll upload a new one for you!

**Comment by daturach** [comment]
It's enough but I have a new message:

![invalid_message](https://cloud.githubusercontent.com/assets/9865568/22443949/3451d76e-e741-11e6-93d1-8c2406a8ad71.png)

**Comment by daturach** [comment]
Follow by this one:
![invalid_message1](https://cloud.githubusercontent.com/assets/9865568/22444032/81699f00-e741-11e6-9596-e3290dc9e1c0.png)

**Comment by jviotti** [comment]
Hi @daturach ,

Can you try the following new build: https://drive.google.com/open?id=0B7tkbonGU-RyTGVHa1B3QjQ0MW8?

**Comment by daturach** [comment]
Hello jviotti

![flashed](https://cloud.githubusercontent.com/assets/9865568/22485232/1d996a54-e805-11e6-9b7b-eba3a59d4f6c.png)

It's looking pretty good. It's burning at about 10MB/s and just completed the process.
One thing I need to check right now: I have a multi-drive supporting different types of cards but I don't see the drives anymore! I will reboot and report back in a few minutes... 

Thanks again for your great help.

**Comment by daturach** [comment]
Tomorrow, I should receive some hardware to test the image.
However, ejecting the card make all drives unavailable. Only a reboot bring them to life again.

**Comment by lurch** [comment]
> However, ejecting the card make all drives unavailable. Only a reboot bring them to life again.

There's a discussion about that in #750

**Comment by jviotti** [comment]
Awesome, sorry for the custom build mess @daturach. I don't know what happened, all the custom builds usually just work :) 

Regarding the multi-sdcard readers issue, this is something we've heard before as @lurch mentioned. Let's continue the discussion there. @daturach Do you mind linking us to the exact adaptor you're using?

**Comment by lurch** [comment]
Just out of curiosity @jviotti what was the cause of _this_ particular issue (that you fixed with an updated build) ?

**Comment by jviotti** [comment]
I released a too custom build for him, almost done by hand, and made various mistakes in the way. The particular issue that this user hit was because I didn't package the code inside the asar, and thus the arguments positions that we expect were different, causing weird stuff in both the child writer execution and elevation stuff.

**Comment by lurch** [comment]
Ahhhh. So a bug in @jviotti rather than a bug in Etcher then ;-D

**Comment by jviotti** [comment]
Yeah, you're welcome to send a PR! :P
