### ISSUE TITLE
pendrive not detected when started as a normal user, works when started as sudo.

### ISSUE THREAD

**Issue by Dark-Passenger** [resin-io/etcher#1075]
- **Etcher version:**
beta 18
- **Operating system and architecture:**
Centos 7.3 64 bit
- **Do you see any meaningful error information on DevTools?**

doesnt seem to an attached pendrive when starting as a normal user. using sudo it works.

**Comment by jviotti** [comment]
Hi @Dark-Passenger ,

Thanks for reporting, that is indeed weird. Can you try running the following bash script with and without `sudo`: https://github.com/resin-io-modules/drivelist/blob/master/scripts/linux.sh?

I'd also love to see the output of `lsblk -d --output NAME` again with and without `sudo`.

**Comment by Dark-Passenger** [comment]
Seems a install specific issue. Reinstalled the same distro and same setup, all good.
