### ISSUE TITLE
Implement a generic tiles CSS module

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1091]
For example:

<img width="492" alt="screenshot 2017-02-10 12 04 46" src="https://cloud.githubusercontent.com/assets/2192773/22833664/242919c4-ef89-11e6-8e30-6e3ce2eaa766.png">

We can probably re-use most of this logic from the Resin UI:

<img width="1139" alt="screenshot 2017-02-10 12 05 20" src="https://cloud.githubusercontent.com/assets/2192773/22833686/3721f0aa-ef89-11e6-9728-81f773b6f77e.png">

**Comment by lurch** [comment]
Connects to https://github.com/resin-io-modules/rendition ?
