### ISSUE TITLE
Implement a form generator re-usable module for configuration forms

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1092]
For example:

<img width="289" alt="screenshot 2017-02-10 12 07 59" src="https://cloud.githubusercontent.com/assets/2192773/22833797/94fc487e-ef89-11e6-80d7-35e9a9e4791f.png">

We should be able to pass a JSON object describing the inputs, groups, etc and a form should be automatically generated.

Part of this task includes designing how the JSON object would look like.

This task should be done in coordination with the Resin UI team, given there is a component there that is able to generate forms:

<img width="595" alt="screenshot 2017-02-10 12 09 16" src="https://cloud.githubusercontent.com/assets/2192773/22833868/c2a72280-ef89-11e6-9c73-e4ae8072d5e4.png">

**Comment by lurch** [comment]
I guess this connects to https://github.com/resin-io-modules/anodize
