### ISSUE TITLE
Get more information out of the writing process to display a fancier flash progress widget

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1094]
<img width="308" alt="screenshot 2017-02-10 12 06 20" src="https://cloud.githubusercontent.com/assets/2192773/22834059/583af89e-ef8a-11e6-9359-f0b157e5e6b3.png">

The colors of the dots represent:

- Flashed blocks
- Validated blocks
- Blocks which for validation failed
- Unwritten blocks
- Skipped blocks (in the case of bmaps)

Notice there is not a direct correlation between the dots and the blocks. Depending on the image, a single dot might represent 50 blocks, etc.

**Comment by alexandrosm** [comment]
also, "downloaded blocks"

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm
