### ISSUE TITLE
Allow inserting entropy to images

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1099]
> because images are cloned, they all start with the same entropy, which means you can have an attack where you can somewhat-predict the pseudo-random generator if on boot the device hasn't had enough time to gather entropy

We can do it by populating `/var/lib/systemd/random-seed` (at least in the case of systemd images): https://www.freedesktop.org/software/systemd/man/systemd-random-seed.service.html

From https://github.com/resin-io/reconfix/issues/8

**Comment by lurch** [comment]
Closing as a duplicate of #718
