### ISSUE TITLE
Improve ENOENT/ENXIO/EIO errors when unplugging drive while flashing/validating, and prevent them from reaching TrackJS

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1124]
### Unplugging while flashing

<img width="435" alt="screenshot 2017-02-21 17 02 36" src="https://cloud.githubusercontent.com/assets/2192773/23187690/25ebda6c-f862-11e6-801e-f596642b5d2a.png">

![unplug-while-flash](https://cloud.githubusercontent.com/assets/2192773/23187700/39e6b276-f862-11e6-890b-8f2a40421b47.PNG)

![unplug-during-flash](https://cloud.githubusercontent.com/assets/2192773/23190262/41f39dca-f86d-11e6-8839-ba3c7ac1a56f.png)

### Unplugging while validating

<img width="431" alt="screenshot 2017-02-21 17 08 52" src="https://cloud.githubusercontent.com/assets/2192773/23187725/4f76720c-f862-11e6-9204-77e6dfb3f5f2.png">

![unplug-while-validating](https://cloud.githubusercontent.com/assets/2192773/23187735/58084eb8-f862-11e6-95dd-036f8957798c.PNG)

![unplug-while-validating](https://cloud.githubusercontent.com/assets/2192773/23190272/4bf85306-f86d-11e6-9fe0-fa5efea1d335.png)

- [ ] Add and document common error codes for these errors in [`etcher-image-write`](https://github.com/resin-io-modules/etcher-image-write)
- [ ] Handle such codes in the GUI, preventing them from getting to TrackJS
- [ ] Trigger Mixpanel events for them

**Comment by jviotti** [comment]
As a bonus point (very, very low priority), we could allow a "resume" option for the writer to continue from where it stopped if the drive is plugged back.

**Comment by lurch** [comment]
As I mentioned in gitter, I don't think that's actually possible, since if the drive was removed unexpectedly AFAIK there's no guarantee about the order that the blocks actually got written by the FlashTranslationLayer? i.e. we might have "written" blocks 0-50 to the card, but perhaps only blocks 0-22 and 34-41 actually made it out of the write buffers and into the card's physical flash memory?

**Comment by alexandrosm** [comment]
In that case we can enter a fast-forward "matching" mode, where we read
what's on the card, and if it matches what we're about to write, we move on
to the next, until we find a disagreement, at which point we continue with
a regular write.

Having said all this, this sounds like a lot of work for a tiny
improvement, so we really should not do this unless we're scraping the
bottom of the barrel for optimisations.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by jviotti** [comment]
This issue was fixed by https://github.com/resin-io/etcher/pull/1301
