### ISSUE TITLE
Improve error when unplugging the drive while its getting erased on Windows

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1127]
Steps to reproduce:

- Select image
- Select drive
- Click "Flash"
- Unplug the drive while the button says "Starting..."

This is the error I get:

![unplug-while-initial-unmount](https://cloud.githubusercontent.com/assets/2192773/23188291/8d6cefbc-f864-11e6-81e5-036489950c88.PNG)

This seems to be the same as https://github.com/resin-io/etcher/issues/989

We should probably detect if the drive exists before attempting to retry the `diskpart` erasure procedure, and if so, fail with another error that should not get to TrackJS.

**Comment by jviotti** [comment]
This was already addressed by https://github.com/resin-io-modules/etcher-image-write/commit/e2d3f0d1b7f62054c34835a731c38a87b6c1fa29

**Comment by lurch** [comment]
Minor nit, but IMHO it'd be nicer to link to the PR ( https://github.com/resin-io-modules/etcher-image-write/pull/99 ) rather than the commit?

**Comment by jviotti** [comment]
True, sorry about that!
