### ISSUE TITLE
Improve error when unplugging the drive while its getting unmounted

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1128]
This is the error I get:

<img width="446" alt="screenshot 2017-02-21 17 17 31" src="https://cloud.githubusercontent.com/assets/2192773/23188445/1681b530-f865-11e6-894b-e185f985dd09.png">

Tasks:

- [ ] Show a more user friendly error
- [ ] Don't send the error to TrackJS

**Comment by lurch** [comment]
...and I guess if the drive (unexpectedly) disappears during the unmount process, then there's no guarantees that the write-buffers have been flushed and the drive actually contains the complete image :-/

**Comment by lurch** [comment]
Did #1301 fix this?
