### ISSUE TITLE
Display the determined uncompressed size on the "too small for image" warning

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1136]
We should make sure the user understands why the drive is not large enough, which can be a bit confusing in the case of compressed images, where the compressed package is usually smaller than the drive.

**Comment by Shou** [comment]
Something like this? Although maybe "image size too big" "actual image size too big" or some such?

![image](https://cloud.githubusercontent.com/assets/819413/23359519/7716ee38-fcde-11e6-8d6e-a8fa7cba9712.png)

**Comment by lurch** [comment]
Might also be worth having an option to display the exact byte-sizes of both the uncompressed image and the drive in that scenario too, since with the units currently being always-rounded to GB, a "7.5GB" image may not actually fit on a "7.5GB" drive, if the image is even a few kilobytes larger than the drive.

**Comment by lurch** [comment]
Hmm, looking at @Shou 's screenshot I guess we need to be careful to try and keep the "warning label" small - maybe @konmouz has some ideas?

**Comment by Shou** [comment]
@lurch yeah, good call. Perhaps "Image Size Bigger By x units" and we just display in the appropriate human readable unit?

**Comment by jviotti** [comment]
Let's bring @konmouz here.

**Comment by konmouz** [comment]
2 options:
- we can have a 'insufficient space' label and on hover a tooltip with details (what @lurch suggested)
- avoid the label and have just an the alert/ danger icon with the explanation, all in red - no tooltip

BTW, @Shou why the above element has two labels? System and boot? It would be better to stick to 1 label per drive.

**Comment by jviotti** [comment]
I think I like the second option more, given that a tooltip might not be very discoverable unless the user however on the badge. In order to continue the brainstorm session: what about displaying the size that doesn't fit instead? E.g: You need 300 more MBs for the image.

**Comment by konmouz** [comment]
@jviotti this sounds even better. So using the label font size and the alert icon, we can display such a message.  - Or, 300 MBs more are required for the selected image. -

**Comment by lurch** [comment]
> BTW, @Shou why the above element has two labels? System and boot?

It's actually System and Source ;-)  But yeah, it probably makes sense to only show one warning-label-per-drive, and I guess in this instance `Source` is 'more important' than `System` (a system drive *may* be writable, but a source drive (where the image is being read from) never will be).

With regards to the "too small" label message, what about "Drive is 300MB smaller than image" ?

**Comment by konmouz** [comment]
Sounds good to me, we should probably add the word 'selected' though, just to help user understand.

**Comment by alexandrosm** [comment]
The "source" label doesn't sound like something I'd understand, nevermind
my mother. Shouldn't we find a better name for it?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by lurch** [comment]
I guess `Source` was chosen, as it's the logical-opposite of `Destination`, but you're right that it doesn't make much sense when seen in isolation. Difficult to thing of a more meaningful label though... what about something like "Image source" or "Image location" instead of "Source Drive"?

**Comment by jviotti** [comment]
I created new issues to track some of the suggestions mentioned here: 

- https://github.com/resin-io/etcher/issues/1143
- https://github.com/resin-io/etcher/issues/1144
