### ISSUE TITLE
Error when closing the new version notification popup

### ISSUE THREAD

**Issue by emirotin** [resin-io/etcher#1139]
- **Etcher version:** beta.18
- **Operating system and architecture:** macOS 64bit
- **Do you see any meaningful error information on DevTools?**

![](https://monosnap.com/file/baxSJOuUJlrhK7w5tuqbeFENZzTQpS.png)

**Comment by lurch** [comment]
I've just checked, and I see the same in Linux :-/

**Comment by jviotti** [comment]
At which stage is this happening? Right when you open the app?

**Comment by lurch** [comment]
Start version beta18 of the app (I'm kinda 'cheating' by running `/usr/share/etcher-electron/etcher` from the terminal, which skips setting `ETCHER_DISABLE_UPDATES` (I haven't `apt-get upgrade`d yet)), and the "NEW UPDATE AVAILABLE!" dialog appears. Click on the "X" or on "SKIP", and the error shown by Eugene then appears :-/
(Clicking 'OK' on that error dialog, and Etcher seems to continue to run fine as normal)

**Comment by jviotti** [comment]
I can confirm this issue was fixed by https://github.com/resin-io/etcher/pull/1083!

**Comment by lekkas** [comment]
Just bumped into this after selecting `skip` in the update notification. Using `beta18`, I'll update to the latest version

**Comment by jviotti** [comment]
Yeah, this bug is trending massively high on TrackJS as you can imagine :P
