### ISSUE TITLE
Error: spawn UNKNOWN on Windows during burn

### ISSUE THREAD

**Issue by mkeegan** [resin-io/etcher#1142]
Hi folks! Mathew over at [Kano](https://www.kano.me) here. We love Etcher, and now recommend it to all 100,000 of our customers!

We've noticed a few folks on Windows running into this rather cryptic error message. They're using v1.0.0-beta.19 trying to install Kano OS 3.8.0. 

![image](https://cloud.githubusercontent.com/assets/1509271/23369001/cc56b292-fd07-11e6-8165-5258d318d0bb.png)

We're pretty exclusively Mac-based at HQ, but we tried a Windows 10 machine and couldn't replicate the issue. Is there any more info you'd like us to follow up with?

**Comment by jviotti** [comment]
Hi Mathew,

Thanks a lot for reaching out :) We're always chasing these obscure Windows issues, which seem to always happen sporadically.

Are you sure this is on v1.0.0-beta.19? The screenshot seems to be running v1.0.0-beta.17.

It'd be nice to know at which stage this error happened. E.g: did it happen while flashing? If so, where? during the flash stage? During the validation stage? At which point? At the beginning of the validation phase? 

Such information would help us sketch some hypothesis of how this could happen, so we can have a better chance of reliably reproducing.

Here are some thoughts based on the information we have at the moment:

The error is during spawn (the `execFile` function, precisely). There are a couple of places this happens:

- The drive detection system

At a certain interval (2 seconds at the moment), we spawn a VBScript script that communicates with WMI to get the current drives information. This starts happening as soon as the app is started, but stops during flashing.

- The elevation system

In order for the elevation mechanism to take place, two spawns happen in the middle: one to re-execute the child writer proxy with elevation once the elevation dialog is accepted, and another one when the writer process is started.

- Drive unmounting

We unmount the drive before and after the flash.

***

Another good information to have is the exact image that was used to flash the error, and also the full path where the image was located (path weirdness could be the issue, so we should discard that as well), and whether Etcher was installed to program files, or was ran using the standalone ZIP that we publish on the website.

Thanks a lot again, we'll hopefully get to the bottom of it!

**Comment by jviotti** [comment]
I'm leaving out the "component:" tag since we don't know where exactly the issue came from.

**Comment by jviotti** [comment]
Also: do you know if the user can actively reproduce this? If so, could you ask him to open DevTools (with Ctrl+Alt+I) and paste the whole thing here?

**Comment by mkeegan** [comment]
Looks like copy/paste fart on the version number. Thanks for the extra info, I'll create a bulletin sheet for the customer service folks to get more info when these happen!

**Comment by jviotti** [comment]
Sounds great, let us know how that goes!

**Comment by jviotti** [comment]
I accidentally found the root cause of this issue. It happens when you unplug an SD Card during flash/validation from an internal reader (related to https://github.com/resin-io/etcher/issues/1124).

I'll provide a nice user friendly error message like in the other cases.

**Comment by jviotti** [comment]
![capture](https://cloud.githubusercontent.com/assets/2192773/25060053/98103d5e-2161-11e7-89a6-5287638826b9.PNG)
![capture2](https://cloud.githubusercontent.com/assets/2192773/25060054/9814fa6a-2161-11e7-93d8-0dac762f68d7.PNG)

**Comment by jviotti** [comment]
Oh, wait. The original error says `spawn UNKNOWN`, while this says `UNKNOWN: unknown error`. Maybe its yet a different one?

**Comment by jviotti** [comment]
This is definitely coming from drivelist. Sentry shows similar errors on 1.0.0-rc.5, in which we don't spawn for elevation nor for unmounting anymore

**Comment by lurch** [comment]
Please see https://github.com/resin-io/etcher/pull/1574#issuecomment-315054168
