### ISSUE TITLE
Don't show System Drive and Source Drive badges at the same time

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1143]
From https://github.com/resin-io/etcher/issues/1136

![7716ee38-fcde-11e6-8d6e-a8fa7cba9712](https://cloud.githubusercontent.com/assets/2192773/23408208/a3c80a38-fd9d-11e6-81a3-a529eada156a.png)

Which one should we prefer though? @konmouz ?

EDIT: Originally from https://github.com/resin-io/etcher/issues/1136#issuecomment-282776898

**Comment by WasabiFan** [comment]
I think there's a case to be made for keeping both: Doing so reinforces the meaning of "source drive" (or whatever you rename it to) so that the user has a reasonable means of understanding that label.

**Comment by jviotti** [comment]
That's a good point as well. Up to @konmouz I guess.

**Comment by konmouz** [comment]
@jviotti I am not sure if I am the better to answer this, it is a bit technical. Is source drive a boot drive? We need to find a name that represents this drive and fits in one label.

**Comment by jviotti** [comment]
@konmouz The source drive is the drive that contains the image that you previously selected (not necessarily a system drive)

**Comment by konmouz** [comment]
@jviotti, ok I was completely out of topic. Now it makes sense why you might need two. So, since a 'source' drive is only one at a time, it should have a different color label (for instance orange). Also, may worth renaming to 'image source' and of course the drive would be greyed out. Maybe in that sense, we don't need the second label even if the drive is system or boot drive.

**Comment by jviotti** [comment]
Perfect, I'll close this issue then!

**Comment by lurch** [comment]
> Now it makes sense why you might need two. (...)
Maybe (...) we don't need the second label even if the drive is system or boot drive.

I'm not quite sure I follow. Which "second label" are you suggesting we omit @konmouz ?

**Comment by lurch** [comment]
Re-opening this issue...
