### ISSUE TITLE
Make images out of SD cards

### ISSUE THREAD

**Issue by Mo3tasm** [resin-io/etcher#1153]
Great application, does what it says it does beautifully,

if it just can make Images from SD cards as backups or to image them to other SD cards (I know there's a suggestion to make Etcher copy an SD card to another on the flay, but sometimes you need to do it manually).

Thanks a lot guys.

**Comment by Mo3tasm** [comment]
Win32DiskImager does this the stupid way, by copying the whole SD card to hard disk, without worrying about how much data is actually being used and how much is free, but still, sometimes it's very useful.

**Comment by jviotti** [comment]
Hi @Mo3tasm ,

Thanks for reaching out. We're tracking this feature at https://github.com/resin-io/etcher/issues/266. Keep an eye there for updates!
