### ISSUE TITLE
option to enable ssh by default

### ISSUE THREAD

**Issue by chrowe** [resin-io/etcher#1164]
The new Raspian image comes with ssh by default, but you can enable it by adding `ssh` to the `boot` partition. https://www.raspberrypi.org/blog/a-security-update-for-raspbian-pixel/

It would be great if Etcher could provide an option to do this.

**Comment by jviotti** [comment]
This issue falls inside https://github.com/resin-io/etcher/issues/718, which aims to provide configuration support, so let's track progress over there.

**Comment by chrowe** [comment]
Just noting that all this takes is a single command `touch /Volumes/boot/ssh`
