### ISSUE TITLE
Windows 7: Removable drive detected as a system drive

### ISSUE THREAD

**Issue by Ruffturn** [resin-io/etcher#1166]
- 1.0.0-beta.19
- Win7
- Don't know what this is:**Do you see any meaningful error information on DevTools?**
Doesn't help:<!-- You can open DevTools by pressing `Ctrl+Alt+I`, or `Cmd+Alt+I` if you're running OS X. --

"Connect a drive" is highlighted but there is no hyperlink related to the highlighted icon. In other words, I can select an image but I cannot do anything with it. I have a thumb drive, an ext USB rive and my C drive and it does not allow me to select a drive to write an image to. If it needs a CD or DVD, I have no use for this. Thanks.>

**Comment by jviotti** [comment]
Hi @Ruffturn,

"Connect a drive" is not a button. Etcher tries to filter out non removable drives by default, so it will avoid showing your C drive and your external USB drive, however the thumb drive should be detected just fine. If for some reason Windows is detecting it as a non removable drive, you can enable "Unsafe mode" in the setting page (the cog icon in the top right corner), which will disable such check.

**Comment by Ruffturn** [comment]
I'll try that. Thanks.


Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone
-------- Original message --------From: Juan Cruz Viotti <notifications@github.com> Date: 3/8/17  5:39 PM  (GMT-05:00) To: resin-io/etcher <etcher@noreply.github.com> Cc: Ruffturn <ruffturn@embarqmail.com>, Mention <mention@noreply.github.com> Subject: Re: [resin-io/etcher] "Connect a drive" has no options (#1166) 
Hi @Ruffturn,
"Connect a drive" is not a button. Etcher tries to filter out non removable drives by default, so it will avoid showing your C drive and your external USB drive, however the thumb drive should be detected just fine. If for some reason Windows is detecting it as a non removable drive, you can enable "Unsafe mode" in the setting page (the cog icon in the top right corner), which will disable such check.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/resin-io/etcher","title":"resin-io/etcher","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/resin-io/etcher"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jviotti in #1166: Hi @Ruffturn,\r\n\r\n\"Connect a drive\" is not a button. Etcher tries to filter out non removable drives by default, so it will avoid showing your C drive and your external USB drive, however the thumb drive should be detected just fine. If for some reason Windows is detecting it as a non removable drive, you can enable \"Unsafe mode\" in the setting page (the cog icon in the top right corner), which will disable such check."}],"action":{"name":"View Issue","url":"https://github.com/resin-io/etcher/issues/1166#issuecomment-285193311"}}}

**Comment by jviotti** [comment]
In case that works, do you mind running the following script on your computer while the problematic drive is plugged in and report back the results? https://github.com/resin-io-modules/drivelist/blob/master/scripts/win32.bat

**Comment by jviotti** [comment]
@Ruffturn Did you get a chance to run the script?

**Comment by jviotti** [comment]
I'll close this issue, given we don't have any information to proceed. Please re-open if you find the time to run the script linked above.
