### ISSUE TITLE
bad archive!!! isuuse

### ISSUE THREAD

**Issue by bonda007** [resin-io/etcher#1178]
- **Etcher version:** latest 
- **Operating system and architecture:** mac osx lateset
- **Do you see any meaningful error information on DevTools?** nope

**Comment by lurch** [comment]
I'm afraid there's nothing we can do with the little information you've given us above ;-)

Can you let us know what image you were trying to flash? A link to the image so we can download it ourselves to try to reproduce this problem would be great.

**Comment by jviotti** [comment]
This means that the ZIP that you're selecting has no images, or more than one image, confusing Etcher. Please make sure the ZIP you're trying to flash is a valid archive image.
