### ISSUE TITLE
Check if an image has a MBR or GPT, and complain if not

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1189]
Images without a MBR nor GPR will probably not boot. This simple check covers most edge cases:

- Hybrid ISOs still have a MBR
- Windows images don't have a MBR

**Comment by jhermsmeier** [comment]
We should probably still let the user decide if they want to proceed with flashing, to avoid false positives from getting in the way.

**Comment by lurch** [comment]
Is this a duplicate of #553 ? ;-)

**Comment by jviotti** [comment]
Good catch. I'll close the other one in flavour of this, which sets a clearer way forward.

**Comment by jhermsmeier** [comment]
Closing, as has been done in https://github.com/resin-io/etcher/pull/1248
