### ISSUE TITLE
Ability to submit auto-filled issues from Etcher

### ISSUE THREAD

**Issue by Shou** [resin-io/etcher#1198]
Something like a button or other that when triggered opens a link to a new Github issue, partially filled with information from their local Etcher. Such information can be the version string, system, processor architecture, and more.

Example: https://github.com/resin-io/etcher/issues/new?title=foo&body=bar

**Comment by lurch** [comment]
Perhaps this could tie in with the work done in #1888 ?

**Comment by jhermsmeier** [comment]
Yeah, indeed it would be nice to have a bug-reporter in Etcher that will also bundle some more data and could open an issue with all of it attached. Could also add a report generated by [node-report](https://github.com/nodejs/node-report) or so
