### ISSUE TITLE
Drag and drop is broken

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1230]
When dropping an image, nothing happens.

It seems that we're passing the file path to `ImageSelectionController.selectImage()`, which expects an image object instead.

**Comment by lurch** [comment]
I note that #853 is still open...

**Comment by Shou** [comment]
Drag'n'drop works here on master and the console logs an image object. Where are you experiencing it?

**Comment by jviotti** [comment]
Oh, that's weird. It works for me from `master` as well. Maybe its an issue coming from https://github.com/resin-io/etcher/pull/1229? Can you check if you can reproduce from your side from that branch?

**Comment by jviotti** [comment]
Yeah, that seems to be it. Sorry for the noise. I'll fix it myself.
