### ISSUE TITLE
Drag and drop doesn't use the manifest information

### ISSUE THREAD

**Issue by Shou** [resin-io/etcher#1232]
When dragging and dropping a ZIP with a manifest name, the filename is used instead. Using the normal file selector dialog doesn't cause this to happen. It seems that the ZIP file is used as-is rather than the residing image—I'm not sure if this affects the actual writing but I suspect it might, which isn't good.

Screenshots of drag and drop versus through the file selector.
![image](https://cloud.githubusercontent.com/assets/819413/24452688/50535952-147c-11e7-9a99-1393cd2975fa.png)
![image](https://cloud.githubusercontent.com/assets/819413/24452706/6c1eb7ee-147c-11e7-81f2-f13c1bcaa68f.png)

Edit: it also uses the compressed size rather than uncompressed.

![image](https://cloud.githubusercontent.com/assets/819413/24454208/eb2dd6a4-1482-11e7-9ac8-41d552f9af9c.png)

**Comment by jviotti** [comment]
Ugh, looks like we should make sure we use the same logic in both scenarios.

**Comment by jviotti** [comment]
I think I coincidentally solved this issue while fixing drag and drop for https://github.com/resin-io/etcher/pull/1229. Do you mind pulling my latest changes from that PR and confirming that it solves the issue for you too? If so, I'll add a "Fixes" footer tag to the commit.

**Comment by lurch** [comment]
Wow, I never imagined my [refactoring suggestion](https://github.com/resin-io/etcher/pull/1223#discussion_r108165110) would lead to fixes in the drag'n'drop code too. Awesome! :-D

**Comment by jviotti** [comment]
Don't be humble, you knew that from the start! :P

**Comment by lurch** [comment]
@Shou Is this indeed resolved by #1229 ? If it is, should this PR #1232 be closed?

**Comment by Shou** [comment]
Yup. We can close this once it gets merged.

**Comment by jviotti** [comment]
I added a "Fixes" tag to the PR.
