### ISSUE TITLE
OSX remounting bug

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher#1282]
User reports that Etcher is remounting their drive after flashing, even though they have "Auto-unmount on success" enabled.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1g41)

**Comment by pelicanmedia** [comment]
+1 on this

**Comment by lurch** [comment]
@pelicanmedia Can you provide details of which image you were writing please?

**Comment by pelicanmedia** [comment]
Sure... The latest Raspbian image from [raspberrypi.org](https://downloads.raspberrypi.org/raspbian_latest)

**Comment by jviotti** [comment]
Looks like https://github.com/resin-io/etcher/issues/1385 is a duplicate of this one. I'll close this one since the other issues contains way more information.
