### ISSUE TITLE
[website]: semantics of debian packages

### ISSUE THREAD

**Issue by dlech** [resin-io/etcher#1291]
In the downloads section of https://etcher.io/, it says "Looking for debian images?". What is should really say is "Looking for Debian (.deb) packages?" or something similar. When I read "debian images", it makes me think an ISO used to install Debian rather than a Debian package used to install Etcher.

**Comment by jhermsmeier** [comment]
Good catch! But that's probably best filed over at https://github.com/resin-io/etcher-homepage :)

**Comment by dlech** [comment]
Thanks. I didn't know there was a repo for that.
