### ISSUE TITLE
More room for showing filename and disk name?

### ISSUE THREAD

**Issue by dlech** [resin-io/etcher#1292]
- **Etcher version:** 1.0.0-rc2
- **Operating system and architecture:** Ubuntu 16.04 x64 
- **Do you see any meaningful error information on DevTools?** N.A

We could make more room for displaying the image file name and the disk name if we moved the sizes below instead of on the same line.

In the example below, my drive name is "STORAGE DEVICE", which is not unreasonably long, so it would be nicer if it was not truncated.

![etcher_014](https://cloud.githubusercontent.com/assets/963645/24970981/dca91aa4-1f7b-11e7-997b-776a8a3634a9.png)

**Comment by jviotti** [comment]
Thanks for the idea @dlech. Let's bring @konmouz on the loop. Maybe we can improve this somehow on the v2 design?

**Comment by konmouz** [comment]
@jviotti, Indeed on v2 we don't have this issue. The old solution for that was to use a two line system. The only concern here is that the 'change' button wouldn't appear as clear as it appears now (there will be 3 lines: name - size - change CTA). I'll upload a screenshot to see how it might look.

**Comment by konmouz** [comment]
<img width="923" alt="screen shot 2017-04-13 at 11 58 39" src="https://cloud.githubusercontent.com/assets/15323961/25002103/8e904dfe-2040-11e7-9293-8c73b39f4266.png">

**Comment by jviotti** [comment]
Sounds good @konmouz. I'll assign @Shou in case he has some time to tweak the v1.0 design as proposed, but definitely not very high priority if this is getting fixed on v2 already.
