### ISSUE TITLE
Setup Electron crash reporter

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1311]
See https://electron.atom.io/docs/api/crash-reporter/.

We should deploy a small server for this: https://github.com/electron/mini-breakpad-server

**Comment by lurch** [comment]
Interesting. Could / should this be part of resin-corvus, or is this more low-level than that?

**Comment by jviotti** [comment]
Oh, that's a very good idea. @stefan-mihaila what do you think? The tricky part is that this code should be ran on the main process before everything else. resin-corvus could expose a function to configure it that we call there.

**Comment by lurch** [comment]
Pinging @izavits in case this is something that relates to resin-analytics?

**Comment by izavits** [comment]
We could probably include an integration in the analytics lib for this.

**Comment by jhermsmeier** [comment]
@izavits wouldn't that be a bit too specific towards Electron apps?

**Comment by izavits** [comment]
@jhermsmeier is it something that can be covered by sentry?

**Comment by jviotti** [comment]
This is very Electron specific, and not something that can be covered
with any other JS third party tool given that its part of the C++ side
of things.

On Thu, Mar 01, 2018 at 08:02:52AM +0000, Ilias Zavitsanos wrote:
> @jhermsmeier is it something that can be covered by sentry?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io/etcher/issues/1311#issuecomment-369508212

-- 
Juan Cruz Viotti
Software Engineer
