### ISSUE TITLE
Switch speed and time below the progress bar

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1312]
Put the speed on the left and the time on the right.

**Comment by lurch** [comment]
I don't mean to sound pedantic, but isn't being in the ReleaseCandidate phase a bit late for this kind of change?
(just out of curiosity, why switch them anyway?)

**Comment by jviotti** [comment]
We definitely don't need to do this right now (maybe for v2)? It was just a though by @alexandrosm, so it felt more natural.

**Comment by lurch** [comment]
Ahhh, fair enough :-)
Yeah, I think if this is changed we should save it for V2, with input from @konmouz too of course.
