### ISSUE TITLE
Make use of electron-link to improve startup time

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1323]
See https://github.com/atom/electron-link and http://blog.atom.io/2017/04/18/improving-startup-time.html

**Comment by lurch** [comment]
Interesting - the first link makes much more sense (forbidden modules - wtf?) after reading the second link ;-)
Sounds like it's actually the use of V8 snapshots that speeds up the startup time, and `electron-link` is merely the tool that makes your electron code more "snapshot-able".

**Comment by lurch** [comment]
Connects to #1138
