### ISSUE TITLE
Inject a tag to builds to determine where they came from

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1328]
For example, we can have an "AppImage" tag, or an "installer" or "standalone" tag for Windows. We can then send that to Mixpanel.

**Comment by lurch** [comment]
We should probably break down "installer" into "downloaded from the Etcher website" and "installed by chocolately"? Or is that level of distinction not possible? Does "standalone" mean the "portable" version?

Similarly on Linux, it might be nice if we could tell if the user had installed the .deb file by downloading it from S3, or if they'd installed it from bintray.
