### ISSUE TITLE
Add a JSON file to S3 build directories to control what triggers an update notification

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1329]
Currently, if Etcher detects that all builds are present in S3, it will show a notification to the user. We want to have a json file in each of the S3 sub directories for fine grained control. For example:

- Only show update notification dialogs for the Linux builds of this version
- Don't show update notifications at all for this version

etc

**Comment by lurch** [comment]
Ping @jhermsmeier as I guess this ties into the "gradual releases" thing that got discussed a while ago.
