### ISSUE TITLE
Release checksums and/or signed releases

### ISSUE THREAD

**Issue by imrehg** [resin-io/etcher#1341]
Sort of a release thing that could go under [etcher-homepage](https://github.com/resin-io/etcher-homepage) as well, but maybe more relevant here: would be great to have checksums displayed somehow for the relevant downloads (`md5` / `sha256` are the most common ones), and/or having the releases signed in a way that it can be verified.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1ls7)

**Comment by lurch** [comment]
@jviotti will be able to confirm, but I believe the Windows and Mac builds are already signed?

Also pinging @craig-mulligan as he maintains the https://github.com/resin-io/etcher-homepage

**Comment by jviotti** [comment]
Windows and macOS are code-signed, and we plan to do the same for AppImages at some point.

Showing checksums would be a very nice addition :+1:

**Comment by craig-mulligan** [comment]
Sounds cool, I've added an issue here: https://github.com/resin-io/etcher-homepage/issues/37

**Comment by lurch** [comment]
A `SHASUMS256.txt` is now included on https://github.com/resin-io/etcher/releases for all releases from v1.2.0 onwards, but these checksums aren't displayed on https://etcher.io/ yet.

**Comment by snow8gaia** [comment]
Please, please, please put it on https://etcher.io/ so that its easier for most people. Even a direct link to the [GitHub page](https://github.com/balena-io/etcher/releases) will work. 

I (and some) almost skipped downloading it because of the lack of any checksums.  They help prevent broken downloads on unreliable networks. Happens quite frequently in a lot of places. 

Thanks a lot.

**Comment by Quantumplation** [comment]
Is there a reason you stopped providing these checksums?

**Comment by lurch** [comment]
The checksums _are_ still available, but they're in a slightly weird format :confused: #2826
