### ISSUE TITLE
Store settings in an `.etcherrc` file instead of in local storage

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1356]
We could also allow overriding these options with environment variables, but that's a bonus item.

**Comment by lurch** [comment]
So we're actually "downgrading" from a database to a flat text file, instead of the other way around? ;-D

**Comment by jviotti** [comment]
Haha, exactly. This is particular useful for the hard etcher project, since automatically tweaking certain settings is very difficult/impossible, while a plain text configuration file makes it simpler.
