### ISSUE TITLE
Add Make targets to perform gyp operations targetting either electron or node

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1375]
We have various gyp npm scripts (`configure`, `build`, `install`) that only operate on the node context unless the right environment variables are set. We should define these in the Makefile as easy to use targets that work in either context, as needed.

This would allow us to easily iterate on C++ code without having to run a full `make electron-develop` each time.

**Comment by lurch** [comment]
Afraid I don't understand the context here, but is this still an issue?
