### ISSUE TITLE
Website throws error on IE 11

### ISSUE THREAD

**Issue by Grandpa-G** [resin-io/etcher#1381]
The etcher.io webpage has an error using IE 11 and immediately says "there is an unexpected error"

**Comment by lurch** [comment]
Ping @craig-mulligan

**Comment by craig-mulligan** [comment]
@Grandpa-G, Thanks for the heads up! We were missing some polyfills for older browsers. I've [amended](https://github.com/resin-io/etcher-homepage/blob/master/.babelrc#L6-L10). 

Please let me us if that fixes your issues.

**Comment by Grandpa-G** [comment]
Just verified that it works. Sometimes we don't see what we make. Glad I could help.

**Comment by craig-mulligan** [comment]
Great! @lurch this is good to close.

**Comment by alexandrosm** [comment]
@craig-mulligan can we make sure this is fixed before launch?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm
