### ISSUE TITLE
Etcher fails to start on Windows if its placed on a directory containing a percentage sign

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1399]
![percentage](https://cloud.githubusercontent.com/assets/2192773/25872640/85a774bc-34d9-11e7-840f-4a35a274a9d9.PNG)

**Comment by lurch** [comment]
Is this an Etcher bug, an electron bug, or a packaging bug?

**Comment by jviotti** [comment]
I have no clue, but I wanted to report it before I forget about it. We can look into it in more detail after the v1.0.0 release.
