### ISSUE TITLE
Feature request: show flashing percents in the window headbar

### ISSUE THREAD

**Issue by TotalCaesar659** [resin-io/etcher#1427]
Hello, could you add flashing percents to the window headbar? It's not comfortable to check progress manually.
![1](https://cloud.githubusercontent.com/assets/14265316/26037646/18981d60-3900-11e7-8d08-0496d78c6766.png)

**Comment by lurch** [comment]
I guess you mean dynamically changing the title bar to e.g. `Etcher - Flashing 32%` or `Etcher - Validating 64%` ?
What do you think from a UX perspective @konmouz ?

**Comment by jviotti** [comment]
Sounds good to me, but I wonder if this is a common practice for desktop apps. Let's get feedback from the design team.

**Comment by konmouz** [comment]
@lurch & @jviotti This is a common practice in many applications. It is pretty much what we already do with the app icon and the progress bar (at least on mac). Sounds a nice addition to me.

**Comment by jviotti** [comment]
OK, cool, let's go for it!
