### ISSUE TITLE
Word-wrap properly in the drive-selection dialog

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher#1437]
As pointed out in [gitter](https://gitter.im/resin-io/etcher?at=591a1dcad1a7716a0accc62f) it seems that sometimes the line-wrapping breaks in the wrong place :-(
![image](https://cloud.githubusercontent.com/assets/476186/26100944/4b5437c0-3a27-11e7-801b-4c6245be8e96.png)

In the screenshot above, `15.9` shouldn't be split over two lines.

**Comment by Shou** [comment]
So we need `word-break: break-all` in case of long names, but what we could do here is wrap the size in its own span element and apply `word-break: keep-all` there, so only the whole span will wrap over.
