### ISSUE TITLE
Check for "invalid" CLI options?

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher#1454]
- **Etcher version:** CLI 1.0.0

I noticed that if you specify e.g. `--yes` to specify non-interactivity, but then don't specify `--drive`, you still get an interactive prompt asking you to choose a drive :-/
Would it make more sense for specifying `--yes` without `--drive` to simply print an error and then exit?

**Comment by jviotti** [comment]
I agree, let's make that fix!
