### ISSUE TITLE
Raspberry pi???

### ISSUE THREAD

**Issue by harshil2105** [resin-io/etcher#1479]
Can etcher be used for raspberry pi....like id don't see any installs for raspberry pi and I can't use linux packages to run etcher in raspberry pi

**Comment by Modelmat** [comment]
Try installing from source.

**Comment by jviotti** [comment]
Hey there!

We don't officially provide ARM packages yet, but we plan to do so very soon. That being said, as @Modelmat pointed out, you can build Etcher from source, which has been proven to work on Raspbian.
