### ISSUE TITLE
Avoid "not large enough" checks for Windows drives that report themselves as 0.0 GB

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1483]
See https://github.com/resin-io-modules/drivelist/issues/142

In summary, WMI sometimes fails to detect the real size of the drive, and detects a unreasonably small drive size (e.g. 8 MB) that gets coerced into 0.0 GB by the Etcher UI.

We have a real fix for this (which involves to re-write drivelist on C++), but let's make Etcher not take the size of these problematic drives into consideration for now.

**Comment by lurch** [comment]
Umm nope, this is in fact opposite to what @alexandrosm was suggesting in gitter!
We don't want to filter out (ignore) drives that report themselves as 8MB, we want to ignore the size they report, and allow any-size-image to be written to them anyway.

**Comment by jviotti** [comment]
Yeah, my bad, I totally mixed things up. I'll rephrase the issue.

**Comment by alexandrosm** [comment]
basically we should set a "minimum plausible drive size" and ignore any responses that are below that, simply reporting them as "unknown size", and as a result, not applying any size checks

**Comment by lurch** [comment]
...and there's then a nice symmetry between drives who's size we don't know, with images who's size we don't know ;-)

**Comment by lurch** [comment]
Please see https://github.com/resin-io/etcher/pull/1574#issuecomment-315054168
