### ISSUE TITLE
HI i am trying to flash 64gb Micro sd card format is fat32 for a raspberry pi it is not working

### ISSUE THREAD

**Issue by MatthewRead42** [resin-io/etcher#1485]
- **Etcher version:** 1.0.0
- **Operating system and architecture:** 10.10.5 OS X
- **Image flashed:** ubuntu mate 16.04.2 
- **Do you see any meaningful error information in the DevTools?** it as not flashed properly do you want to retry

**Comment by jviotti** [comment]
Hi @MatthewRead42 ,

Can you elaborate on why "it is not working"? Do you see an error? If so, at which stage?

**Comment by MatthewRead42** [comment]
After it verifies the drive

**Comment by jviotti** [comment]
Can you send us a screenshot of the error?

**Comment by MatthewRead42** [comment]
![screen shot 2017-06-02 at 00 39 44](https://cloud.githubusercontent.com/assets/18283473/26705182/5abd3088-472c-11e7-9754-52c7656ce9cf.png)
![screen shot 2017-06-02 at 00 41 12](https://cloud.githubusercontent.com/assets/18283473/26705183/5af4f6d0-472c-11e7-8c17-d306de3e74b3.png)

**Comment by MatthewRead42** [comment]
It is a new sd card and i have used a different card to a 256gb and I got the same problem?

**Comment by jviotti** [comment]
Can you try another SD Card reader? Etcher will display that error even when a single byte has been written incorrectly, and it may mean that is catching subtle write failures due to either the SD Cards or the reader.

**Comment by MatthewRead42** [comment]
ok thanks

**Comment by jviotti** [comment]
Keep in mind you can disable validation on the settings page (the cog in the top right corner), but I'd highly advise not do, since there is really something going on that Etcher is catching here.

**Comment by Oscarz90** [comment]
I had the same problem with a sd card of 64gb, I think that it's related with micro sd of big capacity......

**Comment by lurch** [comment]
I suspect the bigger the card, the higher the chances of it being a "fake" card?
