### ISSUE TITLE
Formatting optimised for SD cards

### ISSUE THREAD

**Issue by jan-kleks** [resin-io/etcher#1497]
There is this app called SD Card Formatter made by the official SD Association. [On their website](https://www.sdcard.org/downloads/formatter_4/) they claim that:

`The SD Card Formatter was created specifically for memory cards using the SD/SDHC/SDXC standards. It is strongly recommended to use the SD Card Formatter instead of formatting utilities provided with operating systems that format various types of storage media. Using generic formatting utilities may result in less than optimal performance for your memory cards.`

**If this is true** that SD cards formatting can be optimised in some way, it might be worth considering adding such a functionality to Etcher (it's used with SD cards, so why not?). It's also worth noting that SD Card Formatter by the SD Association is available only for Windows and macOS, and it's not open-source...

**Comment by lurch** [comment]
Etcher doesn't "format" SD cards, it merely copies disk images byte-by-byte onto the SD card. As such, any 'format' is entirely up to the image you've selected to flash. Closing this issue as invalid.

Also, as the SD Card Formatter isn't open source, there's nothing we could learn from it even if Etcher _did_ have a card-formatting function.
