### ISSUE TITLE
Raspberry Pi website links to your product however I'm not able to get x64 to install.  --> "Unable to locate package etcher-electron"

### ISSUE THREAD

**Issue by santarosajoe** [resin-io/etcher#1498]
- **Etcher version: from website x64
- Pi 3B

**Comment by lurch** [comment]
Are you trying to run Etcher itself on your Raspberry Pi? This currently won't work as Etcher is currently only built for x86 and x64 CPU types, and the Raspberry Pi has an ARM CPU type.

However we _are_ hoping to have ARM builds of Etcher (which will run on the Pi 2 and Pi 3) at some point soon.
