### ISSUE TITLE
unsupported compression method: 9

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher#1499]
- **Etcher version:** 1.0.0
- **Operating system and architecture:** Any
- **Image flashed:** http://www.protoneer.com/files/RPI-CNC-V400.zip
- **Do you see any meaningful error information in the DevTools?**
```
document not ready yet, trying again in 500 milliseconds...
/usr/lib/etcher-electron/resources/app.asar/node_modules/raven-js/dist/raven.js:51 Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
/usr/lib/etcher-electron/resources/app.asar/node_modules/raven-js/dist/raven.js:51  _____ _       _
|  ___| |     | |
| |__ | |_ ___| |__   ___ _ __
|  __|| __/ __| '_ \ / _ \ '__|
| |___| || (__| | | |  __/ |
\____/ \__\___|_| |_|\___|_|

Interested in joining the Etcher team?
Drop us a line at join+etcher@resin.io
/usr/lib/etcher-electron/resources/app.asar/node_modules/raven-js/dist/raven.js:51 Thu Jun 08 2017 12:11:11 GMT+0100 (BST) Application start
/usr/lib/etcher-electron/resources/app.asar/node_modules/raven-js/dist/raven.js:51 Thu Jun 08 2017 12:11:11 GMT+0100 (BST) Not checking for updates ({"shouldCheckForUpdates":false,"disableUpdatesEnvironmentVariable":"1","releaseType":"PRODUCTION"})
/usr/lib/etcher-electron/resources/app.asar/node_modules/raven-js/dist/raven.js:51 Thu Jun 08 2017 12:11:13 GMT+0100 (BST) Open image selector
/usr/lib/etcher-electron/resources/app.asar/node_modules/raven-js/dist/raven.js:51 {}
console.(anonymous function) @ /usr/lib/etcher-electron/resources/app.asar/node_modules/raven-js/dist/raven.js:51
```
As reported by @htcnish on [gitter](https://gitter.im/resin-io/etcher?at=59386a34e531dbc905bf0e59), when selecting the `RPI-CNC-V400.zip` file, Etcher displays:
![image](https://user-images.githubusercontent.com/476186/26925905-6ca6c36a-4c43-11e7-9061-c87ee22143b2.png)

I managed to track this down to a bug in `yauzl`, and created a ticket with more details there https://github.com/thejoshwolfe/yauzl/issues/58

However in case yauzl doesn't implement this new decompression method before the next release of Etcher, we should probably catch any `unsupported compression method:` error messages, and display a more friendly error-message to the user, so that they don't see the ugly stacktrace.

**Comment by jviotti** [comment]
Now that we merged a PR that shows a friendly message for this (https://github.com/resin-io/etcher/pull/1557), I'll close it as wont-fix, given there doesn't seem to be any zip implementation that supports this, and therefore unlikely that we can move forward in any way.
