### ISSUE TITLE
[enhancement request] Select image from URL

### ISSUE THREAD

**Issue by zafields** [resin-io/etcher#1508]
It would be way cool if you could select images from the web, instead of downloading them and finding them on your hard drive.

For example: [https://downloads.raspberrypi.org/raspbian_latest](https://downloads.raspberrypi.org/raspbian_latest)

**Comment by lurch** [comment]
This is already planned for Etcher V2 https://resin.io/blog/the-future-of-etcher/

Closing this as a duplicate of #54
