### ISSUE TITLE
On OSX, upon starting flash, I get a dialog that "Etcher want to make changes"?

### ISSUE THREAD

**Issue by dteeter** [resin-io/etcher#1526]
Why is giving this type of permission necessary? What is Etcher doing in the back ground if I give that permission?
![screen shot 2017-06-16 at 4 15 00 pm](https://user-images.githubusercontent.com/1538533/27247657-8b67ae1e-52af-11e7-81a6-6be8f5d9e87e.png)

**Comment by deadair3210** [comment]
If OS X is anything like Linux and Windows permission wise, its probably requesting permissions to alter the drive at low level. Needed for block level operations

**Comment by jviotti** [comment]
Hi @dteeter ,

Writing to raw external drives require superuser permissions in all unix based operating systems, including macOS. Etcher is open source, so you can take a look if you want to learn exactly what's happening under the hood.
