### ISSUE TITLE
Upgrade to npm v5

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1528]

**Comment by lurch** [comment]
Duplicate of #1487 ?

**Comment by jviotti** [comment]
Well, that's a PR while this is an issue, so I guess its fine.

**Comment by mykter** [comment]
Heads up: I was using your shrinkwrap cleaner for platform specific dependencies (thanks!) and after upgrading to npm 5 no longer need it. After removing and regenerating the shrinkwrap, npm now just warns about missing optional dependencies that are in the shrinkwrap (finally!).
