### ISSUE TITLE
Build the CLI using pkg

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1531]
See https://github.com/zeit/pkg

**Comment by lurch** [comment]
So does that (effectively) do the same thing as your node-static-entry-point thing?

**Comment by jviotti** [comment]
Yep, but we'll try to re-use as most as we can in order to avoid having to maintain custom code.

**Comment by lurch** [comment]
Should node-static-entry-point now be marked as a 'deprecated' project?

**Comment by jviotti** [comment]
Done!
