### ISSUE TITLE
Integrate pipage in the writer

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1532]
See https://github.com/resin-io-modules/pipage

**Comment by lurch** [comment]
Should there be a 'linked' issue at https://github.com/resin-io-modules/etcher-image-write/issues ?

**Comment by jviotti** [comment]
Up to @jhermsmeier. IMHO, is nicer to unify tickets in the main Etcher project, since its easier to search/tag everything on a single place, but I have no strong opinions neither.

**Comment by jhermsmeier** [comment]
@lurch the pipage stuff is happening in Etcher, and `etcher-image-write` won't be used anymore at that point, hence it'd make sense to only track it here.

**Comment by lurch** [comment]
Ah, so the title should be changed from `Integrate pipage in etcher-image-write` to `Integrate pipage in Etcher` ? ;-) Or even `Replace etcher-image-write with pipage` ?

**Comment by jviotti** [comment]
I rephrased etcher-image-write to "the writer."

**Comment by jhermsmeier** [comment]
Done in #1671
