### ISSUE TITLE
clone repo ....

### ISSUE THREAD

**Issue by calmchess** [resin-io/etcher#1536]
- **Etcher version:**
- **Operating system and architecture:**
- **Image flashed:**
- **Do you see any meaningful error information in the DevTools?**

Is it OK  if I clone deb https://dl.bintray.com/resin-io/debian stable etcher ....as a local repo  on my network ?

**Comment by lurch** [comment]
Sure. As long as you abide by the https://github.com/resin-io/etcher/blob/master/LICENSE you can do whatever you want ;-)

**Comment by jviotti** [comment]
Just out of curiosity, what's the use case @calmchess ?
