### ISSUE TITLE
cli without Electon

### ISSUE THREAD

**Issue by techtonik** [resin-io/etcher#1556]
Etcher-cli-1.0.0-win32-x86.zip

It is surprising that this `dd` clone for Windows is 18Mb in size and doesn't run on older systems, because it requires GUI toolkit.

**Comment by lurch** [comment]
It's already without a GUI toolkit and without Electron - but it does include a NodeJS interpreter.
And Etcher is far more than a 'dd clone'.

**Comment by techtonik** [comment]
> This application is only supported on Windows 7, Windows Server 2008 R2, or higher.

It if doesn't require Electron, why it doesn't work on other systems?

**Comment by jhermsmeier** [comment]
@techtonik that's only supposed to clarify that Windows XP isn't supported anymore. It runs on a wide variety of Linux distributions, and Mac OS as well.

**Comment by lurch** [comment]
I did a quick search, and found https://github.com/nodejs/node/issues/3804 and https://github.com/nodejs/node/pull/5167
If NodeJS itself doesn't support Windows XP, then the Etcher CLI (written in NodeJS) can't run on Windows XP either.

**Comment by techtonik** [comment]
Yea. New NodeJS drops Windows. Too bad Etcher is not written in Go and depends on Windows 7 features that it doesn't use.

**Comment by lurch** [comment]
Etcher is all Open Source, feel free to write your own clone of it in Go ;-)

Just out of curiosity, why do you need Etcher support on older versions of Windows? Are you able to try running it under Linux instead?

**Comment by techtonik** [comment]
Because I used Windows in childhood and I am used to it and besides I still have 3 Linuxes running, I can not use them. I won't buy next Windows, but there is still no software with UX like Far Manager on Linux.

**Comment by lurch** [comment]
> I won't buy next Windows

I'll wish you luck then, as more and more software is dropping support for Windows XP.

> there is still no software with UX like Far Manager on Linux.

That's something I'd never heard of, but a quick search found me: https://en.wikipedia.org/wiki/Far_Manager#Linux_and_MacOS_version

**Comment by jhermsmeier** [comment]
@techtonik why not run Etcher on one of the Linuxes then?

**Comment by techtonik** [comment]
@jhermsmeier good point. Still need to figure out the way to rebind Alt-F1 Alt-F2 on those Linuxes for my own purpose to port my console macros.
