### ISSUE TITLE
Both banners appear when forcing fullscreen

### ISSUE THREAD

**Issue by Shou** [resin-io/etcher#1563]
When the window manager ignores window constraints and fullscreens Etcher, both the fallback and external banners show up. We could solve this by positioning the external banner from `top` instead of `bottom`.

![image](https://user-images.githubusercontent.com/819413/27738458-4a167bc6-5da3-11e7-8df3-4e865842c343.png)

**Comment by lurch** [comment]
> When the window manager ignores window constraints

How common of a situation is that? ;)

**Comment by jviotti** [comment]
@Shou My suggestion in the call was to wrap the contents of the application in a `div`, set a `max-height` and `max-width` to that `div`, and then center it in the window using flexbox. Then, if window manager maximizes the application, the content will remain centered, on the desired dimensions, so the only consequence will be a lot of margins.

**Comment by Shou** [comment]
@lurch I believe most tiling WMs do this, so if you have a tiling WM then most of the time, unless you create rules for Etcher, e.g. make it float, or have a specific size.

@jviotti thanks for the refresher!
