### ISSUE TITLE
Feature request: Use TouchID, when available

### ISSUE THREAD

**Issue by tholu** [resin-io/etcher#1579]
- **Etcher version:** 1.0.0
- **Operating system and architecture:** macOS Sierra, 10.12.5, Macbook Pro with Touchbar

Instead of asking for the password, use TouchID for authentication (if available) when flashing an image.

**Comment by jviotti** [comment]
Hi @tholu ,

That's a very cool suggestion! I'll forward this to `sudo-prompt`, the module we use to handle elevation, and once/if its implemented there, we can then enable it from our side.

**Comment by jviotti** [comment]
See https://github.com/jorangreef/sudo-prompt/issues/53
