### ISSUE TITLE
written image displays tiny boot screen, goes no further on OS X El Capitan

### ISSUE THREAD

**Issue by jbohem** [resin-io/etcher#1601]
Etcher version: 1.0.0
Operating system and architecture OS X El Capitan
Image flashed:kali-2016.2

Runs to completion, no errors. Upon booting from the etched SD card, The boot screen comes up, tiny - occupying the upper left 1/4 of the mac screen. The linux boot menu at that point doesn't respond to the keyboard.

**Comment by jviotti** [comment]
Hi @jbohem ,

If the image validation was successful, then there must be a problem with the image, or the hardware where it was used. Etcher copies the image content byte by byte, without any knowledge about what is flashing, and doesn't manipulate the image in any way.
