### ISSUE TITLE
Etcher-cli: list of flashable devices

### ISSUE THREAD

**Issue by tangb** [resin-io/etcher#1615]
Hi

I want to use etcher-cli on linux mac and windows and I'm looking for a way to detect flashable devices on all platforms.
Is etcher-cli able to return available flashable devices?

Thank you for your answer ;)

**Comment by lurch** [comment]
Not at the moment, but https://github.com/resin-io-modules/drivelist is able to do that :)

**Comment by lurch** [comment]
See also https://github.com/resin-io/etcher/issues/1420#issuecomment-301581820

**Comment by lurch** [comment]
@tangb Is `drivelist` able to provide you the info you're looking for (in which case can this issue be closed?), or is there something more specific you're looking for from etcher-cli?

**Comment by jhermsmeier** [comment]
@lurch I think the intention is to list the available drives from the CLI, to see which one to flash. But that's also already available; if you omit the --drive option you'll be presented with a list of devices to select from, i.e.:

```
$ etcher ~/Downloads/something.img
? Select drive (Use arrow keys)
❯ /dev/disk2 (31.9 GB) - SD Card Reader
```

Closing, as this feature is already available

**Comment by tangb** [comment]
@jhermsmeier  My first intention was to list available drives from python. So i was looking for if etcher-cli was able to return me that list.
Finally I find another way to do the job, looking how it was done in drivelist.
Anyway the "feature" can be closed

Thank you

**Comment by jhermsmeier** [comment]
Sorry that I misunderstood; in that case you're really looking for [drivelist](https://github.com/resin-io-modules/drivelist) 😄
