### ISSUE TITLE
Terminal says "E: Unable to locate package etcher-electron. NEED URGENT HELP!

### ISSUE THREAD

**Issue by somebodynamedjason** [resin-io/etcher#1618]
- **Etcher version: Latest**
- **Operating system and architecture: Raspbian Lite with MATE Desktop Environment**
- **Image flashed: n/a**
- **Do you see any meaningful error information in the DevTools? n/a**

I have the proper configurations and have the proper sentence written in the etcher.list file, so this should be working. I have this installed on my Windows 10 computer, but would also like to get it working on my Raspberry Pi so that I do not have to switch computers in order to write disk images.

Hope somebody can get back to me soon about this issue. For now I will just use Windows 10, as that seems to be working.

If it helps for you to know, I am fairly new to linux, so I don't know too much about the operating system. Some things may be a little confusing.

In advance, thanks for the help! (If anybody responds, that is).

**Comment by lurch** [comment]
The Raspberry Pi has an ARM CPU, whereas we currently only provide Linux builds of Etcher for the x86 and x64 CPUs. We're planning to release an ARM build "soon" (which _will_ work on the Raspberry Pi), but we're not sure exactly when yet.
