### ISSUE TITLE
Flash Drive not visible (different output from diskutil)

### ISSUE THREAD

**Issue by clounie** [resin-io/etcher#1622]
- **Etcher version:** 1.0.0
- **Operating system and architecture:** macOS 10.12.5
- **Image flashed:** Zorin OS 12.1 Ultimate x64 (Ubuntu-based Linux distro)
- **Do you see any meaningful error information in the DevTools?** No
- **Other (possibly) relevant details:** I'm using a Dell USB-A to USB-C [adapter](http://accessories.ap.dell.com/sna/productdetail.aspx?c=sg&l=en&s=bsd&cs=sgbsd1&sku=470-abnl) to flash it from my 2016 Macbook Pro.

This relates to #649 and #828.

I have a SanDisk 32GB flash drive than I'm using to flash, and like the previous two, Etcher didn't see the drive. However, my output from `diskutil` was different from the other two; instead of seeing:

```
   Device Location:          External
   Removable Media:          No
```

I see:
```
   Device Location:          External
   Removable Media:          Fixed
```

It sounds to me from [this link](https://superuser.com/a/728861) that the fate of `Removable: Fixed` devices is the same as `Removable: No` - is this correct, or can you work with Fixed devices and just not `Removable: No`?

I got it flashed by using unsafe mode (a godsend, never want to use another flashing program at this point) - just curious about the rest..

Full diskutil output if you want..
```
diskutil list
...
  /dev/disk2 (external, physical):
     #:                       TYPE NAME                    SIZE       IDENTIFIER
     0:     FDisk_partition_scheme                        *31.4 GB    disk2

diskutil info /dev/disk2
   Device Identifier:        disk2
   Device Node:              /dev/disk2
   Whole:                    Yes
   Part of Whole:            disk2
   Device / Media Name:      Extreme

   Volume Name:              Not applicable (no file system)
   Mounted:                  Not applicable (no file system)
   File System:              None

   Content (IOContent):      FDisk_partition_scheme
   OS Can Be Installed:      No
   Media Type:               Generic
   Protocol:                 USB
   SMART Status:             Not Supported

   Disk Size:                31.4 GB (31376707072 Bytes) (exactly 61282631 512-Byte-Units)
   Device Block Size:        512 Bytes

   Read-Only Media:          No
   Read-Only Volume:         Not applicable (no file system)

   Device Location:          External
   Removable Media:          Fixed

   Virtual:                  No
   OS 9 Drivers:             No
   Low Level Format:         Not supported
```

**Comment by jviotti** [comment]
Hi @clounie,

Thanks for the detailed report. You are right about the fixed property. It basically means "removable = No".

We investigated in the past whether we should only rely on the device location being external, but that includes external hard drives as well.

I guess there's not Etcher can do (for safety reasons) if the adaptor reports to the MacBook Pro that the drive is fixed.

Maybe worth investigating if macOS could somehow be tweaked to detect this adaptor as something removable?
