### ISSUE TITLE
Download links cause Google Chrome to alert about deception

### ISSUE THREAD

**Issue by ColdHeat** [resin-io/etcher#1629]
Tried to download Etcher for OSX and received the following alert from Google Chrome. 
![image](https://user-images.githubusercontent.com/166333/28555612-04ed191c-70cf-11e7-92e0-50655f22aaa7.png)

**Comment by jhermsmeier** [comment]
Could you provide the exact version & link of the one that caused this to display?

**Comment by lurch** [comment]
@jhermsmeier @jviotti @craig-mulligan
Yikes! I'm seeing exactly the same error (in Google Chrome Version 59.0.3071.11) for _any_ of the download links near the bottom of https://etcher.io/ :-(  Looks like Chrome is being a bit over-zealous?

**Comment by jhermsmeier** [comment]
I'm also seeing it with Chrome Canary, but not in Chromium. I've reported it as false positive now, sadly not much more we can do about it, I think. And I can't help but wonder who reported GitHub's release assets as phishing...

**Comment by imrehg** [comment]
Checking the domain that triggers the warning: https://www.google.com/transparencyreport/safebrowsing/diagnostic/#url=https://github-production-release-asset-2e65be.s3.amazonaws.com

**Comment by imrehg** [comment]
Should be resolved now.
