### ISSUE TITLE
ETA box-size too small for longer write/verify times...

### ISSUE THREAD

**Issue by Xalior** [resin-io/etcher#1631]
- **Etcher version:** 1.0.0
- **Operating system and architecture:** MacOS
- **Image flashed:** Custom own image of 128Gb in size
- **Do you see any meaningful error information in the DevTools?** Nope.

The ETA box is too small if your image verification/write takes over 59m59s... it counts down to zero and then resumes at 59m59s...

**Comment by lurch** [comment]
I guess this is a bit like #1539 - we could display XXhYYm if the eta is over an hour, and then only switch to YYmZZs when the eta is less than one hour. (since if the ETA is over an hour, you're probably not worried about having the ETA with the granularity of seconds)
