### ISSUE TITLE
Error when updating source list on Debian Stretch

### ISSUE THREAD

**Issue by fabiomoc** [resin-io/etcher#1638]
- **Etcher version: 1.1.0**
- **Operating system and architecture: Debian Stretch**

This is the error I get when a I execute the command **apt update**:

E: Failed to fetch https://dl.bintray.com/resin-io/debian/dists/stable/InRelease  Unable to find expected entry 'etcher/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)
E: Some index files failed to download. They have been ignored, or old ones used instead.

The source list is in this path: /etc/apt/sources.list.d/etcher.list
And it's content is: **deb https://dl.bintray.com/resin-io/debian stable etcher**

**Comment by Fred-Barclay** [comment]
Duplicate of #1634 😄

**Comment by lurch** [comment]
Closing as duplicate

**Comment by fabiomoc** [comment]
Sorry. Thanks anyway, guys.

**Comment by sherminator666** [comment]
Failed to fetch https://dl.bintray.com/resin-io/debian/dists/stable/InRelease 
pls solve the issue

**Comment by jhermsmeier** [comment]
@sherminator666 see https://github.com/resin-io/etcher/issues/1634 – it's supposed to be https://dl.bintray.com/resin-io/debian/dists/stable/Release
