### ISSUE TITLE
EHOSTDOWN error on startup when no internet connection

### ISSUE THREAD

**Issue by steffenmllr** [resin-io/etcher#1645]
- **Etcher version:**: 1.1.1
- **Operating system and architecture:** osx

Would be nice if the error was silent if there is no internet connection

![image](https://user-images.githubusercontent.com/449563/28744418-d4a39f52-7460-11e7-8adc-31394df96269.png)

**Comment by jviotti** [comment]
Very interesting, thanks a lot for reporting, I'll handle it.
