### ISSUE TITLE
Couldn't initialize the scanner

### ISSUE THREAD

**Issue by stevie86** [resin-io/etcher#1646]
- **Etcher version:** 1.1.1
- **Operating system and architecture:** Windows 10 x64
- **Image flashed:** none, not working
- **Do you see any meaningful error information in the DevTools?**
How do I do that on Windows
![2017-07-30 18_58_02-etcher](https://user-images.githubusercontent.com/5559975/28755376-e237860c-7559-11e7-98f9-cdf65412d1bc.png)

**Comment by jviotti** [comment]
Related to https://github.com/resin-io-modules/drivelist/issues/198. Do you have a virtual drive mounted? Can you confirm that unmounting the virtual drive makes it work?

**Comment by lurch** [comment]
See also #1639

**Comment by MetalRush** [comment]
@ jviotti; I can confirm that (in my case) my Alcohol 120% virtual drive was the culprit.
I disabled the drive and reinstalled Etcher.
(now I have to find out why my image seems corrupt when validating)

**Comment by jviotti** [comment]
Can you try the following snapshot build that contains the fix: https://drive.google.com/file/d/0B7tkbonGU-RyTUNKaVpLb2VCZ1E/view?usp=sharing? If that still doesn't work, can you set the `DRIVELIST_DEBUG` environment variable and execute the application from `cmd.exe`, so you can see the debug logs?

For example:

```
set DRIVELIST_DEBUG=1
cd C:\Program Files\Etcher
etcher.exe
```

**Comment by mikaeljonssonhbg** [comment]
Hi,

Had the same issue and snapshot build from jviotti with fix above solved it for me! Thankxxx!

**Comment by stevie86** [comment]
Hi! Somehow it works for me now, I don't know why! Thanks!

**Comment by lurch** [comment]
@stevie86 Maybe you upgraded from Etcher 1.1.1 to Etcher 1.1.2  :-)

**Comment by jviotti** [comment]
@stevie86 Did you have a virtual volume or some other kind of "special" volume that you unmounted?
