### ISSUE TITLE
Feature request - persistent password

### ISSUE THREAD

**Issue by linuxlite** [resin-io/etcher#1658]
- **Etcher version:** 1.1.1
- **Operating system and architecture:** Linux Lite 3.4 64bit (Ubuntu 16.04.2 base)
- **Image flashed:** multiple images flashed
- **Do you see any meaningful error information in the DevTools?** n/a

When flashing multiple USB drives, each flash requires your user password, despite the program already being open. This makes flashing multiple USB drives a tedious exercise. Please consider a persistent password. If you're using polkit for this, consider using:

```
      <allow_any>auth_admin</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>auth_admin_keep</allow_active>
```

Thank you.

**Comment by jviotti** [comment]
Hi @linuxlite ,

We do use Polkit, however the relevant permissions are system specific, so Etcher just uses what it finds in the system by default. I haven't done it myself, but you should be able to customize your system's Polkit to accomplish this.

**Comment by lurch** [comment]
...alternatively, you can just run the whole Etcher application as `root` (e.g. by using `sudo`) and then it won't need to ask you for a password.

This issue was previously discussed in #851 and #846
