### ISSUE TITLE
etcher.io website lists all downloads as linux

### ISSUE THREAD

**Issue by sarukuku** [resin-io/etcher#1678]
I know this is not the place for this issue but I couldn't find a Twitter handle for etcher.io so I decided to drop this here. Just close this issue immediately, this is just a heads up.

![screen shot 2017-08-08 at 13 16 36](https://user-images.githubusercontent.com/1204559/29067627-18faa690-7c3c-11e7-9edf-281349e957b2.png)

![screen shot 2017-08-08 at 13 16 51](https://user-images.githubusercontent.com/1204559/29067579-e38e58d0-7c3b-11e7-85f0-5a0d75091136.png)

**Comment by lurch** [comment]
Haha, whoops! Pinging @craig-mulligan

BTW the 'correct' place for this issue would be https://github.com/resin-io/etcher-homepage/issues

**Comment by craig-mulligan** [comment]
Taking a look @lurch, it's probably because we changed the releases format.

**Comment by lurch** [comment]
@craig-mulligan I'm assuming https://github.com/resin-io/etcher-homepage/pull/92 fixes this?

**Comment by craig-mulligan** [comment]
Yip, @lurch.
