### ISSUE TITLE
Etcher does not work on Bodhi Linux 4.2

### ISSUE THREAD

**Issue by michmanbiker** [resin-io/etcher#1681]
- *1.1.2**
- **Bodhi Linux 4.2 64 Bit:**
- **Image flashed:**
- **Do you see any meaningful error information in the DevTools?**
Etcher asks me for my Sudo password and then does nothing.

**Comment by michmanbiker** [comment]
Etcher asks me for my Sudo password and then does nothing.

**Comment by lurch** [comment]
I'll take a look at this later, to see if I can reproduce.

**Comment by michmanbiker** [comment]
something to do with syslinux 6.03?

**Comment by jviotti** [comment]
@lurch Did you make any progress on this ticket?

**Comment by lurch** [comment]
Sorry, I forgot. I'll try to take a look soon.

**Comment by lurch** [comment]
I've now tested this in a VirtualBox VM using the Bodhi 4.2 LiveCD. I used the 64-bit Etcher v1.2.0 AppImage to flash a virtual USB disk, and it all went fine, I didn't encounter any problems at all.

So apologies for the very slow response @michmanbiker but I'll mark this as closed. If you're still having problems, then try installing the 64-bit .deb file (it seems like Bodhi is an Ubuntu spin-off), and if you still can't get it working then please feel free to add extra comments here and I'll re-open.
