### ISSUE TITLE
Etcher causes: "Warning: The driver descriptor says the physical block size is 2048 bytes, but Linux says it is 512 bytes"

### ISSUE THREAD

**Issue by Enigma0** [resin-io/etcher#1698]
- Latest .deb
- Ubuntu GNOME 17.04
- Ubuntu GNOME 17.04

It flashes successfully but GParted is unable to properly read it as in the title. It causes this issue: https://askubuntu.com/questions/914983/physical-block-size-is-2048-bytes-linux-says-it-is-512-bytes

Warning: The driver descriptor says the physical block size is 2048 bytes, but Linux says it is 512 bytes.

**Comment by lurch** [comment]
This is nothing to do with Etcher, but is a side-effect of the particular image you're flashing, see https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#flashing-ubuntu-isos
