### ISSUE TITLE
support windows iso on linux

### ISSUE THREAD

**Issue by Rezhwan-IT** [resin-io/etcher#1710]
Etcher tool is very cool for make bootable usb iso but i see just support linux iso not support windows 
Pleas make etcher is better support windows iso on linux 
Thanks

**Comment by jviotti** [comment]
Duplicate of https://github.com/resin-io/etcher/issues/210. 

Etcher currently supports any image that is bootable out of the box. Windows images need special treatment to be made bootable, that we might implement at some point.
