### ISSUE TITLE
etcher spies on the user without consent, and transmits the spying results unencrypted

### ISSUE THREAD

**Issue by sneak** [resin-io/etcher#1718]
- **Etcher version:**

1.1.2

- **Operating system and architecture:**

osx 10.12.6 amd64

![screen shot 2017-08-30 at 00 19 50](https://user-images.githubusercontent.com/408977/29855359-3dda978e-8d19-11e7-845f-5fa25e8581f6.png)

I did not consent or opt in to such tracking.  To add insult to injury, you are transmitting the results of such unethical tracking unencrypted, violating every best practice about the safe handling of user data there is.

**Comment by jviotti** [comment]
Hey there @sneak ,

These logged events are for error tracking purposes. They are anonymous and you can disable them through the settings page.

Regarding HTTP, I was not aware that the Mixpanel client was doing so. Do you have any clues @Shou ?

**Comment by jhermsmeier** [comment]
I was just looking into it, and the Mixpanel client uses HTTP by default, which we don't override in corvus. Mending that at the moment.
