### ISSUE TITLE
Etcher doesn't detect named USBs

### ISSUE THREAD

**Issue by ajmeese7** [resin-io/etcher#1719]
- **Etcher version: 1.1.2**
- **Operating system and architecture: Windows 10 64-bit**

I noticed Etcher won't detect any named USB. By named I mean the user went into the USB's properties and changed the name. I have tried with multiple USBs and it doesn't detect any of them.

**Comment by lurch** [comment]
I'm not sure what you mean. Could you add some screenshots to show examples?
Does Etcher detect "the USB" (whatever you mean by that) before you rename it?

**Comment by ajmeese7** [comment]
I'm not sure how the term USB is ambiguous but here is a screenshot of Etcher only detecting the unnamed flash drive.

![etcher](https://user-images.githubusercontent.com/17814535/30038328-e37e5e64-9188-11e7-82ed-cfb80e021ca0.png)

**Comment by lurch** [comment]
Thanks, that screenshot clarifies that you're actually talking about USB flash drives. (I wasn't sure if you might have been talking about USB ports, USB interface cards, USB drivers, etc.)
I'll try to reproduce and investigate tomorrow.

**Comment by lurch** [comment]
@ajmeese7 Do things now work properly in Etcher 1.3.1 ?

**Comment by jhermsmeier** [comment]
These names you're referring to are volume labels, and are part of the file system(s) stored in the partitions on the device, or in the partition table (for GUID Partition Tables and Apple Partition Maps), not a name of the device itself – we do list devices with their volume mountpoints (i.e. F: on Windows), but don't read the partition or volume labels at the moment.

**Comment by ajmeese7** [comment]
I just checked in 1.4.4 and it properly reads the USB drives now
