### ISSUE TITLE
Invalid partition table - recursive partition on /dev/sdb

### ISSUE THREAD

**Issue by JustAnotherJack** [resin-io/etcher#1722]
- **Etcher version: 1.12.
- : Ubuntu 16.04.1 LTS.  Mate.  
-  Linux Mint 18.2. 
8Gb Usb.  Operational.. Previously had another Distro. Used Gparted and Formatted to Fat 32
Etcher says  indicates sucessful Install.
USB does not show up in file manager.  Gparted results in: WARNING:   Invalid partition table - recursive partition on /dev/sdb.
Thank you in advance.

**Comment by jhermsmeier** [comment]
Hey @JustAnotherJack – which image exactly were you flashing, and which format is it in (img, iso)?

**Comment by JustAnotherJack** [comment]
Hi,  and thank you.

linuxmint-18.2-cinnamon-32bit  iso.

**Comment by lurch** [comment]
I haven't checked yet, but it wouldn't surprise me if this is just another instance of https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#flashing-ubuntu-isos

@JustAnotherJack Ignoring the errors from the file manager and GParted, does your USB drive actually boot?

**Comment by JustAnotherJack** [comment]
No. Does not.
I made one using the command line, and it boots fine.
Thanks

**Comment by jhermsmeier** [comment]
@JustAnotherJack what did you run on the command line?

**Comment by JustAnotherJack** [comment]
I don't remember the exact string, but it was the "dd" command that worked.

**Comment by lurch** [comment]
Both `dd` and `Etcher` do exactly the same thing - copy the disk image exactly byte-for-byte onto your destination drive. So I've got absolutely no idea why you'd be seeing different behaviour from the two tools :-/

**Comment by JustAnotherJack** [comment]
I'll try again with the same distro (Manjaro), and another.
Thanks

**Comment by lurch** [comment]
Hi @JustAnotherJack , did you manage to make any progress?

**Comment by JustAnotherJack** [comment]
Yes. As I said, when I used the command line it worked.  I can do other
distros using etcher, but not Manjaro.

**Comment by lurch** [comment]
@JustAnotherJack Can you please confirm which distros (and which versions of those distros) are and aren't working? Earlier on you were talking about Linux Mint, and now you're talking about Manjaro...?

**Comment by JustAnotherJack** [comment]
My apologies.  The Manjaro comment was meant for another forum.
