### ISSUE TITLE
tried using this on windows to make a usb iso from ubuntu 17 but 

### ISSUE THREAD

**Issue by foxjazz** [resin-io/etcher#1727]
results in not reading disk.
latest version of etcher was used running windows 10
it says it's done 

used disk part to fix the usb drives.

**Comment by jhermsmeier** [comment]
Do you mean that Windows cannot read the disk? Or that yor computer can't boot from it?

**Comment by lurch** [comment]
Unless the USB disk is actually unbootable, I suspect this is just the standard 'problem' of Windows not being able to read Linux-format partitions. Either that, or https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#flashing-ubuntu-isos

@jhermsmeier The problem of Windows not displaying Linux-disks has come up a number of times before - maybe worth adding something about this to the documentation?
