### ISSUE TITLE
Feature suggestion: skip validation

### ISSUE THREAD

**Issue by saviosg** [resin-io/etcher#1731]
I used etcher only once, for flashing a linux iso into a usb drive, it took about 20 minutes to flash the image, and 20 more to verify it.
40 minutes may not be a lot of time, but I believe some people would want to risk and skip the validation process, for a lot of reasons [e.g. not having enough time or no patience...], skipping generally would not be the safest option, but for some people in several cases it would be worth the risk.

**Comment by saviosg** [comment]
#250 
Already exists

**Comment by Galachejp** [comment]
thanks
