### ISSUE TITLE
Gparted launch after Etcher flash finished. GPT / msdos table problem and gparted view no data in usb

### ISSUE THREAD

**Issue by tmiele** [resin-io/etcher#1738]
- **Etcher version: 1.1.2 AppImage**
- **Operating system and architecture: Ubuntu 14.04.5 LTS (trusty)**
- **Image flashed: ubuntu-16.04.3-desktop-amd64.iso**
- **Do you see any meaningful error information in the DevTools?**

```bash
Error mounting /dev/sdd1 at /media/miele_t/Ubuntu 16.04.3 LTS amd64: Command-line `mount -t "vfat" -o "uhelper=udisks2,nodev,nosuid,uid=1000,gid=1000,shortname=mixed,dmask=0077,utf8=1,showexec,flush" "/dev/sdd1" "/media/miele_t/Ubuntu 16.04.3 LTS amd64"' exited with non-zero exit status 32: mount: wrong fs type, bad option, bad superblock on /dev/sdd1,
       missing codepage or helper program, or other error
       In some cases useful info is found in syslog - try
       dmesg | tail  or so

.
```

**Comment by jviotti** [comment]
This is likely related to Ubuntu's hybrid ISOs. Check https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#flashing-ubuntu-isos for more details.
