### ISSUE TITLE
Add .bin to supported image extension name

### ISSUE THREAD

**Issue by kraml** [resin-io/etcher#1739]
- **Etcher version:**
1.1.2

- **Operating system and architecture:**
Windows 10 x64

- **Image flashed:**
- **Do you see any meaningful error information in the DevTools?**

Could you add .bin as the supported image file extension name? Many of the images I flash use it, and I need to change it manually every time.

**Comment by lurch** [comment]
See #1360 

Just out of curiosity, could you link us to some examples of images that use the `.bin` extension?

**Comment by kraml** [comment]
I work on Chromium OS and the images generated by the build script are in the ```.bin``` extension.

**Comment by kraml** [comment]
Thank you!
