### ISSUE TITLE
OSx .dmg Error: Invalid image

### ISSUE THREAD

**Issue by stdex** [resin-io/etcher#1741]
- **Etcher version:**
1.1.2
- **Operating system and architecture:**
Ubutnu 16.04 x64
- **Image flashed:**
OS X El Capitan 10.11.6 
- **Do you see any meaningful error information in the DevTools?**
No

Try to select image InstallESD.dmg from OS X El Capitan 10.11.6
Get error: Error: Invalid image

![image](https://user-images.githubusercontent.com/4608879/30782197-cf49b17a-a135-11e7-9b0d-49233707e838.png)

**Comment by jviotti** [comment]
Can you link us to that image? I don't know for sure, but I have the impression that is an installer for macOS but not an actual image you have to flash directly.

**Comment by jhermsmeier** [comment]
@jviotti the installESD.dmg is the Mac OS installer image, that's all good – see https://github.com/resin-io/etcher/issues/1572 for example.

**Comment by jhermsmeier** [comment]
Turns out that image is corrupted:
```
Error: Invalid footer signature: Expected 0x6b6f6c79, saw 0x9d72b920
```

And Mac OS seems to agree:
![screen shot 2017-09-24 at 22 41 31](https://user-images.githubusercontent.com/244907/30786117-a4e624c4-a179-11e7-9524-20636d4213b5.png)

**Comment by lurch** [comment]
@jhermsmeier If this is `resolution: wontfix`, should it be closed?
