### ISSUE TITLE
Wrong file size of image (1MB = 1024 * 1024 bytes, not 1000 * 1000)

### ISSUE THREAD

**Issue by gregoiregentil** [resin-io/etcher#1746]
Etcher version:1.1.2
Operating system and architecture: Linux Ubuntu 16.04 64 bit
Image flashed: file.img

the file.img is of size 266340352 bytes. It's reported as 266MB which is wrong as the file is 255MB. 1MB = 1024 * 1024 bytes, not 1000 * 1000.

**Comment by daniel-abbey** [comment]
1MB = 1000 * 1000 bytes
1[M**i**B](https://en.wikipedia.org/wiki/Mebibyte) = 1024 * 1024 bytes

**Comment by gregoiregentil** [comment]
Fair enough!
