### ISSUE TITLE
Reboot Option

### ISSUE THREAD

**Issue by keeganmilsten** [resin-io/etcher#1747]
Hi there!
This is more of a question than a problem, but would it be possible to have a "Reboot" option after flashing the image? This seems like a really useful feature to have for newbies...

Thank you!

**Comment by lurch** [comment]
I don't think this makes sense - while in your use-case I'm guessing you're flashing a PC-distro onto a USB stick (which you'll then be booting from), in other cases people use Etcher to write a RaspberryPi-distro onto an SD card, and they obviously wouldn't want to reboot their PC in that case!

I think if we added a reboot option to Etcher, some people would click it accidentally, and then get angry at us when their PC reboots "unexpectedly". Much safer to just reboot (if needed) using your PC's Operating System as you normally would.
