### ISSUE TITLE
“physical block size is 2048 bytes, but Linux says it is 512” error after using etcher

### ISSUE THREAD

**Issue by opensas** [resin-io/etcher#1751]
- **Etcher version:** 1.1.2
- **Operating system and architecture:** Ubuntu 16.04 (Linux inspiron 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)
- **Image flashed:** ubuntu-budgie-17.10-beta2-desktop-amd64.iso
- **Do you see any meaningful error information in the DevTools?**: No

After creating a bootable iso with Etcher, if I want to format the usb using gparted, I get the following warning: “physical block size is 2048 bytes, but Linux says it is 512”, and cannot delete the partitions.

To recover the usb driver I had to follow the steps described here: https://askubuntu.com/a/781236/26067

**Comment by lurch** [comment]
This isn't an Etcher problem - see https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#flashing-ubuntu-isos and https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#recovering-broken-drives
