### ISSUE TITLE
Add documentation about what kind of analytics we collect for debugging purposes

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1774]
From https://github.com/resin-io/etcher/issues/1770

**Comment by TheAssassin** [comment]
I'd appreciate if this was shipped in-app as well, or a link to an online version would be included. Ideally next to the opt-out checkbox. Also, please link to the privacy policies of the services you use (I assume Mixpanel, and maybe a self-hosted Sentry.io instance).
