### ISSUE TITLE
Couldn't scan the drives: An unknown error occurred

### ISSUE THREAD

**Issue by liwanglin12** [resin-io/etcher#1782]
- **Etcher version:**
v1.1.2

- **Operating system and architecture:**
Windows 10

- **Image flashed:** 
Any

Error on start

[Window Title]
Error

[Main Instruction]
Couldn't scan the drives: An unknown error occurred

[Content]
Error: Couldn't scan the drives: An unknown error occurred

**Comment by jhermsmeier** [comment]
Duplicate of #1646

**Comment by liwanglin12** [comment]
After unlocking a Bitlocker locked disk, the problem is lifted.

Hope to improve error handle! lol
