### ISSUE TITLE
MacOS's hfs images support

### ISSUE THREAD

**Issue by Corsten56** [resin-io/etcher#1785]
- Etcher version: 1.1.2 x64 portable
- Operating system and architecture: Windows 8.1 x64
- Image flashed: OSX_10.13_Installer.hfs

Hello.

It is possible for Etcher to able writing HFS macOS install images?
Images downloads: deleted

or torrent magnet link:
magnet:?xt=urn:btih:31E12B5A4C94BEB607CDC42FE166F427BB160CC0

Best regards.

**Comment by jhermsmeier** [comment]
@Corsten56 just a heads up here – you are aware that sharing proprietary OS images / installers in public can get you in trouble?

I'm not sure I understand what you're asking here: If Etcher already has support for this format, or if you want to suggest support for that format?

Apart from that I'm only aware of the installESD.dmg setups (see https://github.com/resin-io/etcher/issues/1572#issuecomment-313395648 for details) – which can be flashed with Etcher.

**Comment by Corsten56** [comment]
Oh, sorry. Removed links. Don't think that install images restricted.

When I try to flash HFS image, Ethcher says "is not supported image type".

**Comment by jhermsmeier** [comment]
If you want to try; You should be able to rename them to `filename.hfs.img` and then flash them, but as I assume that the HFS images are just file system snapshots, it'll likely not do what you want, as they're probably lacking a partition table and hence will probably not be bootable.

There are no plans to support arbitrary file system snapshots and partitioning in Etcher at the moment, so I'm going to close this for now.
