### ISSUE TITLE
STOP Button would be very useful!

### ISSUE THREAD

**Issue by rsmatias** [resin-io/etcher#1791]
It would be great to have a STOP button in the WRITE operation!

Thanks.
RSM

- **Etcher version:**
- **Operating system and architecture:**
- **Image flashed:**
- **Do you see any meaningful error information in the DevTools?**

**Comment by jhermsmeier** [comment]
That's already planned, and will be possible once #1671 has landed

**Comment by rsmatias** [comment]
Nice! Thanks a lot for your quick reply.

Regards,
RSM

**Comment by lurch** [comment]
This request was originally to be able to stop the "write" operation, but we've also had a request from @Gallore to be able to cancel the "verify" operation.
