### ISSUE TITLE
Don't open another Etcher instance when opening it again

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io/etcher#1809]
When you click on Etcher and the program is running, it opens a new instance of Etcher. Instead it should activate / focus the currently running Etcher instance.

**Comment by jviotti** [comment]
I don't think this is the case of macOS, but keep in mind that we know of some users opening multiple instances as a way to do multi-writes, so we might want to delay this until proper multi-writes are implemented.

**Comment by aw5m2nite** [comment]
It's with Windows 10.  When clicking on Etcher in the taskbar (already opened), it doesn't switch windows to Etcher, but insteaad opens a new instance of Etcher.

**Comment by lurch** [comment]
I wonder if this an Electron / Windows 10 issue, rather than specifically an Etcher issue? \*shrug\*

@aw5m2nite Is this with the 64-bit Windows installer version of Etcher 1.1.2 ?

**Comment by Fireflaker** [comment]
Same issue. It had worked. Not anymore. Uninstalled and re-installed. @Win10x64
