### ISSUE TITLE
Replace Lodash templates

### ISSUE THREAD

**Issue by Shou** [resin-io/etcher#1810]
Instead we could simply use lambdas and native template literals, e.g.

```js
const tplt = _.template('I am a <%= adjective %> template.')
tplt({ adjective: 'small' })

const tplt = ({ adjective }) => `I am a ${adjective} template.`
tplt({ adjective: 'small' })
```

**Comment by lurch** [comment]
Would this change have any knock-on effects if/when we decide to localize Etcher? ( #308 )

**Comment by Shou** [comment]
Can't see how, I don't believe `_.template` has any functionality that localization could leverage.

**Comment by lurch** [comment]
Fair enough :)  I just wondered if searching for `_.template` might be a useful way to find strings that ought to be localised, but thinking about it a bit more I guess there'll also be plenty of strings that we need to localise that _aren't_ templated.

**Comment by jhermsmeier** [comment]
In terms of localization, string template could be easily fitted with it by sticking a template function in front of it (see [tagged template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_template_literals)), far easier than mending lodash templates.

**Comment by urohit011** [comment]
I would like to work on this.
