### ISSUE TITLE
macOS Sierra Verification Fails For ANY image

### ISSUE THREAD

**Issue by niftylettuce** [resin-io/etcher#1812]
Every image I've tried fails.  This is on a brand new SDCARD.

![screen shot 2017-10-26 at 9 50 46 pm](https://user-images.githubusercontent.com/523141/32084547-cd4c21c0-ba97-11e7-8cde-6cb35f4069b9.png)

Tested Ubuntu Raspberry Pi 3 image as well as Ubuntu Mate Raspberry Pi 3 image.

https://wiki.ubuntu.com/ARM/RaspberryPi
https://ubuntu-mate.org/raspberry-pi/

**Comment by niftylettuce** [comment]
Using SanDISK Class 10 32, 64, 128, 256 GB cards all failed with same error

**Comment by lurch** [comment]
What SD card reader are you using? Where did you buy your SD cards from? Is it possible you've bought a bulk-set of 'fake' SD cards?

**Comment by niftylettuce** [comment]
I believe this is an error because Mac cannot read ext4 and other formats.
The PI_ROOT partition doesn't show, only PI_BOOT.  I don't think Mac can
fix a SD card without using something like Gparted boot disk.

**Comment by lurch** [comment]
> I believe this is an error because Mac cannot read ext4 and other formats.

That's not a problem for Etcher - it just reads and writes low-level bytes, so it doesn't matter what file-system they happen to be. (Etcher's verification process works just fine on Windows, which also can't read ext4 filesystems)

>  I don't think Mac can fix a SD card without using something like Gparted boot disk.

If you want to be able to 'repair' your SD cards so that they're usable with other programs, see https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#os-x

If you could please answer my earlier questions, we might be able to help you narrow down where the problem is :)

**Comment by niftylettuce** [comment]
I bought from reputable SanDisk reseller, brand new unsealed packaging.  I am using built-in Macbook SD card reader.  Also, I went ahead and tested this on Ubuntu and had zero issues, verification passed as well.

**Comment by lurch** [comment]
@jhermsmeier Do you think we should re-open this, or is this likely to be one of those rare one-off issues that we can't really do anything about?

**Comment by hoangphan** [comment]
it seems i faced the same problem with Mac sierra (10.13.3) and any etcher version.
i got exactly the same result whenever trying to flash a raspbian to my SD card.

if anyone have success on overcoming this issue please share some information. Thanks!

**Comment by jhermsmeier** [comment]
As @lurch already touched on, more often than not persistent verification failure leads back to the hardware (i.e. the sd-card reader, or the cards themselves) - is your mac connected to power while flashing?Are you using an external sd-card reader? And is it only Raspbian specifically, or does this happen with other images as well?

**Comment by hoangphan** [comment]
i have mac connected to power while flashing, and also the case without power.
yes, i have both types of adapter for SD card of my micro SD 16GB, and the USB adapter type. both not work as the same result.

anyway, i had overcome this by an alternative: using another Windows PC and etcher can complete the validation after flashing.

an interesting point is, after the above mentioned error by @niftylettuce, the card seems not able to be mounted/ unmounted by Mac anymore, after many try, i ended up with using my CANON G16 camera to format it, and surprisingly, a camera can format the card when none of my PC (both windows and mac) can do, such a shame to apple and microsoft.

**Comment by lurch** [comment]
Is it possible that this is the same issue I described [here](https://github.com/resin-io/etcher/issues/2085#issuecomment-368819762), i.e. the host OS auto-mounting the partitions on the SD card (after writing, but before verification finishes), which then causes the filesystem meta-data to change, which then causes Etcher's verification process to fail? 

\*shrug\* Or maybe I'm just clutching at straws... ;-)

**Comment by hoangphan** [comment]
I think so :) it seem Apple wants to force every body to start using the MBP with touch pad, without SD card and all type C USB support.

**Comment by raydot** [comment]
I get that error on PC.  On Mac with three different SD cards I get the "Please ensure you have necessary permissions to access this resource..." error.  

/Applications/Etcher.app/Contents/Resources/app.asar/node_modules/raven-js/dist/raven.js:55 {"stack":"Error: EACCES: permission denied, open '/dev/rdisk1'","message":"EACCES: permission denied, open '/dev/rdisk1'","code":"EACCES"}

The disk created on the PC has RASPPI desktop files loaded on to it and boots with the logo but then turns into the black screen of death.  Any thoughts?

**Comment by zen** [comment]
Those symptoms are identical when using write protected card ;)

**Comment by raydot** [comment]
@zen did you maybe miss the part where the card has the desktop files loaded onto it?  ;)

I got Etcher to work with yet a third PC and that card.  Between that and any number of other things I've seen I think it must be a hardware issue.

**Comment by rlueder** [comment]
I think I'm experiencing a similar problem, tried burning a few different ISO to a 32GB Sandisk Cruzer, validation seems to to progress close to 90% done and then the message below appears:

<img width="871" alt="etcher_1 4 4_not_readable" src="https://user-images.githubusercontent.com/341543/41896330-e82ba9be-78e9-11e8-9519-d0f659b8a714.png">

**Comment by lurch** [comment]
@rlueder Duplicate of #1428 ?

**Comment by rlueder** [comment]
Yep, that sounds about right! thanks for the heads up 👍
