### ISSUE TITLE
Unable to detect SD card as a removeable drive

### ISSUE THREAD

**Issue by pslootweg** [resin-io/etcher#1820]
#- **Etcher version:** LATEST
- **Operating system and architecture:** macOS Sierra
- **Image flashed:** You are fucking kidding, right?
- **Do you see any meaningful error information in the DevTools?** Hahahahahahah

**Comment by pslootweg** [comment]
Etcher takes FOREVER to load. Then when I select "select image" it takes an age to open the select dialog and even when I have selected the ISO image, the select drive option takes another century to open.
Then, the SD card is apparently not a removeable drive - so I'm simply blocked at this point from doing anything further.

BTW I ventured into dangerous territory and enabled 'Unsafe mode' - is that what made it recognise my SD card?

Has anyone tested this shit lately? WTF.

**Comment by lurch** [comment]
I'm sorry to hear you've been having problems with Etcher. I can assure you that we do test Etcher, and we have many many users who are perfectly happy with it.

If you'd like to change your tone to that of a more positive one, and give a more detailed description, we may be able to help you diagnose your problems...

**Comment by pslootweg** [comment]
Apologies - I was having a VERY bad day where NOTHING appeared to be
working properly - Mac, network etc.
I just lost my cool.

**Comment by lurch** [comment]
Thanks for the apology, I hope you're having a better day today :-)

Could your problems with Etcher be linked to problems elsewhere? If your other problems have now been resolved, would you mind seeing if Etcher now works properly, or if it's still misbehaving?

And with regards to Unsafe mode - sometimes the OS mis-identifies removable drives as "non-removable" (see e.g. #649 and #1788 ), and in Etcher we label these as "System" drives, to prevent people accidentally overwriting drives that they didn't mean to.

**Comment by pslootweg** [comment]
The next day is always a better day :)

I'll go over it all again. I did eventually get a card written, but really
can't remember how/if the UX might have been affected by wider system
issues.

I did take a clone of the repo, so might investigate, if it continues being
problematic.

Cheers.

**Comment by pslootweg** [comment]
So I start Etcher - it takes quite a long time to appear.
I left it sat there for a while - did not interact with it at all. Then the
attached error pops up and the program no longer responds.
I restart Etcher - this time once it appears I try to point it to an ISO
image - again, response is quite slow, but eventually gets there.
Load the image - let it ponder for a while until it is ready to write the
SD card.

All seems to be OK, except 1) Some half dead process seems to have taken
over my desktop and 2) the SD card didn't work.

I'll try again.

Paul

**Comment by lurch** [comment]
Thanks for the info @pslootweg 

I don't know what you mean by "attached error"? Github doesn't handle email attachments, so assuming you meant a screenshot, you need to login to the Github webinterface and add it there.

Regarding the "half dead process" -  I wonder if you might be experiencing https://github.com/resin-io/etcher/issues/1288 (which we thought we'd fixed in Etcher 1.1.2, but https://github.com/resin-io/etcher/issues/1288#issuecomment-331350986 says is sometimes still happening)

Regarding "the SD card didn't work" - how exactly did it "not work"? Did the Etcher verification-stage fail, or something else?

**Comment by pslootweg** [comment]
<img width="363" alt="screen shot 2017-11-06 at 13 20 29" src="https://user-images.githubusercontent.com/18535779/32456041-1971ed1e-c31c-11e7-9ac9-5844f8195bf8.png">

I was creating an SD card with Raspberry Pi Desktop and it failed to boot.

It might have been the SD card. It was by then early hours so I gave up.

**Comment by pslootweg** [comment]
![screen shot 2017-11-06 at 00 29 42](https://user-images.githubusercontent.com/18535779/32460120-9ddb156e-c329-11e7-89d4-6aed09bd6703.png)

Just now I launched Etcher, and am ignoring it to see if/when the error manifests itself...
Etcher 1.1.2, OS X 10.11.6 (15G1611)
No error after a good while.. However, there was no SD card in the system. So I quit Etcher and launched it again after plugging in the SD card.
Shortly after launching, Etcher detected the SD card - but I just left it sat there. And then it throws that error! And thrashing the CPU. (See attached result of 'top' - just one after another bash shell spawned.

![screen shot 2017-11-06 at 19 55 11](https://user-images.githubusercontent.com/18535779/32461154-dee3f29e-c32c-11e7-91f7-26737185cefb.png)

Managed to kill it by killing the program group.

The SD card had PiDesktop written to but then wouldn't boot.
TBH it was early hours of the morning, so I tried just one more time and when that didn't work I gave up. Not sure what the problem was.

**Comment by pslootweg** [comment]
[https://github.com/resin-io/etcher/issues/1495](url) Indicates the same error.

**Comment by pslootweg** [comment]
So last experiment of the day; No SD card inserted, start Etcher and wait.
No error message after some time - now insert SD Card and wait again.
Eventually Etcher recognises the card - I'm still waiting.
Nothing happens - so I go to select the ISO image (boy, the UI is SLOW!) - and after a bit the 'Flash!' button waits to get pressed. Soon after Etcher throws 'the' error.
![screen shot 2017-11-06 at 20 09 28](https://user-images.githubusercontent.com/18535779/32461648-7423705e-c32e-11e7-9b1e-99e89abdd255.png)

Doesn't seem to like SD cards.

**Comment by lurch** [comment]
Yeah, seems like `drivelist` is having problems on your Mac :-(  I don't have a Mac myself, so either @jhermsmeier or @jviotti will have to take over here with helping you investigate / debug this...

In the meantime, could you try a snapshot build of Etcher, to see if that works any better / differently?
https://resin-nightly-downloads.s3.amazonaws.com/etcher/2017-10-31/1.1.2%2B03b2520/Etcher-1.1.2%2B03b2520.dmg

**Comment by jhermsmeier** [comment]
Many thanks @pslootweg – this is helpful info, I shall have a look. Typically the "fork: Resource temporarily unavailable" error hints at the system running out of file descriptors.

This is most likely an issue with `drivelist`, or Etcher running it too often in succession without waiting for a return. But just to exclude other possibilities, could you tell us what the following three commands report in your terminal?

```
ulimit
sysctl kern.maxproc
sysctl kern.maxprocperuid
```

**Comment by lurch** [comment]
@pslootweg Would you mind re-testing with Etcher 1.3.1 to see if that fixes the problems you were having earlier?

**Comment by pslootweg** [comment]
Hi,

Tried Etcher 1.3.1 and it seems more stable and looks to be working.
However, when I flash the a 16G card with 2017-06-22-rpd-x86-jessie.iso
when I plug it into my Raspberry Pi, it doesn't start up.
Which suggests the image isn't correct.

**Comment by pslootweg** [comment]
I'm trying again with an up-to-date image

**Comment by pslootweg** [comment]
Ah, that explains a lot. Don't know why I used that image file.

Just tried it with 2017-11-29-raspbian-stretch.zip and the RPi booted fine
:)

TBH Etcher is much more stable and handles errors pretty well. Didn't steal
all my CPU either :)

Thanks for asking me to try it out.

Paul

**Comment by jhermsmeier** [comment]
I guess we can close this issue then? :)

**Comment by pslootweg** [comment]
Guess so :)

**Comment by jhermsmeier** [comment]
Sweet!
