### ISSUE TITLE
Document need for rpiboot drivers on Windows

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io/etcher#1827]

**Comment by lurch** [comment]
@jhermsmeier should we push this back to the v1.3.0 milestone?

**Comment by jhermsmeier** [comment]
Hmm yes, probably – It might not hurt to just have it in the docs already though?
Ah well, let us just stick this into v1.3.0.

**Comment by lurch** [comment]
I guess whether we mention it in the docs or not, depends on whether this is a feature we're promoting / supporting yet? ;-)

**Comment by lurch** [comment]
Should this be moved from v1.3.1 to Backlog milestone?
