### ISSUE TITLE
Etcher will not go full screen

### ISSUE THREAD

**Issue by ghost** [resin-io/etcher#1840]
- 1.1.2
- Mac OSX 64 bit
- Raspbian
- No

It will not resize to full screen when you click the + button.

**Comment by jezmck** [comment]
The maximise button in Windows is greyed out, so I guess the interface isn't designed for it.

Any particular reason you want it full screen?

**Comment by JBoyAdvance** [comment]
No, there is not a specific reason. I just was wondering why it did not go full screen. It'd be nice if it did, though.

**Comment by JBoyAdvance** [comment]
No, there is not a specific reason. I just was wondering why it did not go full screen. It'd be nice if it did, though.

**Comment by lurch** [comment]
Correct. The Etcher GUI is currently non-resizable, and therefore can't be maximised. On Linux the maximise button isn't shown either, so perhaps the maximise button getting shown on OSX is a bug in Electron? Or maybe OSX simply doesn't allow the maximise button to be disabled / removed? \*shrug\*
