### ISSUE TITLE
webview success banner height is too small.

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/etcher#1856]
- **Etcher version:**
- **Operating system and architecture:**
- **Image flashed:**
- **Do you see any meaningful error information in the DevTools?**

**Comment by lurch** [comment]
What do you mean by "too small"?

**Comment by craig-mulligan** [comment]
It's height is set to 255px and doesn't take advantage of the height of the default launch window.

**Comment by lurch** [comment]
ping @Shou and @konmouz

**Comment by craig-mulligan** [comment]
We realised there is was a burn again banner that I wasn't seeing because it was rending incorrectly so we actually are using most of the vertical space available - closing.
