### ISSUE TITLE
permission denied error

### ISSUE THREAD

**Issue by varunkrgupta03642** [resin-io/etcher#1871]
Arduino: 1.8.5 (Windows 10), Board: "Arduino/Genuino Uno"

sketch\sketch_nov20a.ino.cpp:1:0: fatal error: can't open C:\Users\hp\AppData\Local\Temp\ccHsjdM0.s for writing: Permission denied

 

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

what to dp now

**Comment by jhermsmeier** [comment]
I think you might have got the wrong repository here?

**Comment by varunkrgupta03642** [comment]
i was trying to compiling my code when i was clicking verify button on my ardunio ide back to back it was compiling but when when i m clicking it and taking halt it was showing this kind of error

**Comment by jhermsmeier** [comment]
Sorry, I'm confused, what does this have to do with Etcher? This is not an Arduino project, nor does it contain any Arduino related code (like the `sketch_nov20a.ino.cpp` that's mentioned in the error message).
