### ISSUE TITLE
Fix OS window keyboard shortcuts

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io/etcher#1883]
Due to `electron.Menu.setApplicationMenu(null)`, native window shortcuts such as hiding or minimising the Window get removed.

**Comment by lurch** [comment]
But Etcher is beautiful! Surely nobody would _ever_ want to hide it?

**Comment by lurch** [comment]
In #1909 @joshlewis also requested:
⌘, - Open preferences (Command-comma)

Do the other platforms we support (Linux and Windows) have a similar keyboard shortcut for the same thing?

**Comment by jhermsmeier** [comment]
> Do the other platforms we support (Linux and Windows) have a similar keyboard shortcut for the same thing?

Not that I'm aware of, but will double-check

**Comment by lurch** [comment]
It occurred to me last night that `Ctrl` + `O` (open) might be a common keyboard shortcut that we could implement, to open the image-selection dialog?

**Comment by lurch** [comment]
(sorry, fat-fingered the wrong button!)

**Comment by jhermsmeier** [comment]
Closed in https://github.com/resin-io/etcher/pull/1888, released in v1.3.0
