### ISSUE TITLE
Missing etcher-CLI examples

### ISSUE THREAD

**Issue by eran101** [resin-io/etcher#1890]
CLI examples should be added to:
https://github.com/resin-io/etcher/blob/master/docs/CLI.md

**Comment by lurch** [comment]
Is this just a generic request for documentation, or is there also some part of the Etcher CLI that you need help with?

**Comment by eranj** [comment]
It's not just for me.
I mean examples like in the following link:
https://www.bountysource.com/issues/45325226-etcher-cli-help-output-is-misleading
How to set the source file and destination drive, with or without verification, unmount or not when flashing finished.

**Comment by lurch** [comment]
Haha, that link you posted there is actually just a copy of #1452 ;-)

We've been focusing most of our efforts on the Etcher GUI so far, as that has **much** greater usage, but we'll try to add some polish (and documentation) to the Etcher CLI at some point soon.
