### ISSUE TITLE
Please also provide unzipped AppImages for download

### ISSUE THREAD

**Issue by probonopd** [resin-io/etcher#1893]
This has been discussed before but has not been satisfactorily resolved. Currently the Etcher AppImages are only provided for download in zipped form, which 
* Cripples functionality of the optional `appimaged` daemon which does automatic desktop integration
* Prevents them from being included in the [AppImageHub](https://appimage.github.io/apps/) central directory of available AppImages, and hence from appearing in app stores and software centers like the __NX Software Center__
* Prevents them from being updated with binary delta updates using AppImageUpdate
Please also provide unzipped AppImages for download

Please also (__additionally__) provide the unzipped AppImages for download on GitHub Releases. Thanks!

NX Software Center:

![](https://cdn-images-1.medium.com/max/800/1*HaIF_ow6qnfQwpAZQEpRPg.gif)

**Comment by lurch** [comment]
See #1842

**Comment by probonopd** [comment]
@lurch 

> See #1842

I am aware of that and hence am suggesting here to provide an unzipped version __additionally__ on GitHub Releases. New users will download from the Etcher homepage anyway.

**Comment by lurch** [comment]
Ah cool - I thought you were suggesting that https://etcher.io should offer both the zipped and unzipped AppImages, which would make things far too confusing for our users!

If all you're asking for is the unzipped AppImages to be provided on https://github.com/resin-io/etcher/releases along with the zipped AppImages, then I _think_ that should be okay.

**Comment by lurch** [comment]
@jhermsmeier Thinking about this, if we do add the unzipped AppImages to GitHub Releases, we should also add them to S3 too.

**Comment by lurch** [comment]
Unzipped AppImages are now included on https://github.com/resin-io/etcher/releases/tag/v1.2.1 :smiley:

**Comment by probonopd** [comment]
Thank you very much @lurch!

**Comment by lurch** [comment]
Thanks due to @jhermsmeier too :-)
