### ISSUE TITLE
OS X: If you go to settings during burn it breaks the progress bar

### ISSUE THREAD

**Issue by lorenzo-stoakes** [resin-io/etcher#190]
If, during the burn, you switch to the settings menu by clicking on the gear in the top right hand corner the progress bar will no longer animate correctly:

<img width="202" alt="screen shot 2016-03-10 at 12 15 52" src="https://cloud.githubusercontent.com/assets/305511/13669255/2b6be668-e6ba-11e5-82f9-dedd06c69a45.png">

This may affect other OSes, I have not tested elsewhere.

**Comment by jviotti** [comment]
This indeed happens in all OS. A fix is coming!
