### ISSUE TITLE
"access denied" right after installation

### ISSUE THREAD

**Issue by dwfunk4475** [resin-io/etcher#1901]
Etcher-Setup-1.2.0-x64.exe
Win  7 Ent.

This error has shown up on installation of Etcher onto my system.
Fresh download of app from website, installed it and this error pops up.
The path displayed in the error is not my system.  I have no idea where that path came from.  I've only installed this package and it errors without even running it.

![install_error](https://user-images.githubusercontent.com/4295202/33573371-3250568c-d8fb-11e7-9bea-545787c310ac.jpg)

**Comment by lurch** [comment]
Are you behind some sort of network proxy? If you click "OK" does Etcher continue to run, or does it close?

**Comment by lurch** [comment]
A similar `EPROTO` error was spotted in #1808

**Comment by dwfunk4475** [comment]
Yes it continues to run and flashes ok.

Why would proxy matter?



-david

**Comment by lurch** [comment]
Etcher checks for updates at startup (using an HTTPS / SSL connection to Amazon S3) and I wondered if you might have a proxy that is blocking or restricting HTTPS, which might explain the openssl error?

If we can figure out a way for us to reproduce the error ourselves, then that makes it much easier for us to fix it (or workaround it) :-)

**Comment by dwfunk4475** [comment]
Interesting.  No proxy, not even on a network.

As another data point that might be helpful, I installed on a laptop:

Etcher-Setup-1.2.0-x64.exe
Win 10

and get this error when I start the program:

[image: Inline image 1]

I can click "OK" and the error dialog goes away and Etcher will image an SD
card.

This laptop is not connected to any network.


-david

**Comment by lurch** [comment]
@dwfunk4475 Your image didn't appear - I don't think GitHub can cope with images in emails, you need to go to the GitHub webinterface itself to add images.

**Comment by dwfunk4475** [comment]
attaching image  . . .
![install_error_1](https://user-images.githubusercontent.com/4295202/33730521-d5521ac2-db45-11e7-994b-66304977f2c2.jpg)

**Comment by lurch** [comment]
Wow, that's a pretty bizarre error message! Is it possible your Etcher download or installation has become corrupted somehow?

**Comment by dwfunk4475** [comment]
That's something I can check. I'll re-download the file from a different
location and try again. I've used the same downloaded file on both machines.

I can clear the dialog boxes on either error and Etcher seems to run just
fine. I have written a couple of SD cards and they have turned out OK.



-david
