### ISSUE TITLE
Checksum for etcher-1.2.0-linux-x86_64.zip wrong

### ISSUE THREAD

**Issue by Morgensohn** [resin-io/etcher#1903]
The checksum published here: https://github.com/resin-io/etcher/releases/download/v1.2.0/SHASUMS256.txt, i.e.

`f12a8f94e0671b16289fe08f4b45cedd5aafbea3af7c41d176a5538bd2dfcb89  etcher-1.2.0-linux-x86_64.zip`

does not correspond to the one I am getting:

`~/Downloads $ sha256sum etcher-1.2.0-linux-x86_64.zip 
ea73df9486abad2a5f225613cb0793b1200a4ad5991cabdb9af3ef52f9652700  etcher-1.2.0-linux-x86_64.zip`

- **Etcher version: 1.2.0
- **Operating system and architecture: etcher-1.2.0-linux-x86_64.zip

**Comment by lurch** [comment]
I've just downloaded the `etcher-1.2.0-linux-x86_64.zip` file and get the matching `f12a8f94e0671b16289fe08f4b45cedd5aafbea3af7c41d176a5538bd2dfcb89` checksum, so it looks like your download has corrupted and you should try downloading it again.
