### ISSUE TITLE
Include electron-builder requirements in documenation

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io/etcher#1904]
Our requirements section is currently missing a mention of electron-builder's dependencies (e.g. `icnsutils` and `graphicsmagic`)

**Comment by lurch** [comment]
...but presumably these `electron-builder` requirements are platform-specific? I suggested a while ago that it would be good to split our requirements documentation into "requirements needed to run the pre-packaged version of Etcher", "requirements needed to run the dev version of Etcher" and "requirements needed to build packages of the dev version of Etcher".
