### ISSUE TITLE
OS X: Make whole window draggable or draggable bit a different shade

### ISSUE THREAD

**Issue by lorenzo-stoakes** [resin-io/etcher#191]
Currently it's not clear which bit of the window you can click on to be able to drag it around, as the whole window is the same shade, the design looks great so if the whole window could be draggable that'd be perfect, however if it's not possible, making the top of the window a different shade accepting a sad but thankfully small design compromise would be really helpful :)

**Comment by jviotti** [comment]
This should be possible with `-webkit-app-region: drag`, according to https://github.com/atom/electron/blob/master/docs/api/frameless-window.md#draggable-region, however it doesn't seem to be working anymore.

I opened an issue on Electron: https://github.com/atom/electron/issues/4741
