### ISSUE TITLE
If single viable target drive no information given

### ISSUE THREAD

**Issue by lorenzo-stoakes** [resin-io/etcher#192]
Currently, if there is only 1 viable drive to burn to, etcher auto-selects it. This is great, but you get no information about the size of the drive like you do when there are multiple available drives:

<img width="139" alt="screen shot 2016-03-10 at 12 13 59" src="https://cloud.githubusercontent.com/assets/305511/13669433/67bdb3de-e6bb-11e5-97a1-230433a85628.png">

It'd be really nice to have the size perhaps in parens here as an extra source of calm that the drive is not in fact the system one :)

__Note:__ This might be applicable to other OSes only confirmed with OS X at time of writing.

**Comment by jviotti** [comment]
Looks reasonable. Its easy to implement, but we need to test in Windows to make sure a string like `\\.\PHYSICALDRIVEN` plus the size doesn't overflow or push things aside.
