### ISSUE TITLE
OS X: Filter out .dmg volumes in disk list

### ISSUE THREAD

**Issue by lorenzo-stoakes** [resin-io/etcher#193]
Currently etcher will list the mounted etcher .dmg as an optional target drive, which is confusing.

 Also, if the user does not have an SD card attached/it is fully ejected, the mounted .dmg will be the only available choice which will get auto-selected adding to the confusion.

Attempts to write the .dmg result in a read-only error.

**Comment by jviotti** [comment]
Great idea. I sent a PR to `drivelist` (https://github.com/resin-io-modules/drivelist/pull/55), the module we use to list the drives to completely omit DMGs.
