### ISSUE TITLE
suggestion could Etcher write disk images of usb devices cf sd etc?

### ISSUE THREAD

**Issue by uigiflip** [resin-io/etcher#1931]
- **Etcher version:**
- **Operating system and architecture:**
- **Image flashed:**
- **Do you see any meaningful error information in the DevTools?**

**Comment by lurch** [comment]
I'm not entirely sure what you're asking for, but is this a duplicate of #266 ?

**Comment by uigiflip** [comment]
Yes rephrased. I mean could etcher make backup s of flash, usb or sd cards.
