### ISSUE TITLE
HDD being accessed while idle

### ISSUE THREAD

**Issue by silviucc** [resin-io/etcher#1940]
- **Etcher version:** 1.2.0 (installer) ; 1.2.1 (installer and portable)
- **Operating system and architecture:** Windows 10 Home 64bit, version 1709, build 16299.125
- **Image flashed:** any, does not matter. Happens with image selected or not.
- **Do you see any meaningful error information in the DevTools?** Nothing interesting in the Console. 

The HDD accessed is not my system drive but one of the others. Can't figure which one though. But it's basically like a pulse. Happens every second. Stops while I'm writing an image to a USB drive. Starts right back after job's finished.

**Comment by jhermsmeier** [comment]
That's due to Etcher scanning for drives, and Windows pinging the drives to get their info (size etc.); there's no read, write, or other stuff happening.
