### ISSUE TITLE
Error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io/etcher#1955]
- **Etcher version:** 1.3.0
- **Operating system and architecture:** Linux
- **Error information:** https://sentry.io/resinio-57/etcher-v130/issues/429230586/

**Comment by bdfoster** [comment]
Reproduced on Ubuntu 16.04.2

**Comment by potatowave** [comment]
Reproduced on Ubuntu 16.04.3

Seems to happen at 73% copying a 1.16GB ISO onto a 16GB USB stick.

**Comment by nicklassundin** [comment]
It seems to happen randomly within spectrum of 30 - 70% into the process
4.9 GB .img to 16 GB Micro-SDHC
Ubuntu 16.04 64-bit

**Comment by Cyb3rpunk-76** [comment]
Reproduced on Mint 18.2 Sonya, always on 65%, 32 Gb Micro-SDHC.

**Comment by Timodz** [comment]
Reproduced on Mint 18.2 Sonya

**Comment by krisYanachkov** [comment]
Etcher version: 1.3.0
Operating System: Mint 18.1 64-bit
SDHC: 8GB

**Comment by SLiX69** [comment]
Get this too on 17.10 with Etcher 1.3

**Comment by JGuillaumin** [comment]
Same error while flashing Raspian on a SD card, from Ubuntu 16.04
Finally I used `dd` command.

**Comment by Lewiscowles1986** [comment]
Ooh

![dodgy sandisk](https://user-images.githubusercontent.com/2605791/35100153-995a54c0-fc52-11e7-931a-f59e6713e47b.png)

Looks like this is still the case in xenial repos. I get it, there are 4 other issues pending fix

![image](https://user-images.githubusercontent.com/2605791/35100177-b0531d06-fc52-11e7-8085-efb065b7fea4.png)
![image](https://user-images.githubusercontent.com/2605791/35100200-cf8e3c50-fc52-11e7-87af-540c6c33decb.png)

**Comment by lurch** [comment]
We updated the bintray repos so that 1.2.1 is the latest version https://bintray.com/resin-io/debian/etcher
but I guess apt / dpkg must not downgrade packages if a newer version of the package is already installed :-/

We're hoping to release Etcher 1.3.1 soon, but as a temporary workaround you can do:
```
sudo apt-get remove etcher-electron
sudo apt-get update
sudo apt-get install etcher-electron
```
to manually downgrade to 1.2.1

**Comment by manuti** [comment]
I know the issue is closed and I don't want to complaint your software but I think this bug corrupt two of my MicroSD. The way it was broken doesn't allow me to use again. The MicroSD appears to be locked.

**Comment by lurch** [comment]
@manuti Does https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#recovering-broken-drives help? If not, could you provide more details about what "appears to be locked" means please?  :)
(and BTW Etcher v1.3.1 has now been released, so please try upgrading to that :grinning: )

**Comment by manuti** [comment]
I've been using Etcher for a long time, for sure before the 1.0 release. A couple of weeks ago I start preparing an *armbian* image on a Samsung MicroSD card and I end with a mess of nested partitions and unrecoverable state. I bougth a new Lexar MicroSD after one try I end with errors and I can't format or change the partitions.
I try your recipes about recovering broken drives:

* On Windows: I can perform all the steps, but the MicroSD is not changed
* On Mac: I can't and the ends with `Error: -69877: Couldn't open device`
* On Linux: ...

**Comment by lurch** [comment]
> I end with a mess of nested partitions and unrecoverable state.

That sounds like https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#flashing-ubuntu-isos ? If you provide a link to the particular image you're using, we'll try investigating this ourselves.

**Comment by manuti** [comment]
The images are the community armbian version for Amlogic 9XX, you can find in this link: https://forum.armbian.com/topic/2419-armbian-for-amlogic-s905-and-s905x/
I share also some images related to the issue. Thanks for you patience.
![1](https://raspberryparatorpes.net/wp-content/uploads/2018/01/etcher-1.png?resize=768%2C698&ssl=1)
![2](https://raspberryparatorpes.net/wp-content/uploads/2018/01/etcher-02.png?resize=768%2C698&ssl=1)
![3](https://raspberryparatorpes.net/wp-content/uploads/2018/01/error-mounting-etcher-02.png?fit=960%2C960&ssl=1)

**Comment by lurch** [comment]
Oh, is this bit what you meant by "a mess of nested partitions" ?
![image](https://user-images.githubusercontent.com/476186/35441452-74d5be42-029b-11e8-9fd6-353794cba190.png)

That's perfectly normal, and is a "feature" of MBR partitioning schemes. Basically an MBR can only store 4 primary partition definitions, so to get around that limitation you can create one of the primary partitions as an extended partition (in this case partition 2), and then create multiple logical partitions (in this case partitions 5 and 6) inside that extended partition. See these links for more of the gory details: https://en.wikipedia.org/wiki/Master_boot_record  https://en.wikipedia.org/wiki/Extended_boot_record
Under Linux the primary partitions are always labelled 1 to 4, and the extended partitions are always labelled starting at 5 (regardless of how many primary partitions there are).

Looking at the forum thread you linked to in #1960 , it seems like you're also having problems with other disk-flashing tools, and the problem you're having (whatever its underlying cause) isn't just limited to Etcher?

**Comment by manuti** [comment]
Thanks for the info about partition.
About my comment in the other forum, I only use Etcher for write images to use with my boards. After having problems with Etcher I decide to try a different approach, but I think the damage is done. My microSD cards are broken and I started having problems with all the other image writer software. In the end I decided to manual partition the microSD, mount the images and copy the BOOT and ROOTFS. In this way the card works and I can my board.
Today I'm going to recover with Ease Windows software if I can't recover, if you wishes I can send my two microSD card for further investigation on your side.
I'm not complaining, I'm only commenting because I thinks this can help someone. 
Thanks again for your patience, your time and your software.

**Comment by jhermsmeier** [comment]
> if you wishes I can send my two microSD card for further investigation on your side.

@manuti thank you for offering that – it would indeed be very helpful in figuring out what's going on there! Let us know how it goes & should it fail, we'll figure out the shipping!

**Comment by lurch** [comment]
Unless your microSD cards are truly flaky at the hardware level, I think it's actually impossible to 'break' them from software.
In the worst possible case (if https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#recovering-broken-drives doesn't help), you should be able to use `sudo dd if=/dev/zero of=/dev/xxx bs=4M` on Linux which will overwrite your entire SD card with zeros (i.e. blank it), which may take some time, and then you should be able to use any disk-partitioning (or image-writing) tools as normal.
I don't have any Amlogic boards so I obviously can't help investigate why your SD cards weren't booting properly when flashed with an image but then did when you partitioned them manually.

**Comment by manuti** [comment]
@jhermsmeier Finally I can confirm that I have two 16GB microSD "bricked" 
How and where I can send you the cards?

**Comment by jhermsmeier** [comment]
@manuti can you shoot us an email at hello@etcher.io and we'll sort it there?
