### ISSUE TITLE
Error: *.tmp.node module not found

### ISSUE THREAD

**Issue by ben-h253** [resin-io/etcher#1956]
- **Etcher version:** 1.3.0
![error capture](https://user-images.githubusercontent.com/35154374/34632840-c53d606a-f26f-11e7-9b44-8081a751d4cf.PNG)

- **Operating system and architecture:** Windows 8
- **Image flashed:** ?
- **Do you see any meaningful error information in the DevTools?** n.a.

**Comment by vtabary** [comment]
Same here with Windows 10.
So I'll use the 1.2.1 for now : https://github.com/resin-io/etcher/releases/

**Comment by jviotti** [comment]
Hi @ben-h253 and @vtabary ,

Were you running the 64-bit or 32-bit versions? Also, were you using the installer or the portable versions? Do you have any anti-virus installed?

**Comment by vtabary** [comment]
Hi @jviotti ,

I'm running the 64-bits version of winfodows 10. And yes, I use Avast antivirus.

**Comment by jhermsmeier** [comment]
We've discovered that this is caused by the lack of certain C runtime libraries on some Windows systems that the WinUSB driver generator requires to function.
