### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by fcailloux** [resin-io/etcher#1958]
1.30
peppermint os
any image crash
buffer error

- **Etcher version:**
- **Operating system and architecture:**
- **Image flashed:**
- **Do you see any meaningful error information in the DevTools?**

**Comment by alexandrosm** [comment]
Hi there, thanks for the report. We've rolled back the 1.3.0 release,
please re-download from the website until we can fix this issue.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by jhermsmeier** [comment]
@fcailloux can you give us more detail on the "buffer error"? Might this be a duplicate of #1955?

**Comment by lurch** [comment]
Closing, as assuming this was fixed by the Etcher 1.3.1 release.
@fcailloux Please feel free to leave more details if you're still having problems with the latest version.

**Comment by jhermsmeier** [comment]
Duplicate of https://github.com/resin-io/etcher/issues/1955

**Comment by lurch** [comment]
Whoops, guess I forgot to actually click the "Close" button :rofl:
