### ISSUE TITLE
npm start command giving error at initial setup

### ISSUE THREAD

**Issue by nitikabhanot** [resin-io/etcher#1980]
var express = require('express');

I am just using this much code in my server.js file and after running 

npm install express successfully. I ran npm start server.js then it throws error as:

> meanproject@1.0.0 start D:\dinkar\node_js_installed\npm_setup
> node server.js "server.js"

D:\dinkar\node_js_installed\npm_setup\server.js:1
(function (exports, require, module, __filename, __dirname) { ��v
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meanproject@1.0.0 start: `node server.js "server.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meanproject@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\NITIKA\AppData\Roaming\npm-cache\_logs\2018-01-19T19_51_14_091Z-debug.log
Why this is happening on simple code? Is something missing in it!
Thanks for any kind of suggestions.

**Comment by jhermsmeier** [comment]
I think you're confusing repositories – the express framework is here: https://github.com/expressjs/express
