### ISSUE TITLE
Fix ARM build tooling

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io/etcher#1993]
Currently Etcher can only be built on / for ARM with some modifications / limitations.

**Issues:**

- **node-sass** doesn't support ARM, even though it works perfectly fine when manual platform checks are disabled in the code – fix in progress at [jhermsmeier/node-sass#arm-support](https://github.com/jhermsmeier/node-sass/tree/arm-support) and https://github.com/sass/node-sass/pull/2253
- **electron-builder** doesn't support running on ARM, even though it advertises building for it, due to fpm etc. not being available for ARM

Connects-To: #1992 #1688 #1683

**Comment by lurch** [comment]
Progress being tracked in #2870
