### ISSUE TITLE
unreadable usb drive

### ISSUE THREAD

**Issue by carlogaudio** [resin-io/etcher#2000]
- **Etcher version: 1.3.1
- **Operating system and architecture: windows 10 64bit
- **Image flashed: ubuntu 17.10.1 desk amd 64
- **Do you see any meaningful error information in the DevTools?
negative

negative

Hello everybody. I have trying to create a flash driver usb with etcher, selecting iso image of Ubuntu 17.10, in os platform Windows 10, and at end process i can't read anymore the usb drive 8 gb. Can anyone help me please? 
Thank you

**Comment by lurch** [comment]
This is because the filesystems used by Linux aren't readable by Windows. If you try booting from the USB drive, you should find that it works fine.
To restore your USB drive back to "normal", see https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#recovering-broken-drives
