### ISSUE TITLE
gpg: keyserver receive failed: No data

### ISSUE THREAD

**Issue by Dshoe** [resin-io/etcher#2009]
When executing `sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 379CE192D401AB61` I get `gpg: keyserver receive failed: No data`. This is possibly an `hkp://pgp.mit.edu:80` issue, but I figured I would let you guys know.

**Comment by Dshoe** [comment]
Never mind, the issue has been resolved after about 30 minutes.

**Comment by lurch** [comment]
Yeah, this has happened a couple of times recently, but obviously there's nothing we can do about it.
