### ISSUE TITLE
Etcher doesn't work on VoidLinux

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher#2011]
A user on gitter ( @tom-i ) has reported that whilst the AppImage runs on VoidLinux, it isn't able to flash an image.

We should investigate this.

**Comment by jhermsmeier** [comment]
@tom-i which CPU arch and desktop are you running?

**Comment by tom-i** [comment]
Ha, guys.. I used to use 1.1.2 version.
Today I downloaded 1.3.1 and it works like a charm..
So for VoidLinux users problem solved somehow by yours updates ;)
Please close this issue.

My configuration was:
uname -a
Linux PC 4.14.15_3 #1 SMP PREEMPT Sun Jan 28 22:13:16 UTC 2018 x86_64 GNU/Linux

lsb_release -a
LSB Version:	1.0
Distributor ID:	VoidLinux
Description:	Void Linux
Release:	rolling
Codename:	void

**Comment by lurch** [comment]
That's great news, thanks for letting us know! :smiley:

**Comment by Jakecheslekov** [comment]
I'm running i686 Void, are you guys gonna be adding support for Void Linux i686 & x86_64?

**Comment by lurch** [comment]
Just for clarity and to avoid any confusion:
If your kernel reports i686 then you're running in 32-bit mode and need to use the x86 version of Etcher
If your kernel reports x86_64 then you're running in 64-bit mode and need to use the x64 version of Etcher

@Jakecheslekov Does the x86 AppImage not work on i686 VoidLinux? I never got round to investigating this as @tom-i reported that the x64 AppImage worked fine on x86_64 VoidLinux.
Do you see any errors displayed if you run the x86 Etcher AppImage from a terminal window?
