### ISSUE TITLE
The Writer Process Ended Unexpectedly - Etcher

### ISSUE THREAD

**Issue by cavalier666-uk** [resin-io/etcher#2020]
get error - the writer process ended unexpectedly, when clicking write, windows 10 and ntfs 8gb pen drive, also same when run as administrator

tried latest version installed and portable, both do the same

windows 10 X64
recalbox.img - file
![capture](https://user-images.githubusercontent.com/36195060/35860801-4bf46ff0-0b3d-11e8-8296-25a0b1e1f517.PNG)

- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by jhermsmeier** [comment]
@cavalier666-uk is there any place we can obtain the image in question? Would like to give it a run & see if we can reproduce this.

**Comment by lurch** [comment]
@jhermsmeier I'd guess it's one of these? https://archive.recalbox.com/

**Comment by cavalier666-uk** [comment]
Hi yes that's the image. The pc x64 version

**Comment by l4gu5** [comment]
I had the same issue regarding NOOBS and Raspbian stretch image.
I removed the new version of etcher and installed the old 1.2.1 version and it works fine again, I hope that helps. My system is a Windows 10 64 bit

**Comment by cavalier666-uk** [comment]
thanks @l4gu5 will give that a go see if it works

**Comment by cavalier666-uk** [comment]
thanks again, confirmed working fine on 1.2.1

**Comment by lurch** [comment]
Labelling this as a bug, as it appears to be a regression from v1.2.1

**Comment by emon0509** [comment]
Please help me to find the 1.2.1 version or explain how to fix this issue

**Comment by lurch** [comment]
Older releases of Etcher can be found at https://github.com/resin-io/etcher/releases

**Comment by jhermsmeier** [comment]
@l4gu5 NOOBS cannot be flashed with Etcher, NOOBS is not a disk image, and needs a different installation procedure as described in https://www.raspberrypi.org/documentation/installation/noobs.md

**Comment by famaia** [comment]
I also had this problem today burning the latest version of RETROPIE (retropie-4.4-rpi2_rpi3.img) with the latest version of Etcher-Portable-1.5.39-x64 on Windows 10 x64.

After downloading Etcher 1.2.1, I was able to write the IMG successfully.

**Comment by thundron** [comment]
@famaia closed in favor of this one https://github.com/balena-io/etcher/issues/2757 please write there the output you see in Etcher's console (see last comment)

**Comment by splatkin** [comment]
right-click zip file > properties > check "unblock". Worked for me after that

**Comment by MaXiNom1** [comment]
Getting the same error vr 1.5.51 mac OSX HighSierra

**Comment by prajwalkoirala23** [comment]
same for me homeboy

**Comment by daton89** [comment]
Getting this error on Windows10 with 1.5.53

**Comment by Robert923** [comment]
Just had this issue - it was the Windows 10 Ransomware Protection.
Windows Security | Virus & threat protection | Ransomware protection (at the bottom)
Then you can either:
- temporarily disable Controlled folder access (easier) or
- click on "Allow an app through Controlled folder access", and then choose "Add an allowed app".  I find choosing the recently blocked apps is easiest.  Then just select balena-etcher (NOT the installer, that won't help).

I hope that helps,

Robert

you can

**Comment by DominoX** [comment]
Etcher 1.5.6 is still giving this error first reported here last year. Win 10 Pro with latest updates (10.0.18362 Build 18362)

1.2.1 still works

The 'Ransomware protection' work-around listed by @Robert923 did not work for me. Neither of the 2 methods shown

**Comment by CDeLeon94** [comment]
https://github.com/balena-io/etcher/issues/2833#issuecomment-511152047
> ```shell
> sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher
> ```
This worked for me

**Comment by ReubenBTalbott** [comment]
> [#2833 (comment)](https://github.com/balena-io/etcher/issues/2833#issuecomment-511152047)
> 
> > ```shell
> > sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher
> > ```
> 
> This worked for me
> 
> 1.5.57
> macOS Catalina Beta (19A573a)

That won't work on windows since windows does not have sudo, and windows stores apps in a different location than a Mac.

**Comment by CDeLeon94** [comment]
"Run as administrator"?

**Comment by ChrisRiddell** [comment]
> [#2833 (comment)](https://github.com/balena-io/etcher/issues/2833#issuecomment-511152047)
> 
> > ```shell
> > sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher
> > ```
> 
> This worked for me
> 
> 1.5.57
> macOS Catalina Beta (19A573a)

Thanks that worked for me on macOS Catalina Beta  (19A578c)

**Comment by lcrostarosa** [comment]
Had same issue on catalina prod this command worked for me as well 


```
    sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher

```

**Comment by lurch** [comment]
@lcrostarosa For problems with Catalina, see #2833

**Comment by AlexandruBuhai** [comment]
> [#2833 (comment)](https://github.com/balena-io/etcher/issues/2833#issuecomment-511152047)
> 
> > ```shell
> > sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher
> > ```
> 
> This worked for me
> 
> 1.5.57
> macOS Catalina Beta (19A573a)

Thanks! This was helpful!

**Comment by Borewit** [comment]
I had the same issue on Windows 10.
Downgraded from [v1.5.70](https://github.com/balena-io/etcher/releases/tag/v1.5.70) to [v1.2.1](https://github.com/balena-io/etcher/releases/tag/v1.2.1) which allowed me to flash.

**Comment by thundron** [comment]
I'd argue it's the same *permission* issue if it's a different OS, as permissions on Windows are *very* different than OSX/Linux.
You could consider looking for other Windows permission issues, or opening a new one if you don't find any similar to what you experienced

**Comment by Priyansu67** [comment]
I had the same issue and it was the controlled folder access which was blocking the etcher from acessing the image file. Just turn it of in settings will do the charm.

**Comment by sushah** [comment]
I had the same issue with portable version 1.5.79. Tried native windows installation - resulting in same error. Tried other versions, all with different errors. In the end, burned image with rufus and this worked without any issues.

**Comment by EmnaX** [comment]
I also ran into the same issue with 1.5.79. I'm running on macOS Catalina 10.15.3 (19D76). Running BalenaEtcher with sudo worked.

**Comment by lurch** [comment]
@EmnaX Your feedback may be useful on #3107 ?

**Comment by faaps** [comment]
> Just had this issue - it was the Windows 10 Ransomware Protection.
> Windows Security | Virus & threat protection | Ransomware protection (at the bottom)
> Then you can either:
> 
> * temporarily disable Controlled folder access (easier) or
> * click on "Allow an app through Controlled folder access", and then choose "Add an allowed app".  I find choosing the recently blocked apps is easiest.  Then just select balena-etcher (NOT the installer, that won't help).
> 
> I hope that helps,
> 
> Robert

Thanks a lot!, you save me!

**Comment by IIWare** [comment]
quit the app and reopen it, if it doesn't work then quit the app and run it as administrator, and I am sure I am the only one who wrote /issues/2020 lol

**Comment by longletian** [comment]
![image](https://user-images.githubusercontent.com/28197668/94507375-311ccc00-0242-11eb-9eb7-48786e4c3323.png)
 system version   win10 2004,  I've already used the administrator

**Comment by thundron** [comment]
@longletian please update to the latest version and retry. If it still doesn't work, check for an already open issue, this one is quite polluted with many other issues of old versions

**Comment by longletian** [comment]
thanks，The answer has been found

**Comment by stijojoseph** [comment]
> Just had this issue - it was the Windows 10 Ransomware Protection.
> Windows Security | Virus & threat protection | Ransomware protection (at the bottom)
> Then you can either:
> 
> * temporarily disable Controlled folder access (easier) or
> * click on "Allow an app through Controlled folder access", and then choose "Add an allowed app".  I find choosing the recently blocked apps is easiest.  Then just select balena-etcher (NOT the installer, that won't help).
> 
> I hope that helps,
> 
> Robert

u saved my 125mb etched download LOL thanks a lot
