### ISSUE TITLE
how can i create a write protect if i am create an image file with etcher?

### ISSUE THREAD

**Issue by skynetmedia** [resin-io/etcher#2025]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by lurch** [comment]
I'm afraid I don't understand your question. What does "create a write protect" mean?
Are you in fact asking for #266 ?

**Comment by lurch** [comment]
@skynetmedia Could you elaborate your question please? Otherwise we'll close this issue.

**Comment by jhermsmeier** [comment]
Closing – @skynetmedia please reopen once you come back to this
