### ISSUE TITLE
Image title overflows with Japanese characters

### ISSUE THREAD

**Issue by Shou** [resin-io/etcher#2032]
![image](https://user-images.githubusercontent.com/819413/36073782-2b262b16-0f2e-11e8-8690-a7f7bde5e854.png)

**Comment by jhermsmeier** [comment]
Is this an image name that contains Japanese characters, or does the ellipsing make them show up out of thin air?

**Comment by lurch** [comment]
Is this fixed by #2160 ?

**Comment by Shou** [comment]
That it is, thanks @lurch!
