### ISSUE TITLE
Etcher just DESTROYED 2 brand new Kingston USB keys

### ISSUE THREAD

**Issue by JFD73** [resin-io/etcher#2034]
DO NOT USE THIS SOFTWARE

**Comment by Eurobertics** [comment]
Can not confirm this. Just used Etcher to write Raspian or Debian images, even on likely new Kingston.
Did you get any errors?

**Comment by 1zerozero2** [comment]
Can you please elaborate?

**Comment by jhermsmeier** [comment]
@JFD73 can you detail the problems you're having, the image(s) flashed and the Etcher version? I'm going to close this for now, as this doesn't have any info for us to go on; feel free to reopen it if you can tell us more about it.
