### ISSUE TITLE
etcher spies on the user without consent

### ISSUE THREAD

**Issue by sneak** [resin-io/etcher#2057]
etcher version 1.3.1

This is the part of #1718 that is not yet resolved.

I launch the app and flash a disk, and it transmits my activity to multiple third parties (google analytics and mixpanel and some other one) without my consent or even warning me that it's doing so so that I could e.g. discontinue use of the spyware app.

Please fix this.  Transmitting user data without ADVANCE, OPT-IN consent is unethical.

**Comment by jviotti** [comment]
I double-checked this and can confirm no requests to any service (we don't even use Google Analytics, as claimed here) is made from the application. Closing as invalid. Please re-open if you can point us to an "unethical" request.

<img width="1047" alt="screen shot 2018-02-19 at 10 47 09" src="https://user-images.githubusercontent.com/2192773/36374154-4824ab9a-1562-11e8-8eef-79e8f3aee44c.png">

**Comment by kevcampb** [comment]
I started up etcher (1.4.8), and it certainly makes a large number of tracking requests on startup, without any opt-in to analytics.

![screenshot 2018-11-29 at 15 02 05](https://user-images.githubusercontent.com/1244107/49204825-0ebc8c00-f3e8-11e8-87d3-298246c81d6b.png)

Content is now sent over HTTPs, so I don't have the internals of these. Google analytics is certainly included. The previous version of etcher certainly included tracking codes in the messages sent to services.

There is a setting "Anonymously report errors and usage statistics to balena.io" in the settings, but it is defaulted to on.
