### ISSUE TITLE
tiling window manager (i3wm) file selection broken

### ISSUE THREAD

**Issue by dayne** [resin-io/etcher#2058]
- **Etcher version: 1.3.1** 
- **Operating system and architecture: Ubuntu 16.04**  

I'm using a tiling window manager on Ubuntu, [i3wm](https://i3wm.org/) specifically , and when I push the `select image` button it gives me a full screen blank (white) window with no text/buttons. I can hit escape to close it.

I'd love to debug this but not sure where to start.  DevTools doesn't open up for the full screen blank file selection window. 

For others that might run into this - I was able to make etcher work in i3wm by using Xnest:

```
sudo apt install xnest # install Xnest
Xnest :1 -ac &         # launch a nested X server on :1
export DISPLAY=:1      # set current terminal DISPLAY to use that Xnest server
etcher-electron        # launch etcher inside Xnest 
                       # file selection dialog works fine
```

**Comment by lurch** [comment]
Connects (ish) to #1563 so assigning this to @Shou
