### ISSUE TITLE
No windows downloads available for 1.3.1

### ISSUE THREAD

**Issue by InuyashaITB** [resin-io/etcher#2072]
- **Etcher version:** 1.3.1
- **Operating system and architecture:** Windows 10 - x64

There is no download links available for 1.3.1 on Windows.

**Comment by jhermsmeier** [comment]
@InuyashaITB thanks for bringing this up so quickly; our build pipeline appears to have caught a bug and decided to meddle with our releases; I've fixed the v1.3.1 downloads now – will keep this issue open until the underlying issue is resolved.

**Comment by MttArmstrong** [comment]
Having the same problem with MacOS as well, just a heads up! @jhermsmeier

**Comment by jhermsmeier** [comment]
@MttArmstrong everything is back to normal as far as we can see; are you still having issues downloading it?

**Comment by jhermsmeier** [comment]
Closing, as the underlying cause has been tended to
