### ISSUE TITLE
EINVAL: invalid argument, write

### ISSUE THREAD

**Issue by tangb** [resin-io/etcher#2074]
- **Etcher version:** 
etcher-cli 1.3.1
- **Operating system and architecture:** 
Linux debian x64 stable 8.10 up-to-date (Linux mp-de-057 4.7.0-0.bpo.1-amd64 #1 SMP Debian 4.7.8-1~bpo8+1 (2016-10-19) x86_64 GNU/Linux)
- **Image flashed:** 
Raspberry pi https://downloads.raspberrypi.org/raspbian_lite_latest
- **Do you see any meaningful error information in the DevTools?** 
No DevTools on cli

I launch cli as root (not sudo) with this command:
> ./etcher --drive /dev/mmcblk0 /home/tbonneau/Downloads/2017-11-29-raspbian-stretch-lite.zip

And I got a confirmation message
> ? This will erase the selected drive. Are you sure? Yes

Finally I simply got:
> EINVAL: invalid argument, write

Is there a way to get more info ?
Is there something I can do to investigate more ?

Thank you

**Comment by tangb** [comment]
I tested with older cli version and:
- 1.2.1 => failed
- 1.2.0 => success
- 1.1.2 => success

By the way, etcher application v1.3.1 works well on the same computer with the same input file.

**Comment by jhermsmeier** [comment]
This is something that happens on some Linux machines; and should be fixed by #2055 in the next release of Etcher

**Comment by tangb** [comment]
@jhermsmeier 
ok thank you very much for your answer

**Comment by lurch** [comment]
Should this be closed then @jhermsmeier ?
