### ISSUE TITLE
CONTRIBUTING.md doesn't mention the `make webpack` step

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher#2079]
...which means if you only follow what https://github.com/resin-io/etcher/blob/master/docs/CONTRIBUTING.md says, then you get a version of Etcher that doesn't work properly and just prints:
```
gui.js Failed to load resource: net::ERR_FILE_NOT_FOUND
```
in the DevTools console.

**Comment by lurch** [comment]
...and I've just noticed that it doesn't mention the `make cli-develop` step either?

**Comment by jhermsmeier** [comment]
I didn't even know `cli-develop` existed o.O

**Comment by lurch** [comment]
`make help` is your friend ;)

**Comment by lurch** [comment]
Should I create a separate issue for `make cli-develop` being missing from CONTRIBUTING.md ?

**Comment by jhermsmeier** [comment]
Yeah, or just make a PR? ;P
