### ISSUE TITLE
Unmount failed

### ISSUE THREAD

**Issue by shawaj** [resin-io/etcher#2110]
- **Etcher version:** 1.3.1
- **Operating system and architecture:** See attached image
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** No

Despite this error, the flash has actually completed successfully!

![image](https://user-images.githubusercontent.com/3359418/37180428-daa2251c-2320-11e8-98bd-1283f65f0510.png)
![image](https://user-images.githubusercontent.com/3359418/37180446-ed29e404-2320-11e8-80b1-1c98b9b7fa5d.png)
![image](https://user-images.githubusercontent.com/3359418/37180466-0aefebc8-2321-11e8-86a9-32c073afa0f0.png)

**Comment by jhermsmeier** [comment]
Duplicate of #1370
