### ISSUE TITLE
Flash drive size reduced

### ISSUE THREAD

**Issue by entraide-net** [resin-io/etcher#2117]
Last etcher on Windows 7 64 bits, Debian 9.4 Mate non-free iso, tried formating, disk manager and diskpart on Windows, dd on Linux ...

I try to get it empty and at full size like usual, it show under a Gb for a 4Gb drive ...

**Comment by lurch** [comment]
Does https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#recovering-broken-drives help?

**Comment by entraide-net** [comment]
no I did solve it on Linux at home, Windows 7 and 10 weren't able to
do anything, the documentation failed to help ...

2018-03-13 6:55 UTC−04:00, Andrew Scheller <notifications@github.com>:
> Does
> https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#recovering-broken-drives
> help?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io/etcher/issues/2117#issuecomment-372625716


-- 
Michaël Caron Couturier

**Comment by jhermsmeier** [comment]
I guess this can be closed then
