### ISSUE TITLE
Error Opening Etcher if Etcher's Obtrusive Internet Requests are Filtered

### ISSUE THREAD

**Issue by ClosetCoder** [resin-io/etcher#2126]
- **Etcher version:** 
     v1.3.1

- **Operating system and architecture:** 
     mac OS High Sierra v10.13.3 (17D102) - i7 Quad 2.4GHz - 16GB RAM - 512GB SSD
- **Image flashed:** 
     None - Error occurs simply opening app if internet access is filtered
- **Do you see any meaningful error information in the DevTools?** 
     Yes:  [Error-A](https://ibb.co/cQcNZc)  &  [Error-B](https://ibb.co/esy70H)
- **Error message produced by Etcher**
     Yes:  [Error Message](https://ibb.co/ccHRkH) w/'OK' to proceed
- **Clicking 'OK' on message allows Etcher to run**
     Yes
- **Define Filtered in Issue Title**
     When Etcher is opened, and obtrusively begins to reach for multiple sites online,
     some are allowed, while others are denied.

**Comment by jhermsmeier** [comment]
Error A

![image](https://user-images.githubusercontent.com/244907/37684501-7efe6864-2c90-11e8-9813-4d676bec7d25.png)

Error B

![image](https://user-images.githubusercontent.com/244907/37684517-8b9ceda2-2c90-11e8-9f1f-3ab0e03dfd1b.png)

Error Message

![image](https://user-images.githubusercontent.com/244907/37684533-98e74520-2c90-11e8-837a-d87bb3d2fcb5.png)
