### ISSUE TITLE
Error Opening Etcher if Etcher's Obtrusive Internet Requests are Blocked by Firewall

### ISSUE THREAD

**Issue by ClosetCoder** [resin-io/etcher#2127]
- **Etcher version:** 
     v1.3.1

- **Operating system and architecture:** 
     mac OS High Sierra v10.13.3 (17D102) - i7 Quad 2.4GHz - 16GB RAM - 512GB SSD
- **Image flashed:** 
     None - Error occurs simply opening app if internet access is blocked
- **Do you see any meaningful error information in the DevTools?** 
     Yes:  [Error-A](https://ibb.co/cQcNZc)  &  [Error-B](https://ibb.co/esy70H)
- **Error message produced by Etcher**
     Yes:  [Error Message](https://ibb.co/mTnuxx) w/'OK' to proceed
- **Clicking 'OK' on message allows Etcher to run**
     Yes
- **Define Blocked in Issue Title**
     Rules are added to firewall to block ALL internet requests made by Etcher

**Comment by jhermsmeier** [comment]
Inlining images here for quicker reference;

Error A

![image](https://user-images.githubusercontent.com/244907/37684597-dfe630bc-2c90-11e8-8f5d-7b347d09ab2d.png)

Error B

![image](https://user-images.githubusercontent.com/244907/37684606-e4656db0-2c90-11e8-8dc3-4c9dc54698b5.png)

Error Message

![image](https://user-images.githubusercontent.com/244907/37684619-ec7ce37a-2c90-11e8-97e1-f32b5135a24c.png)

**Comment by lurch** [comment]
Looks like this is closely related to #2126 ? (just with a slightly different error dialog at the last step)

**Comment by BananaAcid** [comment]
And possibly #2143 (for Windows).
