### ISSUE TITLE
2TB hardrive erased?

### ISSUE THREAD

**Issue by Kcirtap6564** [resin-io/etcher#2133]
I downloaded etcher and made a drive for Ubuntu recently. I put the .iso in a new file on a 2TB hard drive that I had all my military photos and videos from my deployments on. I downloaded Ubuntu onto my laptop and plugged my hard drive back into my desktop and all the files are gone. I had thousands of pictures and videos of me and my buddies over seas. Some of them did not make it back, so this hard drive's photos and videos are all I really have left of them. Please do not tell me the files are gone. If I can bring it to anyone who can possibly restore the information I will do it regardless of cost. Any help will be greatly appreciated. I'm not very tech savvy, but I will do my best to provide any information that you may need to help understand the issue.

**Comment by KeithIMyers** [comment]
Thank you for your service. That is not good. Contact me directly off group
and I will try to help you get the photos back.

keithiokepamyers@gmail.com
