### ISSUE TITLE
Any chance for a flatpak and hosting it on flathub.org?

### ISSUE THREAD

**Issue by HoboPrimate** [resin-io/etcher#2141]
I believe flatpaking eletron apps is still a work in progress, but doing it would give the user advantages, such as peace of mind of it being sandboxed and allow them to update etcher easily. It would also make etcher be more discoverable if hosted on flathub.org.

Consider this just a small wish, as the appimage version seems to works fine!

Thank you

**Comment by lurch** [comment]
Duplicate of #2019 ?

**Comment by HoboPrimate** [comment]
Yep, sorry for the noise.
