### ISSUE TITLE
Etcher's Obtrusive Internet Needs produce Errors in Windows 10 Pro When Blocked

### ISSUE THREAD

**Issue by ClosetCoder** [resin-io/etcher#2143]
- **Etcher version:** 
v1.3.1 both 'portable' and 'installed' instances
- **Operating system and architecture:** 
Windows 10 Pro v10.0.16299
Dell Latitude i7 Quad Core - 16GB RAM
- **Image flashed:** 
Yes - Bitdefender Rescue CD
- **Do you see any meaningful error information in the DevTools?** 
Yes - [Error in GUI](http://ibb.co/e4Vj5S)
and - [Error in Console](http://ibb.co/hzGJX7)

**Comment by jviotti** [comment]
This should be fixed in later versions
