### ISSUE TITLE
Failed to fetch https://dl.bintray.com/resin-io/debian/dists/stable/InRelease 

### ISSUE THREAD

**Issue by sherminator666** [resin-io/etcher#2144]
- **Etcher fresh install thru terminal** 
- **Operating system and architecture: debian 9, 32bit** 
- 
- **Do you see any meaningful error information in the DevTools? NA**

**Comment by jhermsmeier** [comment]
Can you post how exactly you installed it, meaning which commands you ran?

**Comment by sherminator666** [comment]
i did this
echo "deb https://dl.bintray.com/resin-io/debian stable etcher" | sudo tee /etc/apt/sources.list.d/etcher.list
and then did 
sudo apt-get update
it was then the mentioned error showed..

**Comment by jhermsmeier** [comment]
Ref #1638, #1634, #1633

**Comment by jhermsmeier** [comment]
Thanks, we'll look into it!

**Comment by sherminator666** [comment]
also did this before update command
sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 379CE192D401AB61

i was just following instructions on https://github.com/resin-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64

**Comment by lurch** [comment]
Hmmm, this still works for me (on Ubuntu 14.04)
```bash
$ sudo apt-get update|grep bintray
Get:5 https://dl.bintray.com stable InRelease
Ign https://dl.bintray.com stable InRelease
Hit https://dl.bintray.com stable Release.gpg
Hit https://dl.bintray.com stable Release
Hit https://dl.bintray.com stable/etcher amd64 Packages
Hit https://dl.bintray.com stable/etcher i386 Packages
Get:11 https://dl.bintray.com stable/etcher Translation-en_GB
Get:13 https://dl.bintray.com stable/etcher Translation-en
Get:16 https://dl.bintray.com stable/etcher Translation-en_GB
Get:17 https://dl.bintray.com stable/etcher Translation-en
Get:18 https://dl.bintray.com stable/etcher Translation-en_GB
Get:19 https://dl.bintray.com stable/etcher Translation-en
Get:20 https://dl.bintray.com stable/etcher Translation-en_GB
Get:21 https://dl.bintray.com stable/etcher Translation-en
Get:22 https://dl.bintray.com stable/etcher Translation-en_GB
Ign https://dl.bintray.com stable/etcher Translation-en_GB
Get:23 https://dl.bintray.com stable/etcher Translation-en
Ign https://dl.bintray.com stable/etcher Translation-en
```

Perhaps the `apt-get` command works slightly differently on Debian 9?

Hmmm, did a bit of searching and eventually found https://unix.stackexchange.com/questions/387053/debian-9-apt-and-gpg-error-inrelease-the-following-signatures-were-inva

**Comment by andersab** [comment]
Didn't work for me either...
sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 379CE192D401AB61
Executing: /tmp/apt-key-gpghome.DU63ZhEJ9o/gpg.1.sh --keyserver hkp://pgp.mit.edu:80 --recv-keys 379CE192D401AB61
gpg: keyserver receive failed: No data

**Comment by jhermsmeier** [comment]
@andersab looks like you're experiencing #1786, rather than this issue

**Comment by Luccasbb2** [comment]
Vá em fontes de aplicativos, depois Bintray/ stable e desabilita, isso resolveu pra mim.

**Comment by zahyaa** [comment]
https://github.com/balena-io/etcher?d_id=58e02706-2ca2-465d-bd23-5b4f5b801e22R#debian-and-ubuntu-based-package-repository-gnulinux-x86x64

Follow this link ti install .deb using termianl commands.
