### ISSUE TITLE
OS X: Uncaught exception thrown if no password is given on startup

### ISSUE THREAD

**Issue by lekkas** [resin-io/etcher#215]
If I click 'Cancel' when the admin password dialog pops up on program startup the following exception is thrown after the 'Elevation Error' message:
<img width="414" alt="screen shot 2016-03-22 at 21 22 43" src="https://cloud.githubusercontent.com/assets/5211478/13980809/243ff9d6-f0e9-11e5-9c26-d99c3a7a0c78.png">

Minor bug really, more UX related since it doesn't affect program usability.

**Comment by jviotti** [comment]
@lekkas Thanks for the heads up! Sorry for the late response, turns out I wasn't "watching" the repo and therefore got no notifications :)

I'll send a fix very soon.

**Comment by jviotti** [comment]
PR sent, thanks a lot!

**Comment by lekkas** [comment]
Cool! By the way, I've been using Etcher since last week and there is no going back when it comes to burning SD cards! :+1:

**Comment by jviotti** [comment]
Awesome to hear that! Ping me with any suggestions :)
