### ISSUE TITLE
it looks like (mac high sierra)

### ISSUE THREAD

**Issue by kv71** [resin-io/etcher#2193]
- **Etcher version:** 
version v1.3.1
- **Operating system and architecture:** 
MAc OS high Sierra version 10.13.4
- **Image flashed:** 
windows 10 , windows server 2016, ect 
- **Do you see any meaningful error information in the DevTools?** 

before i could easy (in high sierra use etcher to burn windows ) but now  it always mentions "It Looks like this is not a bootable image
![screen shot 2018-04-11 at 14 27 34](https://user-images.githubusercontent.com/38282597/38616554-b2945052-3d94-11e8-809f-42bbf57c5e4d.png)

**Comment by lurch** [comment]
See https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#why-is-my-drive-not-bootable

**Comment by kenny-w1** [comment]
You guys should add Solaris, NetBSD & OpenBSD to that list along with Windows 10... FreeBSD will work tho.
I always thought Etcher worked with windows/etc, didn't know it was just like DD...

**Comment by lurch** [comment]
See also #210

**Comment by jhermsmeier** [comment]
Closing this, as it's documented, and alternatives available
