### ISSUE TITLE
Implement file-picker UI

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#2238]
![screen 02](https://user-images.githubusercontent.com/2192773/39143626-712888c4-46fc-11e8-96a2-3dfcd53f9ebb.png)

We should be able to pass this component a path as the "initial location"

**Comment by jviotti** [comment]
The file picker should be able to show all available partitions of a drive a user could go to.

**Comment by jhermsmeier** [comment]
Closed by https://github.com/resin-io/etcher/pull/2333, https://github.com/resin-io/etcher/pull/2349 and https://github.com/resin-io/etcher/pull/2350

**Comment by lurch** [comment]
I guess this also connects to #1823 ?  (and #2362 )
