### ISSUE TITLE
Add an environment variable that can be used to instruct the UI to run in Etcher Pro mode

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#2244]
This environment variable should of course be set in the Dockerfile that will run the app.

**Comment by jhermsmeier** [comment]
@jviotti any details on the solution that's going to replace this?

**Comment by jviotti** [comment]
@jhermsmeier We will use different environment variables to enable separate features that together become Etcher Pro.

**Comment by lurch** [comment]
Does that mean that enabling some env-vars but not others will create "Etcher semi-pro" ? :laughing:
