### ISSUE TITLE
Disable links that go to external websites when running on Etcher Pro mode

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#2246]
Etcher Pro users will of course not be able to navigate to them. This includes logos in the footer.

**Comment by jviotti** [comment]
This is blocked by https://github.com/resin-io/etcher/issues/2244

**Comment by lurch** [comment]
Will it still load the success-banner over HTTP? Does that mean there needs to be an Etcher-Pro-specific success-banner that (unlike the normal success-banner) never contains any external links?

**Comment by jviotti** [comment]
I clarified it a bit here: https://github.com/resin-io/etcher/issues/2266

**Comment by jviotti** [comment]
Lets expose this mode through an environment variable such as `ETCHER_MODE_NON_EXTERNAL_LINKS` or something like that
