### ISSUE TITLE
Get Etcher to run as a container inside the Up Squared

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#2255]
Write this Dockerfile into a separate `etcher-pro` (private) repository.

**This Dockerfile should install Etcher from Bintray as a debian package.**

We might need to configure the screen correctly (ie the rotation, etc)

**Comment by jviotti** [comment]
We should try to re-use https://github.com/resin-io/resin-electronjs for this project.

**Comment by jhermsmeier** [comment]
Closing, as done. See https://www.flowdock.com/app/rulemotion/r-etcherprv/threads/is7_MaRUyDzJ_Ue_MPa0mkp7i3n for details
