### ISSUE TITLE
Implement an Etcher Pro development Resin container

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#2256]
So we can develop and build Etcher inside it. Maybe it should also give you Etcher as an available git repository.

**Comment by jhermsmeier** [comment]
@jviotti can you clarify "Maybe it should also give you Etcher as an available git repository."?

**Comment by jviotti** [comment]
@jhermsmeier I meant that the etcher repo is already cloned inside the image, so you can just pull and get to work.

**Comment by jhermsmeier** [comment]
@jviotti @curcuz I suppose https://github.com/resin-io/etcher-pro/pull/2 already supports this? (I'm still not 100% clear on what this issue's requirements are)
