### ISSUE TITLE
Publish Debian packages to Bintray through Resin CI on every commit 

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#2260]
So we can easily test Etcher Pro updates.

**Comment by lurch** [comment]
Isn't this kind of the opposite of what #2076 did? :confused:

**Comment by jviotti** [comment]
@lurch The main motivation behind that PR was to reduce pricing, but we're looking at getting an Open Source free Bintray account (for which Etcher qualifies), so we might be able to pull it off that way.
