### ISSUE TITLE
Make the Resin container capable of loading an .env file with settings

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#2265]
We will use these variables to configure what LEDs correspond to what drives, etc.

**Comment by jhermsmeier** [comment]
We should be able to re-use https://github.com/resin-io/etcher/pull/2311 for this

**Comment by lurch** [comment]
> We should be able to re-use #2311 for this

I guess that presumes that everything that's configurable through an env-var, is also configurable through the localSettings? Currently IIRC there are several places in the code which **only** look at `process.env` .

**Comment by lurch** [comment]
Has this been closed by #2368 and #2369 ?

**Comment by jhermsmeier** [comment]
Not quite yet, some changes on the Etcher Pro side still tbd
