### ISSUE TITLE
[Bug Report] Etcher 1.4.3 - Drive Select GUI Error

### ISSUE THREAD

**Issue by Richyread** [resin-io/etcher#2267]
- **Etcher version:** 1.4.3
- **Operating system and architecture:** Win 10(64)
- **Image flashed:** Raspbian Stretch Lite (13-03-2018)
- **Do you see any meaningful error information in the DevTools?** See screenshot attached.

I have upgraded my Etcher installation this morning and encountered an issue with writing an image to an SD Card - specifically that the device/drive selection step appears to accept and then immediately cancel the choice within the GUI ~ see shot below for better description 😄 

![etcher_143_error](https://user-images.githubusercontent.com/7470850/39170481-a54fff5a-4793-11e8-8876-8b28cae020e2.gif)

**Workflow prior to upgrade:**

- Insert SD Card into reader

- Close Win10's 'Please Format Drive' prompts

- Launcher Etcher

- Select image file (including .ZIP archived images)

- Select USB Card Reader

- Click 'Flash'

Etcher would then in chain of actions, Format the Drive(s), Extract the image, Write the image, Tidy up, Eject SD Reader.

Since the upgrade I'm unable to proceed past the 'Select Drive' stage.

Screenshot of Etcher_Console, below.

![etcher_143_console](https://user-images.githubusercontent.com/7470850/39170494-adfd0634-4793-11e8-8342-41b1126cb348.png)

Hope this helps - let me know if you need anything further etc.

Many thanks,

Richy.

**Comment by PecoraInPannaCotta** [comment]
Same on ubuntu 17.10

**Comment by nex86** [comment]
same issue. going back to 1.3.1!

**Comment by Shou** [comment]
What happens when you double-click?

**Comment by nex86** [comment]
it keeps deselecting even when you double click.

**Comment by PecoraInPannaCotta** [comment]
If you go faster than the GUI, you can actually flash the ISO, so is confirmed is just a UI problem

**Comment by fivestones** [comment]
I wish I were as fast as you :-)

**Comment by Shou** [comment]
I've identified the issue and fixed it in the above PR. We'll have 1.4.4 out shortly.
