### ISSUE TITLE
Update winusb-driver-generator to build under Visual Studio 2015

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#2270]
This is blocking an upgrade to a newer Electron version

**Comment by lurch** [comment]
See also https://github.com/resin-io-modules/winusb-driver-generator/issues/26

**Comment by jhermsmeier** [comment]
Fixed in https://github.com/resin-io-modules/winusb-driver-generator/pull/28

**Comment by lurch** [comment]
Just to be pedantic, should this be closed when https://github.com/resin-io/etcher/blob/master/package.json#L99 gets upgraded to 1.2.0 ?
