### ISSUE TITLE
Add an environment variable to restrict the directories the user can see on the file picker

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#2285]
This will be used by Etcher Pro to not allow the user to see anything else other than the source drive.

**Comment by jhermsmeier** [comment]
Closed by https://github.com/resin-io/etcher/pull/2333

**Comment by lurch** [comment]
Should this also be using the "unique device path" stuff added by #2325 ? Since IIRC the "source drive" is identified by which particular USB slot it's plugged into?
