### ISSUE TITLE
gpg: keyserver receive failed: No data

### ISSUE THREAD

**Issue by NatoBoram** [resin-io/etcher#2303]
- **Etcher version:** N/A
- **Operating system and architecture:** Ubuntu 18.04 LTS x86_64
- **Image flashed:** N/A
- **Do you see any meaningful error information in the DevTools?** N/A

```bash
sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 379CE192D401AB61
Executing: /tmp/apt-key-gpghome.0M3e6QLdQ9/gpg.1.sh --keyserver hkp://pgp.mit.edu:80 --recv-keys 379CE192D401AB61
gpg: keyserver receive failed: No data
```

**Comment by jhermsmeier** [comment]
Duplicate of #1786

**Comment by djkerya** [comment]
sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 379CE192D401AB61
Executing: /tmp/apt-key-gpghome.3wzLSL1SLd/gpg.1.sh --keyserver hkp://pgp.mit.edu:80 --recv-keys 379CE192D401AB61
gpg: keyserver receive failed: No data
