### ISSUE TITLE
Windows "Format Removable Disk" pops up mid Etcher flash

### ISSUE THREAD

**Issue by Matei-Ciobotaru** [resin-io/etcher#2308]
- Etcher 1.4.4
- Windows 7 Enterprise SP 1, 64bit
- Rock64 Armbian 5.42  OS image
- No errors reported.

Issue description:

Firstly, thanks for Etcher and keep up the good work!

While flashing the above mentioned image to a USB to eMMC adapter, using a Sandisk 32GB eMMC a window appeared asking if I would like to format the eMMC card... 

![etcher_1 4 4](https://user-images.githubusercontent.com/38288638/39696578-cdfb6396-51f6-11e8-8726-434a914f5c17.JPG)

I would expect Etcher to format the drive before flashing and to try to suppress these kind of messages from the OS as it's possible that at some point, some inexperienced user will actually format the drive mid flash and then complain it won't boot or worse, end up corrupting it...

I want to add, the eMMC was already flashed with a Ubuntu Artful image, before attempting the Armbian image flash, yet Windows did not pop up that dialog when first inserting the USB to eMMC adapter,

Regards.

**Comment by Chealer** [comment]
Thank you for reporting @Matei-Ciobotaru
This unfortunately also affects Etcher 2.1.4 on Windows 11 24H2, which failed with unhelpful errors all 5+ attempts I made to write [debian-live-13.0.0-amd64-kde.iso](https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-13.0.0-amd64-kde.iso):
> Something went wrong. If it is a compressed image, please check that the archive is not corrupted.
> The writer process ended unexpectedly

Using Rufus 4.9 instead worked like a charm.

@jviotti: Please clarify how this was (supposedly?) solved

<details>
  <summary>License</summary>
This comment and any other I might add to this ticket is offered under the terms of CC0 1.0.
</details>
