### ISSUE TITLE
Etcher download issue

### ISSUE THREAD

**Issue by chaudharisuresh997** [resin-io/etcher#2336]
If you use etcher 32 bit linux version cli or normal download it does not complete it fails whe  reached to 60% of 90% progress level

- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by lurch** [comment]
The downloads are all working fine for me - perhaps there was a temporary problem with your ISP?

**Comment by chaudharisuresh997** [comment]
I agree later on download got successful

On May 14, 2018 16:00, "Andrew Scheller" <notifications@github.com> wrote:

The downloads are all working fine for me - perhaps there was a temporary
problem with your ISP?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/resin-io/etcher/issues/2336#issuecomment-388771235>,
or mute
the thread

**Comment by samnet** [comment]
Also having trouble with this. Every time I try to download etcher on my mac it fails (Failed - Network error) halfway, on both Chrome and Safari.
