### ISSUE TITLE
Fix touch areas on Etcher Pro

### ISSUE THREAD

**Issue by Shou** [resin-io/etcher#2364]
There is a strange behaviour where only certain regions are clickable, these regions being elements on the current page e.g. main page buttons and icons, settings page checkboxes. This results in the file-picker being unusable because the clickable areas are retained, and only files that overlap with the buttons on the page behind the modal are clickable.

- Touch screen tested to work perfectly when plugged directly into laptop, none of these issues

**Comment by jhermsmeier** [comment]
Fixed in #2372
