### ISSUE TITLE
Etcher erroneously thinks micro SD card is locked. Cannot write to it.

### ISSUE THREAD

**Issue by davidrnewman** [resin-io/etcher#2366]
Ignore this issue. I found a read only switch on the card adaptor, not on the card itself.

**Comment by kriekprinsloo** [comment]
Yes, this has happened to me before as well.  It turned out that there was
something wrong with my SD card reader.  Maybe try a different computer?

Also, there is a lock usually on your microSD card adapter.  Try a few
other adapters, see if that fixes the problem.

**Comment by jhermsmeier** [comment]
Thanks for helping out here @kriekprinsloo! Going to close this then, as the read-only switch was at fault here ;)

**Comment by kriekprinsloo** [comment]
No problem :) glad to be able to help you guys out.

**Comment by nalply** [comment]
Another tip: for me it helped to tap the adapter with the finger really hard, sometimes the lock state seems to get stuck
