### ISSUE TITLE
Recover the data in the USB drive 

### ISSUE THREAD

**Issue by seevider** [resin-io/etcher#2378]
Hi all,

I used the etcher to flash an os image to my USB drive but I forgot to copy all the original files in the USB drive before I did the action. Then, I lost all my files......

Is it possible to recover the USB drive? How can I do that?

Thanks

**Comment by KeithIMyers** [comment]
Not likely

**Comment by jhermsmeier** [comment]
Sorry to hear that @seevider, unfortunately that's bad news. There might be a possibility to recover some files, depending on large the image you flashed was, and some other factors. But I'm afraid we can't do much, apart from suggesting recovery software that helped some people before (have to go look them up again)

**Comment by seevider** [comment]
Thank you for your information @jhermsmeier. I formatted my USB driver and the storage space went back to original size. I will try the recovery software to recover the data.

**Comment by lurch** [comment]
Unfortunately formatting your drive first may make the recovery process less successful :-(
