### ISSUE TITLE
"Eject on success" yet validation fails

### ISSUE THREAD

**Issue by MakiseKurisu** [resin-io/etcher#2386]
- 1.4.4
- Win10 x64
- raspbian-lite.zip
- No

Well guess what I'm gonna do if the data on the disk is not the same as the image I was trying to burn?

Flash again.

Currently Etcher ejects as long as write has no error.

**Comment by jhermsmeier** [comment]
So, if I read this correctly, you'd like Etcher to *not* unmount / eject devices that have failed validation?
