### ISSUE TITLE
I am having trouble downloading the latest etcher version for windows 64

### ISSUE THREAD

**Issue by ellafairhurst** [resin-io/etcher#2389]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by jhermsmeier** [comment]
Hi @ellafairhurst, can you describe the issue you're having in a little more detail? Does the download not complete, is it slow, or what's happening?

**Comment by jhermsmeier** [comment]
And from where are you downloading it (https://etcher.io, github releases, etc...)?

**Comment by ellafairhurst** [comment]
Actually, it seems to be working now, thanks!

**Comment by jhermsmeier** [comment]
Alright, good to hear! Do let us know if you have any further troubles!

**Comment by ellafairhurst** [comment]
Hi,
    Have attached the zero cam to the pi zero, it lights up green, but
there is no red light on the zero cam, do you know why this would be?
Thanks,
            Ella

**Comment by lurch** [comment]
That sounds like a question for https://www.raspberrypi.org/forums/ rather than the Etcher issues list :wink:

**Comment by ellafairhurst** [comment]
I've downloaded etcher but can't download naturecam file, seems to be
corrupted.
Any suggestions?
Thanks
       Ella
