### ISSUE TITLE
/!\ Urgent /!\ 32 GO lost ...

### ISSUE THREAD

**Issue by Hadesa** [resin-io/etcher#2391]
I lost my 32 GB that I had on my micro SD card because of your Flash software. How to recover them?

**Comment by cj2tech** [comment]
I would suggest downloading SD card formatter (https://www.sdcard.org/downloads/formatter_4/index.html) or Rufus (https://rufus.akeo.ie.).

I would also suggest once done format using your Os built in formatted and unchecking quick format or set all bytes to 0. It will take a long time to do it but it will help clear out your SD of any bugs and set it to a factory state.

**Comment by cj2tech** [comment]
I’d also reccoment to uninstall etcher.io and reinstall. And check to make sure all you drivers are up to date.

**Comment by Hadesa** [comment]
I try formatter via the console

**Comment by jhermsmeier** [comment]
@Hadesa we can't really help you without a little bit more info; what steps did you take until this occured? i.e. did you flash the card, and with which image, which version of Etcher are you running, etc.?

**Comment by Hadesa** [comment]
Forget I managed it alone thanks to other forum
