### ISSUE TITLE
Cannot Install Etcher

### ISSUE THREAD

**Issue by SwiftHackerz** [resin-io/etcher#2392]
- **Etcher version: 1.4.4** 
- **Operating system and architecture: Windows x64** 
- **Image flashed: None** 

Whenever I install Etcher, my antivirus always scans the exe file and it says that there is a virus inside the program installer. And whenever I try to restore the installer, it always gives me a warning that there is a heuristic virus (Heur.AdvMLC) and it could harm my system. Is this a normal thing or is my computer reacting to this virus embedded in the installer? 

![image](https://user-images.githubusercontent.com/33038633/41480904-e531af3c-7084-11e8-8bc8-f7743d45d644.png)

**Comment by Synaxis** [comment]
https://www.virustotal.com/en/file/432203b640ace82b91a951146bd4d45fdc60ed0d9e91140abfa275a2108bee6c/analysis/

**Comment by jhermsmeier** [comment]
@SwiftHackerz can I ask where you're downloading Etcher from?

**Comment by SwiftHackerz** [comment]
I installed Etcher straight from the source. (https://etcher.io/)
-------- Original message --------From: Jonas Hermsmeier <notifications@github.com> Date: 6/18/18  6:59 AM  (GMT-08:00) To: resin-io/etcher <etcher@noreply.github.com> Cc: SwiftHackerz <cool.aqualine@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [resin-io/etcher] Cannot Install Etcher (#2392) 
@SwiftHackerz can I ask where you're downloading Etcher from?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/resin-io/etcher/issues/2392#issuecomment-398063523","url":"https://github.com/resin-io/etcher/issues/2392#issuecomment-398063523","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/resin-io/etcher","title":"resin-io/etcher","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/resin-io/etcher"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jhermsmeier in #2392: @SwiftHackerz can I ask where you're downloading Etcher from?"}],"action":{"name":"View Issue","url":"https://github.com/resin-io/etcher/issues/2392#issuecomment-398063523"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [resin-io/etcher] Cannot Install Etcher (#2392)",
"sections": [
{
"text": "",
"activityTitle": "**Jonas Hermsmeier**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jhermsmeier",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"resin-io/etcher\",\n\"issueId\": 2392,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"resin-io/etcher\",\n\"issueId\": 2392\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/resin-io/etcher/issues/2392#issuecomment-398063523"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 346525028\n}"
}
],
"themeColor": "26292E"
}
