### ISSUE TITLE
Etcher doesn’t open on Windows 10

### ISSUE THREAD

**Issue by 9999years** [resin-io/etcher#2409]
- **Etcher version:** 1.4.4
- **Operating system and architecture:** Windows 10 x64

When I run Etcher from the start menu or by clicking the .exe directly, no window appears, although a process is started which lingers around until I kill it manually.

Applies to both portable and standard builds. Tried launching as administrator and as user.

**Comment by lurch** [comment]
Duplicate of #1866 ?

**Comment by jhermsmeier** [comment]
Duplicate of #1866
