### ISSUE TITLE
usb drive not recognizable after etcher

### ISSUE THREAD

**Issue by revzim** [resin-io/etcher#2414]
- **Etcher version:** 1.4.4
- **Operating system and architecture:** macOS High Sierra
- **Image flashed:** Ubuntu desktop iso
- **Do you see any meaningful error information in the DevTools?** After etcher "completed," an error popped up that stated, "The disk you inserted was not readable by this computer." Now my usb cannot be read by my computer and I cannot format or do anything with the USB drive. No error in devtools either... Interesting.

Fri Jul 06 2018 00:34:39 GMT-0400 (EDT) Verifying 1 devices, 74% at 11.2 MB/s (total 11.2 MB/s) eta in 43.73684210526316s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:39 GMT-0400 (EDT) Verifying 1 devices, 74% at 11.2 MB/s (total 11.2 MB/s) eta in 43.29625292740047s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:40 GMT-0400 (EDT) Verifying 1 devices, 75% at 11.2 MB/s (total 11.2 MB/s) eta in 42.89906103286385s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:40 GMT-0400 (EDT) Verifying 1 devices, 75% at 11.2 MB/s (total 11.2 MB/s) eta in 42.40023474178403s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:41 GMT-0400 (EDT) Verifying 1 devices, 75% at 11.2 MB/s (total 11.2 MB/s) eta in 41.95652173913044s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:41 GMT-0400 (EDT) Verifying 1 devices, 75% at 11.1 MB/s (total 11.1 MB/s) eta in 41.51176470588236s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:42 GMT-0400 (EDT) Verifying 1 devices, 76% at 11.1 MB/s (total 11.1 MB/s) eta in 41.10849056603774s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:42 GMT-0400 (EDT) Verifying 1 devices, 76% at 11.1 MB/s (total 11.1 MB/s) eta in 40.60731132075472s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:43 GMT-0400 (EDT) Verifying 1 devices, 76% at 11.1 MB/s (total 11.1 MB/s) eta in 40.153482880755604s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:43 GMT-0400 (EDT) Verifying 1 devices, 77% at 11.1 MB/s (total 11.1 MB/s) eta in 39.645808736717825s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:44 GMT-0400 (EDT) Verifying 1 devices, 77% at 11.1 MB/s (total 11.1 MB/s) eta in 39.14403778040141s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:44 GMT-0400 (EDT) Verifying 1 devices, 77% at 11.1 MB/s (total 11.1 MB/s) eta in 38.590801886792455s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:45 GMT-0400 (EDT) Verifying 1 devices, 77% at 11.1 MB/s (total 11.1 MB/s) eta in 38s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:45 GMT-0400 (EDT) Verifying 1 devices, 78% at 11.1 MB/s (total 11.1 MB/s) eta in 37.49411764705882s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:46 GMT-0400 (EDT) Verifying 1 devices, 78% at 11.2 MB/s (total 11.2 MB/s) eta in 36.950646298472385s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:46 GMT-0400 (EDT) Verifying 1 devices, 78% at 11.2 MB/s (total 11.2 MB/s) eta in 36.40258215962441s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:47 GMT-0400 (EDT) Verifying 1 devices, 79% at 11.2 MB/s (total 11.2 MB/s) eta in 35.81967213114754s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:47 GMT-0400 (EDT) Verifying 1 devices, 79% at 11.2 MB/s (total 11.2 MB/s) eta in 35.322014051522245s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:48 GMT-0400 (EDT) Verifying 1 devices, 79% at 11.2 MB/s (total 11.2 MB/s) eta in 34.81850117096018s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:48 GMT-0400 (EDT) Verifying 1 devices, 80% at 11.2 MB/s (total 11.2 MB/s) eta in 34.280701754385966s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:49 GMT-0400 (EDT) Verifying 1 devices, 80% at 11.2 MB/s (total 11.2 MB/s) eta in 33.829039812646364s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:49 GMT-0400 (EDT) Verifying 1 devices, 80% at 11.2 MB/s (total 11.2 MB/s) eta in 33.3704572098476s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:50 GMT-0400 (EDT) Verifying 1 devices, 80% at 11.2 MB/s (total 11.2 MB/s) eta in 32.916666666666664s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:50 GMT-0400 (EDT) Verifying 1 devices, 81% at 11.2 MB/s (total 11.2 MB/s) eta in 32.45593419506463s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:51 GMT-0400 (EDT) Verifying 1 devices, 81% at 11.1 MB/s (total 11.1 MB/s) eta in 31.99411764705882s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:51 GMT-0400 (EDT) Verifying 1 devices, 81% at 11.1 MB/s (total 11.1 MB/s) eta in 31.5s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:52 GMT-0400 (EDT) Verifying 1 devices, 82% at 11.1 MB/s (total 11.1 MB/s) eta in 31.07311320754717s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:52 GMT-0400 (EDT) Verifying 1 devices, 82% at 11.1 MB/s (total 11.1 MB/s) eta in 30.57193396226415s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:53 GMT-0400 (EDT) Verifying 1 devices, 82% at 11.1 MB/s (total 11.1 MB/s) eta in 30.06485849056604s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:53 GMT-0400 (EDT) Verifying 1 devices, 82% at 11.1 MB/s (total 11.1 MB/s) eta in 29.56367924528302s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:54 GMT-0400 (EDT) Verifying 1 devices, 83% at 11.1 MB/s (total 11.1 MB/s) eta in 29.056603773584907s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:54 GMT-0400 (EDT) Verifying 1 devices, 83% at 11.1 MB/s (total 11.1 MB/s) eta in 28.488235294117647s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:55 GMT-0400 (EDT) Verifying 1 devices, 83% at 11.1 MB/s (total 11.1 MB/s) eta in 27.98235294117647s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:55 GMT-0400 (EDT) Verifying 1 devices, 84% at 11.2 MB/s (total 11.2 MB/s) eta in 27.411971830985916s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:56 GMT-0400 (EDT) Verifying 1 devices, 84% at 11.2 MB/s (total 11.2 MB/s) eta in 26.881594372801878s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:56 GMT-0400 (EDT) Verifying 1 devices, 84% at 11.2 MB/s (total 11.2 MB/s) eta in 26.38335287221571s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:57 GMT-0400 (EDT) Verifying 1 devices, 84% at 11.2 MB/s (total 11.2 MB/s) eta in 25.84894613583138s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:57 GMT-0400 (EDT) Verifying 1 devices, 85% at 11.2 MB/s (total 11.2 MB/s) eta in 25.321637426900583s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:58 GMT-0400 (EDT) Verifying 1 devices, 85% at 11.2 MB/s (total 11.2 MB/s) eta in 24.82456140350877s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:58 GMT-0400 (EDT) Verifying 1 devices, 85% at 11.2 MB/s (total 11.2 MB/s) eta in 24.355971896955502s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:59 GMT-0400 (EDT) Verifying 1 devices, 86% at 11.2 MB/s (total 11.2 MB/s) eta in 23.852459016393443s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:34:59 GMT-0400 (EDT) Verifying 1 devices, 86% at 11.2 MB/s (total 11.2 MB/s) eta in 23.34894613583138s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:00 GMT-0400 (EDT) Verifying 1 devices, 86% at 11.2 MB/s (total 11.2 MB/s) eta in 22.830409356725145s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:00 GMT-0400 (EDT) Verifying 1 devices, 86% at 11.2 MB/s (total 11.2 MB/s) eta in 22.3915592028136s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:01 GMT-0400 (EDT) Verifying 1 devices, 87% at 11.2 MB/s (total 11.2 MB/s) eta in 21.950646298472385s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:01 GMT-0400 (EDT) Verifying 1 devices, 87% at 11.1 MB/s (total 11.1 MB/s) eta in 21.476470588235294s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:02 GMT-0400 (EDT) Verifying 1 devices, 87% at 11.1 MB/s (total 11.1 MB/s) eta in 20.976470588235294s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:02 GMT-0400 (EDT) Verifying 1 devices, 88% at 11.1 MB/s (total 11.1 MB/s) eta in 20.500588928150766s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:03 GMT-0400 (EDT) Verifying 1 devices, 88% at 11.1 MB/s (total 11.1 MB/s) eta in 19.994110718492344s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:03 GMT-0400 (EDT) Verifying 1 devices, 88% at 11.1 MB/s (total 11.1 MB/s) eta in 19.470588235294116s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:04 GMT-0400 (EDT) Verifying 1 devices, 89% at 11.1 MB/s (total 11.1 MB/s) eta in 18.970588235294116s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:04 GMT-0400 (EDT) Verifying 1 devices, 89% at 11.1 MB/s (total 11.1 MB/s) eta in 18.48645465253239s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:05 GMT-0400 (EDT) Verifying 1 devices, 89% at 11.1 MB/s (total 11.1 MB/s) eta in 17.97997644287397s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:05 GMT-0400 (EDT) Verifying 1 devices, 89% at 11.2 MB/s (total 11.2 MB/s) eta in 17.438307873090483s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:06 GMT-0400 (EDT) Verifying 1 devices, 90% at 11.2 MB/s (total 11.2 MB/s) eta in 16.91901408450704s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:06 GMT-0400 (EDT) Verifying 1 devices, 90% at 11.2 MB/s (total 11.2 MB/s) eta in 16.400937866354045s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:07 GMT-0400 (EDT) Verifying 1 devices, 90% at 11.2 MB/s (total 11.2 MB/s) eta in 15.8968347010551s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:07 GMT-0400 (EDT) Verifying 1 devices, 91% at 11.2 MB/s (total 11.2 MB/s) eta in 15.380562060889929s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:08 GMT-0400 (EDT) Verifying 1 devices, 91% at 11.2 MB/s (total 11.2 MB/s) eta in 14.882903981264636s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:08 GMT-0400 (EDT) Verifying 1 devices, 91% at 11.2 MB/s (total 11.2 MB/s) eta in 14.396248534583822s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:09 GMT-0400 (EDT) Verifying 1 devices, 91% at 11.2 MB/s (total 11.2 MB/s) eta in 13.881733021077283s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:09 GMT-0400 (EDT) Verifying 1 devices, 92% at 11.2 MB/s (total 11.2 MB/s) eta in 13.389929742388757s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:10 GMT-0400 (EDT) Verifying 1 devices, 92% at 11.2 MB/s (total 11.2 MB/s) eta in 12.922535211267606s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:10 GMT-0400 (EDT) Verifying 1 devices, 92% at 11.2 MB/s (total 11.2 MB/s) eta in 12.444183313748532s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:11 GMT-0400 (EDT) Verifying 1 devices, 93% at 11.1 MB/s (total 11.1 MB/s) eta in 11.964705882352941s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:11 GMT-0400 (EDT) Verifying 1 devices, 93% at 11.1 MB/s (total 11.1 MB/s) eta in 11.478209658421672s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:12 GMT-0400 (EDT) Verifying 1 devices, 93% at 11.1 MB/s (total 11.1 MB/s) eta in 10.983510011778563s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:12 GMT-0400 (EDT) Verifying 1 devices, 93% at 11.1 MB/s (total 11.1 MB/s) eta in 10.50177095631641s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:13 GMT-0400 (EDT) Verifying 1 devices, 94% at 11.1 MB/s (total 11.1 MB/s) eta in 9.98820754716981s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:13 GMT-0400 (EDT) Verifying 1 devices, 94% at 11.1 MB/s (total 11.1 MB/s) eta in 9.481132075471699s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:14 GMT-0400 (EDT) Verifying 1 devices, 94% at 11.1 MB/s (total 11.1 MB/s) eta in 8.97995283018868s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:14 GMT-0400 (EDT) Verifying 1 devices, 95% at 11.1 MB/s (total 11.1 MB/s) eta in 8.472877358490566s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:15 GMT-0400 (EDT) Verifying 1 devices, 95% at 11.1 MB/s (total 11.1 MB/s) eta in 7.952941176470588s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:15 GMT-0400 (EDT) Verifying 1 devices, 95% at 11.1 MB/s (total 11.1 MB/s) eta in 7.447058823529412s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:16 GMT-0400 (EDT) Verifying 1 devices, 95% at 11.2 MB/s (total 11.2 MB/s) eta in 6.93075117370892s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:16 GMT-0400 (EDT) Verifying 1 devices, 96% at 11.2 MB/s (total 11.2 MB/s) eta in 6.41852286049238s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:17 GMT-0400 (EDT) Verifying 1 devices, 96% at 11.2 MB/s (total 11.2 MB/s) eta in 5.907494145199063s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:17 GMT-0400 (EDT) Verifying 1 devices, 96% at 11.2 MB/s (total 11.2 MB/s) eta in 5.397196261682243s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:18 GMT-0400 (EDT) Verifying 1 devices, 97% at 11.2 MB/s (total 11.2 MB/s) eta in 4.900584795321637s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:18 GMT-0400 (EDT) Verifying 1 devices, 97% at 11.2 MB/s (total 11.2 MB/s) eta in 4.404205607476635s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:19 GMT-0400 (EDT) Verifying 1 devices, 97% at 11.2 MB/s (total 11.2 MB/s) eta in 3.916861826697892s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:19 GMT-0400 (EDT) Verifying 1 devices, 98% at 11.2 MB/s (total 11.2 MB/s) eta in 3.4250585480093676s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:20 GMT-0400 (EDT) Verifying 1 devices, 98% at 11.2 MB/s (total 11.2 MB/s) eta in 2.9401408450704225s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:20 GMT-0400 (EDT) Verifying 1 devices, 98% at 11.2 MB/s (total 11.2 MB/s) eta in 2.4441833137485314s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:21 GMT-0400 (EDT) Verifying 1 devices, 98% at 11.1 MB/s (total 11.1 MB/s) eta in 1.9529411764705882s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:21 GMT-0400 (EDT) Verifying 1 devices, 99% at 11.1 MB/s (total 11.1 MB/s) eta in 1.4546525323910482s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:22 GMT-0400 (EDT) Verifying 1 devices, 99% at 11.1 MB/s (total 11.1 MB/s) eta in 0.9610849056603774s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:22 GMT-0400 (EDT) Verifying 1 devices, 99% at 11.1 MB/s (total 11.1 MB/s) eta in 0.4609929078014185s with 0 failed devices
gui.js:105081 Fri Jul 06 2018 00:35:23 GMT-0400 (EDT) Flashing 0 devices, 100% at 0 MB/s (total 0 MB/s) eta in 0s with 0 failed devices
gui.js:105081 Finish: 1921843200
gui.js:105081 Flash results Objectcancelled: falseresults: ObjectbytesWritten: 1921843200checksum: Objectsha512: "a1f9a1b348d0ddf44120d536e596959eed3fe07a92c3aded3775c467569f26ebb671b9786ea1d03c689e99f7d5c38ef8e95172355e8071dac0aee1b5fb54a32c"__proto__: Objectdevices: Objectfailed: 0successful: 1__proto__: Objecterrors: Array(0)length: 0__proto__: Array(0)__proto__: Object__proto__: Object
gui.js:105081 Terminating IPC server
gui.js:105081 Fri Jul 06 2018 00:35:25 GMT-0400 (EDT) Done ({"image":"/Users/azim/Downloads/ubuntu-18.04-desktop-amd64.iso","drives":["/dev/disk2"],"uuid":"6c71edea-d5f9-4210-8a9d-3cd48540d050","unmountOnSuccess":true,"validateWriteOnSuccess":true})

**Comment by lurch** [comment]
https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#recovering-broken-drives
