### ISSUE TITLE
How to Flash mac OS image to my Local HDD drives?

### ISSUE THREAD

**Issue by lpflhh** [resin-io/etcher#2427]
Hello,
I want flash mac OS image （.dmg） to my HDD drives,Can the next version add this feature?
thanks very much!

**Comment by jhermsmeier** [comment]
Hey there, you can already do that, but need to enable "Unsafe mode" in the settings. Be aware that doing so will make previous data on that drive unrecoverable, so please be very sure you know what you're doing.
