### ISSUE TITLE
can etcher be used to copy the image to a blank dvd-r disc

### ISSUE THREAD

**Issue by linuxfartbox** [resin-io/etcher#2432]
- **Etcher version:**  version (1.4.4) 
- **Operating system and architecture:** Linux Mint 18.3 Sylvia Mate,  x86_64 GNU/Linux
- **Image flashed:** kali-linux-mate-2018.2-amd64.iso
- **Do you see any meaningful error information in the DevTools?**

**Comment by lurch** [comment]
Nope, that needs dedicated DVD-writing software. Etcher can only write to block-devices (USB sticks, HDDs, SD cards, etc.)

**Comment by jhermsmeier** [comment]
Duplicate of https://github.com/resin-io/etcher/issues/2086

**Comment by linuxfartbox** [comment]
thanks
