### ISSUE TITLE
Ubuntu 18.04 cannot receive the resin.io apt keys

### ISSUE THREAD

**Issue by softweyr** [resin-io/etcher#2437]
- **Etcher version:** 
$ uname -a
Linux uninspiron 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
Executing: /tmp/apt-key-gpghome.PXDwM3sm05/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
gpg: keyserver receive failed: Server indicated a failure

**Comment by softweyr** [comment]
Oh, ugh, never mind, yet another corporate web filter failure.

**Comment by jhermsmeier** [comment]
Alright, closing this then :)
