### ISSUE TITLE
Drives always locked in Ubuntu, but not in windows

### ISSUE THREAD

**Issue by onokje** [resin-io/etcher#2446]
- **Etcher version: Version = 1.4.4, Type = appimage** 
- **Operating system and architecture: Ubuntu 16, x64** 
- **Image flashed: Any** 
- **Do you see any meaningful error information in the DevTools? No** 

I can't use this tool in Ubuntu. Any SD card I try, or any image, it always says the SD card is Locked in the Select drive modal (the red "Locked" label). I checked if the drive is physically locked: It is not. If i switch to windows 10 on the same PC (I have dualboot) and use the windows version, it works fine. So i have a workaround for myself (switch to Windows), but it is still kinda annoying.

**Comment by lurch** [comment]
@jhermsmeier Another `drivelist` bug?

**Comment by jhermsmeier** [comment]
@onokje what are those SD cards formatted as? Do they only have one partition, or several? Are they automatically mounted on your Ubuntu?

**Comment by jhermsmeier** [comment]
Thanks @onokje! Let us know how it goes

**Comment by jhermsmeier** [comment]
Also, if you could post the output of running `lsblk --bytes --all --json --paths --output-all` in a terminal, that'd be very helpful!

**Comment by onokje** [comment]
The problem still exists on ubuntu 18.

output of lsblk:

`{
   "blockdevices": [
      {"name": "/dev/loop0", "kname": "/dev/loop0", "maj:min": "7:0", "fstype": "squashfs", "mountpoint": "/snap/gnome-logs/45", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "15208448", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop1", "kname": "/dev/loop1", "maj:min": "7:1", "fstype": "squashfs", "mountpoint": "/snap/gnome-characters/296", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "15462400", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop2", "kname": "/dev/loop2", "maj:min": "7:2", "fstype": "squashfs", "mountpoint": "/snap/gnome-logs/61", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "1032192", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop3", "kname": "/dev/loop3", "maj:min": "7:3", "fstype": "squashfs", "mountpoint": "/snap/gnome-3-28-1804/67", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "157184000", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop4", "kname": "/dev/loop4", "maj:min": "7:4", "fstype": "squashfs", "mountpoint": "/snap/gnome-system-monitor/100", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "3825664", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop5", "kname": "/dev/loop5", "maj:min": "7:5", "fstype": "squashfs", "mountpoint": "/snap/gtk-common-themes/1198", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "37027840", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop6", "kname": "/dev/loop6", "maj:min": "7:6", "fstype": "squashfs", "mountpoint": "/snap/core/6964", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "92733440", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop7", "kname": "/dev/loop7", "maj:min": "7:7", "fstype": "squashfs", "mountpoint": "/snap/gnome-calculator/260", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "2355200", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop8", "kname": "/dev/loop8", "maj:min": "7:8", "fstype": "squashfs", "mountpoint": "/snap/gnome-calculator/406", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "4218880", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop9", "kname": "/dev/loop9", "maj:min": "7:9", "fstype": "squashfs", "mountpoint": "/snap/gtk2-common-themes/5", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "135168", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop10", "kname": "/dev/loop10", "maj:min": "7:10", "fstype": "squashfs", "mountpoint": "/snap/gnome-3-28-1804/63", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "157184000", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop11", "kname": "/dev/loop11", "maj:min": "7:11", "fstype": "squashfs", "mountpoint": "/snap/gnome-system-monitor/95", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "3825664", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop12", "kname": "/dev/loop12", "maj:min": "7:12", "fstype": "squashfs", "mountpoint": "/snap/core18/1055", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "57016320", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop13", "kname": "/dev/loop13", "maj:min": "7:13", "fstype": "squashfs", "mountpoint": "/snap/core18/1066", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "57069568", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop14", "kname": "/dev/loop14", "maj:min": "7:14", "fstype": "squashfs", "mountpoint": "/snap/p7zip-desktop/220", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "106397696", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop15", "kname": "/dev/loop15", "maj:min": "7:15", "fstype": "squashfs", "mountpoint": "/snap/gtk2-common-themes/4", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "135168", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop16", "kname": "/dev/loop16", "maj:min": "7:16", "fstype": "squashfs", "mountpoint": "/snap/gtk-common-themes/1313", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "44879872", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop17", "kname": "/dev/loop17", "maj:min": "7:17", "fstype": "squashfs", "mountpoint": "/snap/core/7270", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "92778496", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop18", "kname": "/dev/loop18", "maj:min": "7:18", "fstype": "squashfs", "mountpoint": "/snap/skype/66", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "154406912", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop19", "kname": "/dev/loop19", "maj:min": "7:19", "fstype": "squashfs", "mountpoint": "/snap/gnome-characters/292", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "15458304", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop20", "kname": "/dev/loop20", "maj:min": "7:20", "fstype": "squashfs", "mountpoint": "/snap/gnome-3-26-1604/88", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "147501056", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop21", "kname": "/dev/loop21", "maj:min": "7:21", "fstype": "squashfs", "mountpoint": "/snap/gnome-3-26-1604/90", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "147501056", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop22", "kname": "/dev/loop22", "maj:min": "7:22", "fstype": "squashfs", "mountpoint": "/snap/p7zip-desktop/163", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "53182464", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop23", "kname": "/dev/loop23", "maj:min": "7:23", "fstype": "squashfs", "mountpoint": "/snap/gnome-calculator/352", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "4214784", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop24", "kname": "/dev/loop24", "maj:min": "7:24", "fstype": "squashfs", "mountpoint": "/snap/gnome-logs/57", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "1032192", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop25", "kname": "/dev/loop25", "maj:min": "7:25", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": null, "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/sda", "kname": "/dev/sda", "maj:min": "8:0", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": "Crucial_CT1050MX", "serial": "1631137A283A", "size": "1050214588416", "state": "running", "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "disk", "disc-aln": "0", "disc-gran": "512", "disc-max": "2147450880", "disc-zero": "0", "wsame": "0", "wwn": "0x500a0751137a283a", "rand": "0", "pkname": null, "hctl": "5:0:0:0", "tran": "sata", "subsystems": "block:scsi:pci", "rev": "R031", "vendor": "ATA     ", "zoned": "none",
         "children": [
            {"name": "/dev/sda1", "kname": "/dev/sda1", "maj:min": "8:1", "fstype": "ntfs", "mountpoint": null, "label": "Recovery", "uuid": "48D08A96D08A8A40", "parttype": "de94bba4-06d1-4d40-a16a-bfd50179d6ac", "partlabel": "Basic data partition", "partuuid": "5ed78712-79d0-4e2f-b2b1-28e64f20c260", "partflags": "0x1", "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "471859200", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "512", "disc-max": "2147450880", "disc-zero": "0", "wsame": "0", "wwn": "0x500a0751137a283a", "rand": "0", "pkname": "/dev/sda", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null, "zoned": "none"},
            {"name": "/dev/sda2", "kname": "/dev/sda2", "maj:min": "8:2", "fstype": "vfat", "mountpoint": "/boot/efi", "label": null, "uuid": "928A-BC80", "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b", "partlabel": "EFI system partition", "partuuid": "8e76d95e-9c44-41cf-9909-2b2040899f90", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "103809024", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "512", "disc-max": "2147450880", "disc-zero": "0", "wsame": "0", "wwn": "0x500a0751137a283a", "rand": "0", "pkname": "/dev/sda", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null, "zoned": "none"},
            {"name": "/dev/sda3", "kname": "/dev/sda3", "maj:min": "8:3", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": "e3c9e316-0b5c-4db8-817d-f92df00215ae", "partlabel": "Microsoft reserved partition", "partuuid": "987107a8-a7ff-4a97-ad9e-dbf219c29d14", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "16777216", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "512", "disc-max": "2147450880", "disc-zero": "0", "wsame": "0", "wwn": "0x500a0751137a283a", "rand": "0", "pkname": "/dev/sda", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null, "zoned": "none"},
            {"name": "/dev/sda4", "kname": "/dev/sda4", "maj:min": "8:4", "fstype": "ntfs", "mountpoint": null, "label": null, "uuid": "38BA9F98BA9F50EC", "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7", "partlabel": "Basic data partition", "partuuid": "a5f66177-b829-44a4-ba11-ed86e05bbb32", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "785838505984", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "512", "disc-max": "2147450880", "disc-zero": "0", "wsame": "0", "wwn": "0x500a0751137a283a", "rand": "0", "pkname": "/dev/sda", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null, "zoned": "none"},
            {"name": "/dev/sda5", "kname": "/dev/sda5", "maj:min": "8:5", "fstype": "ext4", "mountpoint": "/", "label": null, "uuid": "54b6d4d6-382b-4160-a7df-3899b0b9118d", "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4", "partlabel": null, "partuuid": "1cd1eb63-762b-492d-b4d4-0189b08ab2b7", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "246670163968", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "512", "disc-max": "2147450880", "disc-zero": "0", "wsame": "0", "wwn": "0x500a0751137a283a", "rand": "0", "pkname": "/dev/sda", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null, "zoned": "none"},
            {"name": "/dev/sda6", "kname": "/dev/sda6", "maj:min": "8:6", "fstype": "swap", "mountpoint": "[SWAP]", "label": null, "uuid": "73ebede8-5275-4b78-9844-e01e16cd6ec3", "parttype": "0657fd6d-a4ab-43c4-84e5-0933c84b4f4f", "partlabel": null, "partuuid": "eff514e4-0cd7-477a-a8c4-8953e705f56a", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "17111711744", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "512", "disc-max": "2147450880", "disc-zero": "0", "wsame": "0", "wwn": "0x500a0751137a283a", "rand": "0", "pkname": "/dev/sda", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null, "zoned": "none"}
         ]
      },
      {"name": "/dev/sdb", "kname": "/dev/sdb", "maj:min": "8:16", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "1", "hotplug": "1", "model": "STORAGE DEVICE  ", "serial": "000000000903", "size": "32010928128", "state": "running", "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "cfq", "rq-size": "128", "type": "disk", "disc-aln": "0", "disc-gran": "0", "disc-max": "0", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "1", "pkname": null, "hctl": "6:0:0:0", "tran": "usb", "subsystems": "block:scsi:usb:pci", "rev": "0903", "vendor": "Generic ", "zoned": "none",
         "children": [
            {"name": "/dev/sdb1", "kname": "/dev/sdb1", "maj:min": "8:17", "fstype": "vfat", "mountpoint": "/media/onok/9016-4EF8", "label": null, "uuid": "9016-4EF8", "parttype": "0xc", "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "1", "hotplug": "1", "model": null, "serial": null, "size": "32006733824", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "0", "disc-max": "0", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "1", "pkname": "/dev/sdb", "hctl": null, "tran": null, "subsystems": "block:scsi:usb:pci", "rev": null, "vendor": null, "zoned": "none"}
         ]
      }
   ]
}
`

**Comment by thundron** [comment]
@onokje Which version of Etcher are you running? Have you tried also with the latest available?

**Comment by onokje** [comment]
1.5.52 (AppImage)
