### ISSUE TITLE
Blank window on start

### ISSUE THREAD

**Issue by shavee** [resin-io/etcher#2456]
- Etcher version: any on Windows (tried 1.4.4 portable, 1.4.4 x64, 1.4.3 portable, 1.4.3 x64, 1.3.1 portable)
- Windows 10 x64 fully updated
- DevTools not working

Nothing more to explain... this is what it looks like:
![image](https://user-images.githubusercontent.com/42537290/44332426-50927980-a46c-11e8-9075-b9d95f9e89f6.png)

Dev tools (ctrl+shift+I) shows like this:
![image](https://user-images.githubusercontent.com/42537290/44332459-6869fd80-a46c-11e8-91b4-9c1b23f1e0fd.png)

Tried running as administrator, running from different units... always the same result.

Any clue?

**Comment by lurch** [comment]
I wonder if this is related to #1866 ?

**Comment by shavee** [comment]
SOLVED! Same problem as in #696 . My laptop was set to force NVIDIA graphics instead of integrated ones. Switch this to force integrated graphics and Etcher starts without problems.

Thanks!

**Comment by lurch** [comment]
@jhermsmeier Maybe something to add to the docs?

**Comment by koper87** [comment]
I have an AMD graphic card, so the solution up there didn't work for me. I was facing the same problem until I did change the compatibility mode to Windows Vista, in the Compatibility tab on the executable' Properties menu. 
I hope it helps.

**Comment by vanhvungve** [comment]
> I have an AMD graphic card, so the solution up there didn't work for me. I was facing the same problem until I did change the compatibility mode to Windows Vista, in the Compatibility tab on the executable' Properties menu.
> I hope it helps.

well it works

**Comment by TheOD706** [comment]
Look like Etcher use component of base browser (maybe Internet Explorer), but you all not use/update IT. I use other OS and it work.

**Comment by bpp9614** [comment]
Having same problem Windows, hp laptop. Intel HD graphics 620. Blank grey screen on running npm start.

**Comment by kodouglass** [comment]
worked when using internet explorer, failed with chrome

**Comment by poshest** [comment]
Same problem, Windows 7, Intel HD Graphics 3000. v1.5.86 seems to work in Vista compatibility mode (although etching fails), but I can't get v1.5.95 working at all.

**Comment by imarindam** [comment]
Same problem with Windows 10, AMD CPU and GPU.

**Comment by thundron** [comment]
@imarindam can you try updating the .NET framework? if that doesn't work, another thing to try is running from `C:` in case you're using the portable version.
You might also try downgrading and running with compatibility mode as previously mentioned by @poshest.
This is probably not related to Etcher itself so I wouldn't know how to proceed if none of these options work

**Comment by riccardosimo** [comment]
same here with the 1.7.9 version
