### ISSUE TITLE
Warn that Etcher deletes all files on the disk

### ISSUE THREAD

**Issue by breznak** [resin-io/etcher#2462]
Ok, I didn't read man pages or docs here, but just found my way that flashing an OS on a flashdrive means deleting all files there. 
I think there should be more proactive warning/documentation of that! Best a dialog if files are found on the selected drive. 
This esp. bites as unetbootin, the tool I've used prior did keep users files. 

Best approaches: 
1. keep files intact, as unetbootin did
2. dialog with warning if there are user files present

**Comment by lurch** [comment]
unetbootin works differently to Etcher, see #413

**Comment by heartbr0ken** [comment]
I was heartbroken by this as well. I second the kind idea of putting a warning page in the actual deployment of the program.

**Comment by breznak** [comment]
@jviotti  would you care to elaborate why you've just closed the issue? Esp. since it's data-loss related..

**Comment by jviotti** [comment]
@breznak This is not something we can easily handle from Etcher's point of view. Etcher is a byte-by-byte flasher, and is expected to wipe all the data and partition table (this is literally the core mission of Etcher).

We could show a dialog if there are files present, but this is not as simple as it sounds. You might be plugging in a drive with a file-system that is not readable in the host operating system and thus don't detect any files even though there might be some.

**Comment by breznak** [comment]
> and is expected to wipe all the data and partition table (this is literally the core mission of Etcher). 

agree and it's fine, imho just warn about it. 

> but this is not as simple as it sounds. You might be plugging in a drive with a file-system that is not readable in the host operating system and thus don't detect any files even though there might be some. 

I wouldn't bother with any file-detection code, just add a "Etcher will wipe all the files in the flash drive, continue?" to the reflash dialog and that's it. What do you think?

**Comment by jviotti** [comment]
Yeah, that might be worth considering. @thundron @konmouz ?

**Comment by AnneKir** [comment]
nice to know this was closed 2 years ago, just lost my all my files, because it was assumed I knew it would delete it.

**Comment by dennisExploring** [comment]
> @breznak This is not something we can easily handle from Etcher's point of view. Etcher is a byte-by-byte flasher, and is expected to wipe all the data and partition table (this is literally the core mission of Etcher).
> 
> We could show a dialog if there are files present, but this is not as simple as it sounds. You might be plugging in a drive with a file-system that is not readable in the host operating system and thus don't detect any files even though there might be some.

tso dissapoint lost my data

**Comment by dennisExploring** [comment]
> nice to know this was closed 2 years ago, just lost my all my files, because it was assumed I knew it would delete it.

same

**Comment by breznak** [comment]
It is a shame the issue was just closed (and never reopened), prior to discussion.. where a we found a "compromise" (it is really not that hard to print "Beware, your drive will be fully erased, all data on it will be lost!" )

**Comment by breznak** [comment]
@lurch @jviotti can you at least reopen and acknowledge the issue? So someone might care to fix it, thx

**Comment by lurch** [comment]
@breznak Neither myself nor @jviotti are working on Etcher any more. If you'd like to see this "fixed", you should probably open a new issue so that the current Etcher maintainers are able to see it.
