### ISSUE TITLE
 Image correctly FLASHED but display's  "1 Failed device" under the Flash Complete! 

### ISSUE THREAD

**Issue by Dewlistic** [resin-io/etcher#2480]
****Software Version:** Etcher version**: 1.4.4
**Target Computer:** Windows 10 Pro:** 
**File to Flash:** A .hddimg file [is] an msdos filesystem containing syslinux, a kernel, an initrd and a rootfs image. These can be written to harddisks directly and also booted on USB flash disks (write them there with dd) 
**Hardware Flashed:** SanDisk 8GB Thumb Drive Formatted for FAT32

.hddimg image files correctly FLASHED to Thumb Drive but display's  "**1 Failed device**" under the Flash Complete! message.  Mouse hover over the failure display screen shot below. 

![image](https://user-images.githubusercontent.com/43378664/45691658-a0716880-bb1e-11e8-9ba9-422618a3a10c.png)

Developer Console read out at the end of the write cycle. 

Tue Sep 18 2018 08:32:44 GMT-0500 (Central Daylight Time) Verifying 1 devices, 98% at 21.7 MB/s (total 21.7 MB/s) eta in 0.3153357531760435s with 0 failed devices
gui.js:105081 
Fail: Object
gui.js:105081 
Tue Sep 18 2018 08:32:44 GMT-0500 (Central Daylight Time) Flashing 0 devices, 100% at 0 MB/s (total 0 MB/s) eta in 0s with 1 failed devices
gui.js:105081 
Finish: 653737984  gui.js:105081

Flash results Object
gui.js:105081 
Terminating IPC server
gui.js:105081 
Tue Sep 18 2018 08:32:49 GMT-0500 (Central Daylight Time) Done ({"image":"C:\\Desktop\\Temp\\image.hddimg","drives":["\\\\.\\PhysicalDrive1"],"uuid":"78aadde8-d984-48b6-9879-407e901ee625","unmountOnSuccess":true,"validateWriteOnSuccess":true})
gui.js:105081 etcher:sdk:scanner start +3m true
gui.js:105081 
Tue Sep 18 2018 08:32:49 GMT-0500 (Central Daylight Time) Navigate ({"to":"success","from":"main"})

**Comment by thundron** [comment]
@konmouz Can we improve this? What do you think?
