### ISSUE TITLE
new repo address in README.md does not work

### ISSUE THREAD

**Issue by kurbeco** [resin-io/etcher#2492]
The change brought in with https://github.com/resin-io/etcher/commit/c3ff03054238a4973c961f7c234b6211e0857b5c points to a 404 on https://etcher.io/static/etcher-rpm.repo

It is not possible to install on Fedora using these instructions.

**Comment by lurch** [comment]
I wonder if that's because https://github.com/resin-io/etcher-homepage/pull/133 hasn't been merged yet?

**Comment by kurbeco** [comment]
Likely, yes. It's a shame there's not a way to have PRs depend on others in GitHub.

**Comment by thundron** [comment]
Should be fixed in https://github.com/resin-io/etcher-homepage/commit/e7ab84d0f297f7ccfc4fafb7eb7dc9ed05297b13 @kurbeco @lurch , check now
