### ISSUE TITLE
[Feature Request] Compute Module (usbboot) support for CLI

### ISSUE THREAD

**Issue by ball-hayden** [resin-io/etcher#2499]
- **Etcher version:** 
etcher-cli-1.4.4-darwin-x64

- **Operating system and architecture:**
darwin 64
macOS High Sierra 10.13.6
 
The CLI doesn't seem to pick up compute modules in the same way the GUI does. I'm assuming this is a feature that hasn't been baked in to etcher-cli yet?
I couldn't see an issue to confirm, so thought I would open one.

Thanks for the great project!

**Comment by jviotti** [comment]
We are re-working the CLI to be more on par with the GUI app. I'll close this for now, but keep an eye for a later CLI version!
