### ISSUE TITLE
Mojave Flashing Error

### ISSUE THREAD

**Issue by drduker** [resin-io/etcher#2500]
- **Etcher version:**  1.4.4
- **Operating system and architecture:** MacOS Mojave
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 

I'm getting this error:
Error: Command "diskutil list -plist" returned without data
    at ChildProcess.childProcess.spawn.on.on (/Applications/Etcher.app/Contents/Resources/app.asar/node_modules/drivelist/lib/diskutil.js:48:26)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

One thing to note that is different is that I installed osxfuse which shouldn't cause any problems.
I used this so that I could mount a Raspbian SD card image on my mac.

So this is what I did but it shouldn't produce the error above or interfere with the workings of etcher.  Etcher has been granted accessability under security @ privacy in Sys Prefs.

brew cask install osxfuse
brew install ext4fuse
sudo mkdir /Volumes/rpi
sudo ext4fuse /dev/disk2s2 /Volumes/rpi -o allow_other
sudo cp /Volumes/rpi/home/pi/Pictures/* /Users/me/work/raspi/Pix/

**Comment by jviotti** [comment]
Closing as duplicate :)
