### ISSUE TITLE
Implement parallel writes

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#267]
This is a big feature that would allow Etcher to be able to stream the same image to multiple drives at the same time. This feature should be implemented by extending the already existing `etcher-image-write` NPM module. The module currently accepts the path to a drive device as an argument to the main function. If the user passes an array of drives, the multi-writer logic should come in.

Some of the challenges for this task are: 
- Cross platform support.
- Validating the drives at the moment the writing starts.
- Handling validation correctly for all of them (there are some quirks to make validation work in certain operating systems, like in OS X, where we have to use OS X specific frameworks to prevent the drives from being mounted right when the flash ends, so the operating system doesn’t write files like .DS_Store that messes up the checksum).
- Handling error conditions correctly (e.g: if a certain drive fails, the rest should continue).
- Making sure the whole stream is streamed to all devices (e.g: no data is lost because it has been piped to another drive).
- Imposing a reasonable limit of drives that can be written at the same time, depending on the capabilities of the operating system to prevent potential kernel panics, etc. If a user tries to write to more images than he should, we should make of use of a queue.

The module returns an EventEmitter instance which emits state information. When multiple writings are taking place, the emitted events could have a property containing the drive they correspond to.

It's important that this feature contains extensive end to end tests.

This project **should not contain native addons by any means**, since it's used by other projects that are installed by end users without necessarily having a toolchain in place.

**Comment by lurch** [comment]
And I guess this will also need to cope with some of the drives being written to having much slower write speeds than others (e.g. a Class4 SD card in a USB2 cardreader vs. a Class10 SD card in a USB3 cardreader). So perhaps there needs to be separate decompression queues for each drive, rather than trying to stream the same decompressed data to each of the drives? Unless of course you're happy for the whole process to just run at the speed of the slowest drive.

**Comment by jviotti** [comment]
Hey there,

That's spot on. We've experimented with opening different file
descriptors from the input image, and handling decompression separately,
which helps avoiding faster drives being bottlenecked by slower drives,
however that also means that when uncompressing many multiple streams
(think >20), the CPU usage rises a lot, and we're basically duplicating
computation.

Another thing we found out is that performing much I/O on a single
NodeJS process (even with different file descriptor) slows things down a
lot, given the single-threaded nature of NodeJS. Seems like the way to
go is to spawn multiple NodeJS processes.

On Thu, Sep 29, 2016 at 05:30:10AM -0700, Andrew Scheller wrote:
> And I guess this will also need to cope with some of the drives being written to having much slower write speeds than others (e.g. a Class4 SD card in a USB2 cardreader vs. a Class10 SD card in a USB3 cardreader). So perhaps there needs to be separate decompression queues for each drive, rather than trying to stream the same decompressed data to each of the drives? Unless of course you're happy for the whole process to just run at the speed of the slowest drive.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io/etcher/issues/267#issuecomment-250452357

-- 
Juan Cruz Viotti
Software Engineer

**Comment by lurch** [comment]
Yeah, and I guess by running all-drives at the speed of the slowest drive, you only need a single progress bar, rather than separate progress bars for each drive ;-)

**Comment by alexandrosm** [comment]
@jviotti I think we can push this off the v1 release.

**Comment by jviotti** [comment]
Done!

**Comment by jviotti** [comment]
Lets try using web workers with node integration for this: https://github.com/electron/electron/pull/8852

**Comment by jhermsmeier** [comment]
Resolved by #2124

**Comment by unphased** [comment]
I've flashed about 20 cards now and I have noticed that the time taken more or less scales linearly with the transfer speed of one card. e.g. if I have 3 cards that are independently capable of flashing @21MB/s, flashing 3 of them simultaneously has them proceed at almost exactly 7MB/s, making it so that I have to wait 3 times as long for the batch. Now, this is a process improvement, however I am confused as to why there is no speedup as you would see if you just ran concurrent `dd`s on multiple drives. 

This is using a MacBook with multiple usb-c to sd card adapters.

**Comment by sonttran** [comment]
Same issue, same setup with @unphased on **Etcher Version 1.5.100.** Any way to improve speed to full in parrallel, @jviotti ? That would be great.

> I've flashed about 20 cards now and I have noticed that the time taken more or less scales linearly with the transfer speed of one card. e.g. if I have 3 cards that are independently capable of flashing @21MB/s, flashing 3 of them simultaneously has them proceed at almost exactly 7MB/s, making it so that I have to wait 3 times as long for the batch. Now, this is a process improvement and already a big win, however I am confused as to why there is no speedup as you would see if you just ran concurrent `dd`s on multiple drives. The reason I use etcher is so I can avoid building a `dd` runner and figuring out how to properly verify a disk, but this seems... not ideal.
> 
> This is using a MacBook with multiple usb-c to sd card adapters.

**Comment by socks415** [comment]
I know this is old, but it's 2025 and I'm on a macbook air m2 with the latest etcher and experiencing the same thing trying to flash multiple cm4s at the same time.  one cm4 flashes at roughly 5.7mb/s. 3 flashes at about 1.9mb/s. it's completely linear.  It's also very unstable and fails to successfully complete often when flashing more than one at a time
