### ISSUE TITLE
Normalise image open dialog when running as root in OS X

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#287]
The open dialog from Etcher differs from other applications (like missing Favourites) given that Etcher is ran as root.

**Comment by alexandrosm** [comment]
Could Etcher start a non-root sub-process to select the file?

**Comment by jviotti** [comment]
@alexandrosm The problem is that once we package the application, the "Electron" binary is locked down to running a certain application (the one it has been packaged for), so if we want to fork a child process, we can't have Electron run it (e.g: we should make assumptions like NodeJS/Electron already being installed on the system). This same error applies when only asking for elevation on the burn phase.

We could maybe try having the application's entry point react differently to certain command line arguments, but then its also a pain to communicate between the processes correctly, and sounds like a mess (which I'd like to avoid).
