### ISSUE TITLE
Improve UX when attempting to re-select a drive

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#296]
If there is a single connected drive, it gets auto-selected. If you then attempt to change it, the button will appear for some milliseconds, and the selection will be made again automatically since that's the only connected drive.

We should probably allow the user to open the drive selector modal in this case, even if there is only one drive.

**Comment by alexandrosm** [comment]
@jviotti I think we should have the "change" link there (not have the name clickable) and open the modal when it's clicked.
