### ISSUE TITLE
Create an appimage Linux package for Etcher

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#323]
http://appimage.org

**Comment by probonopd** [comment]
Done, can be downloaded from https://bintray.com/probono/AppImages/Etcher/view#files. 
See this [Recipe](https://github.com/probonopd/AppImages/blob/master/recipes/etcher/Recipe) for how it was produced. It would be nice if this project would provide AppImages for all architectures (Intel 64-bit, Intel 32-bit, ARM) natively.

**Comment by jviotti** [comment]
@probonopd Thank you very much, you're amazing! :D I'll give this a try very soon, and will import your script to our current `Makefile`.
