### ISSUE TITLE
Support for compressed files

### ISSUE THREAD

**Issue by kkaiser1952** [resin-io/etcher#325]
When I burn the SD to a hard drive I generally save it as .GZ for space reasons. It would be great if Etcher recognized these and could use them to burn it back to an SD.

**Comment by jviotti** [comment]
Hi @kkaiser1952 ,

So you mean Etcher should be able to burn `image.img.gz` or `image.iso.gz` right? If so, I think this is a good addition, but I wonder how this will plan with the fact that Etcher currently writes ZIPs that containing a single image file inside, but are not necessarily a "zipped" single file.

I think checking the extension should be a good enough clue.

**Comment by kkaiser1952** [comment]
Well if what you are saying is to let Etcher open a .GZ file from my desktop and burn a SD card with it then yes, thats what I mean.

**Comment by noglitch** [comment]
@jviotti I've just tried Etcher and it seems fantastic for what we put in place with our board SD images.
But while you are at it, I would also suggest to add .bz2 images as well.
In fact we produce .img.bz2 images for SD card right now: http://www.at91.com/linux4sam/bin/view/Linux4SAM/Sama5d2XplainedMainPage#Demo_archives

To write them on a Windows platform, we advice users to use the Rawrite32 tool as it handles such a file format...

Thanks, bye.

**Comment by jviotti** [comment]
@noglitch Thanks for the suggestion! I edited the title to include `.bz2` support.

**Comment by RobertCNelson** [comment]
@jviotti fantastic tool, if you include *.img.xz files beagleboard.org can switch too... ;)

**Comment by jviotti** [comment]
@RobertCNelson Thanks a lot! Taking notes :)

***

To summarise:

- [ ] Support for `.gz`
- [ ] Support for `.bz2`
- [ ] Support for `.7z`
- [ ] Support for `.xz`

**Comment by jviotti** [comment]
Hi @RobertCNelson ,

I've just published v1.0.0-beta.5 with XZ support. Let us know what you think!

**Comment by jmark1m** [comment]
XZ support is great but please don't stop there.  The GZ support is helpful because GZ decompresses so much faster the XZ.  
http://catchchallenger.first-world.info/wiki/Quick_Benchmark:_Gzip_vs_Bzip2_vs_LZMA_vs_XZ_vs_LZ4_vs_LZO

**Comment by jviotti** [comment]
Hi @jmark1m ,

Definitely, we'll provide support for all compression formats discussed above. We're currently prioritising auto-updating functionality, and we'll probably get all the formats out in a row afterwards.

**Comment by jviotti** [comment]
Sorry for the huge delay on this issue, I'm finally allocating some time to finish the remaining compression formats. I just PRed GZ support, and will be looking forward to PR bzip2 support as well today.

**Comment by noglitch** [comment]
Hi

I've just tested the xz and bz2 image writers with 1.0.0-beta7 version and:
- xz image flasher works great
- I can't use the .bz2 format:
  * I can't select a file with this format unless there is a file with the same name but a .zip extension in the directory
  * when I select the img.bz2 file, the .zip file is presented instead in the GUI, just underneath the "select image icon"
  * when I try to start flashing... it doesn't go further with sometimes a window saying "an error occurred". Note, when etcher fails like this, I have big difficulties to actually kill it...

(I run it from Linux Ubuntu 16.04)

Hope that it can help, Bye,

**Comment by jviotti** [comment]
Hi @noglitch ,

Thanks for reporting this! It seems that you're hitting this error: https://github.com/regular/unbzip2-stream/issues/7 from one of the dependencies we're using. I'll try to allocate some time to work myself on it!

**Comment by jviotti** [comment]
Hi @noglitch ,

Turns out the bz2 selection issue was an Electron bug with the open dialog on GNU/Linux (see https://github.com/electron/electron/issues/6305), which was fixed in the latests versions!

**Comment by jviotti** [comment]
Hi @noglitch ,

I'm happy to announce the bz2 issue you've experienced has just been fixed in the bz2 implementation we're using (se https://github.com/resin-io-modules/etcher-image-stream/pull/37), and it's coming on the next release!

**Comment by mpvader** [comment]
Hi, running Etcher 1.0.0.0-rc4, I get this error:

![image](https://cloud.githubusercontent.com/assets/5200296/25453904/fa7fff52-2aca-11e7-96ea-d3db64294680.png)

But opening the same file in 7zip works fine.

Running Windows 8.1 Pro.

**Comment by jhermsmeier** [comment]
Hey @mpvader, that's because Etcher currently checks the image extension – in this case `.rpi-sdimg`, and bails out on that because it's not mapped as a known format.
We're currently working on making it fall back to treating anything unknown as if it had an `.img` extension – so, renaming your file to `venus-image-rapsberrypi2.img.bz2` should do the trick for now.

**Comment by mpvader** [comment]
Hi @jhermsmeier, thank you for the fast response. Should it just compare the most right part? So as long as it ends in .bz2 it's fine?

These 'cascading' extensions are quite common for images and such.

**Comment by mpvader** [comment]
I meant shouldn't

**Comment by mpvader** [comment]
And, just to be clear: I'd expect etcher to unzip the .bz2 file, and burn its contents. Not burn the zipped file.

**Comment by jhermsmeier** [comment]
@mpvader well, what it basically does is look at the base extension (i.e. `.bz2` here), and then checks if it knows how to deal with the thing that has been compressed (in this case the next extension, `.rpi-sdimg`) – so what comes before the `.bz2` does factor into how Etcher treats it.

> And, just to be clear: I'd expect etcher to unzip the .bz2 file, and burn its contents. Not burn the zipped file.

Yup, that's exactly what it does (unzip & flash the contained image)

**Comment by mpvader** [comment]
ahh.. thanks. Understood! looking forward to your fix then :)

**Comment by lurch** [comment]
@jhermsmeier Was this fixed by #1363 ?

**Comment by jhermsmeier** [comment]
Only partially – there's another check in the GUI, which won't let you select unrecognised images – working on fixing that now.

**Comment by lurch** [comment]
But presumably that GUI-check will still allow @mpvader 's `venus-image-rapsberrypi2.rpi-sdimg.bz2` file to be selected?

**Comment by jhermsmeier** [comment]
@lurch oh yes, right, that should work already now
