### ISSUE TITLE
UI scaling issue when screen resolution changed

### ISSUE THREAD

**Issue by geomic** [resin-io/etcher#328]
On plugging (and then unplugging) an external monitor which forces a change in screen resolution, the UI is distorted/scaled per the attached image.
![screenshot 2016-04-15 20 56 13](https://cloud.githubusercontent.com/assets/163444/14570427/d2f3e0e4-034c-11e6-8954-d525a63c494c.png)

**Comment by jviotti** [comment]
Hi @geomic,

This sounds more like an Electron issue. I'd encourage you to open a ticket there a link back here. Anyway, we might be able to provide a workaround by forcing the size on focus/unfocus events.

**Comment by jviotti** [comment]
Seems to be fixed in the newest Electron versions. We'll re-open if it ever happens again.
