### ISSUE TITLE
Add as snap package in Ubuntu

### ISSUE THREAD

**Issue by ericoporto** [resin-io/etcher#415]
Just a thought. It's ridiculously easy to pack.

**Comment by jviotti** [comment]
This is actually something we've been thinking about, so thanks for the reminder. I've been skimming through the Ubuntu Developer Portal documentation, and will be looking forward to give it a go soon.

**Comment by jviotti** [comment]
I'm closing this since after some internal discussion, we decided that a Snappy package is not beneficial for us over AppImages, at least for the time being.

**Comment by sidahmed-malaoui** [comment]
It would much easier to install if you add it as a snap package.

**Comment by Jacalz** [comment]
Yeah I would love to get etcher as a snap image since it would update it self and work across most Linux distros 👍

**Comment by Feichtmeier** [comment]
I would also love to install it as a snap package. Many great companies have joined the snap band waggon. Including Microsoft with skype and vscode, spotify and intellij with all their IDEs.
Snaps are greatly included in the gnome-software app which comes preinstalled on many distros. They even promote snaps which are new so people become interested and install it.

**Comment by DarkLite1** [comment]
+1 for snap package

**Comment by NatoBoram** [comment]
> We decided that a Snappy package is not beneficial for us over AppImages
> https://github.com/resin-io/etcher/issues/415#issuecomment-244827814

Can we have more details on that?

**Comment by MeRuslan** [comment]
+1 for snap

**Comment by jviotti** [comment]
Sounds interesting! I remember I hit various issues when trying to build a Snap for Etcher some time ago, but we can definitely revisit it. @thundron is currently the maintainer of Etcher, so he can take this forward. 

@thundron Looks like @Mikerr1111 has an Etcher fork with some initial setup, so maybe you can coordinate the contribution?

**Comment by aurelijusrozenas** [comment]
So, maybe reopen issue? ;)

**Comment by armintelker** [comment]
Please reopen this. 
Your app as a snap package would make my/our life so much easier. 
I am switching pretty often between multiple linux distributions for testing. Snap makes the switch easier and my install script is much more readable since it is not depending anymore on so much different package managers. Your app is one of my last apps that is not published via snap. 

As a small motivation I am sponsoring a sixpack of beer, coke or a beverage of choice for successfully publishing a snap package into the snap store.

**Comment by HattinGokbori87** [comment]
I use Etcher everyday for my work (Thanks!!). I also like to see it as a snap if doing so doesn't increase pressure  on devs. It's not a top priority as Etcher is already available at deb.etcher.io but many end-users prefer snaps for different reasons (auto updates, delta updates, not having to add another repository which slows down update checking etc).

**Comment by Jacalz** [comment]
> I use Etcher everyday for my work (Thanks!!). I also like to see it as a snap if doing so doesn't increase pressure on devs. It's not a top priority as Etcher is already available at deb.etcher.io but many end-users prefer snaps for different reasons (auto updates, delta updates, not having to add another repository which slows down update checking etc).

Not to mention the fact that far from everybody uses Ubuntu or Debian. We are a lot of users that have snap enabled didstros like Solus, Manjaro and so on. It’s not just about easy updates. A well set up snap is also in theory more secure than a regular old package file...

**Comment by Jacalz** [comment]
If snap isn’t your thing, go with Flatpak on Flathub instead. It has pretty much all the good points of snap while having better desktop integration, it is available on more distorts and it is fully open source compared to snap. Probably a better alternative to be quite honest 👍

**Comment by lurch** [comment]
Obligatory XKCD link: https://xkcd.com/927/
:wink:

**Comment by the-spyke** [comment]
Please reconsider adding a snap package.

> Snappy package is not beneficial for us over AppImages

Snap gives users at least easy updates and free discoverability for you in the Snap Store.

**Comment by lurch** [comment]
#2019 (and https://github.com/flathub/flathub/pull/1363 ) says that it was impossible to get Etcher packaged as a "flatpak" because of the low-level permissions Etcher requires in order to be able to write to disks at the block-level. I wonder if the same thing might affect "snap" packaging? :man_shrugging:

**Comment by the-spyke** [comment]
@lurch It may be impossible yet, because of sandbox-first approach chosen for snap/flatpack. But you need to try `classic` confinement with snap first and open a ticket on Snapcraft if it isn't enough, so snap developers will be aware of the issue and make a plug/portal/solution for such applications.

**Comment by lurch** [comment]
@the-spyke I don't work on Etcher, I'm just a helpful 3rd-party user :slightly_smiling_face:

**Comment by thundron** [comment]
We looked into it and for now we haven't currently got any plans to bring a snap/flathub package.
If anyone feels like giving it a try and also managing/supporting it, we're always open to contributions! :D

**Comment by the-spyke** [comment]
@thundron Raspberry Pi image flasher works fine as a snap: https://github.com/popey/imager-snap

**Comment by xlmnxp** [comment]
@lurch there isn't any problem to package it as Snap package
see "Raspberry Pi Imager" available at Snapcraft
https://snapcraft.io/rpi-imager ([source code for YAML](https://github.com/popey/imager-snap))

**Comment by enoch85** [comment]
I'm surprised that you decided to not use snaps. AppImage is legacy by now.
