### ISSUE TITLE
Can activate "Flash!" button with keyboard while a write is in process

### ISSUE THREAD

**Issue by mccollam** [resin-io/etcher#431]
While Etcher is performing a write, it is still possible to activate the "Flash!" button by using the spacebar while the Etcher window has focus.  This is handled gracefully by popping up a message about a write being already in progress, so it's a minor cosmetic issue.  But it seems like it would still be nice to just prevent this behavior.

Steps to reproduce:
1. Launch Etcher.
2. Begin an image write.
3. Press the spacebar.
4. Observe that an error box occurs.

**Comment by jviotti** [comment]
Hi @mccollam ,

Awesome observation! I can't reproduce in OS X though, so it might be a Linux thing. I'll give it a go there.

**Comment by jviotti** [comment]
Hi @mccollam ,

Turns out I can't reproduce on Ubuntu 16.04 LTS neither :/ Could it be something specific to your setup? What distro, desktop environment, or window manager are you running?

**Comment by mccollam** [comment]
Yes, I can do this by clicking "Flash!" and then hitting the spacebar a few seconds later.  Screenshot of the result attached; I can make a video if that's more helpful.

Ubuntu 16.04 amd64 running stock Unity, Etcher 1.0.0-beta6

fader@lacquer:~$ uname -a
Linux lacquer 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

![image](https://cloud.githubusercontent.com/assets/3144447/15512371/92d4472c-21ad-11e6-99c9-e0d13b47aeec.png)

**Comment by jviotti** [comment]
Thanks for the explanation, I can reproduce now. I was attempting to press "space" once I lost focus on the button. Sending a fix right now, thanks a lot!
