### ISSUE TITLE
Privilege escalation should ideally be more narrow

### ISSUE THREAD

**Issue by mccollam** [resin-io/etcher#444]
Privilege escalation via the GUI in Linux is awesome :D

But ideally it would be great to escalate only at the time when absolutely necessary (i.e. writing to a device).  Escalating before then for the entire application leaves a much larger security attack surface.

**Comment by jviotti** [comment]
Hi @mccollam ,

Definitely. I've been working on only elevating the writer process in this PR: https://github.com/resin-io/etcher/pull/423, which is a work in progress. It has been successfully implemented in GNU/Linux and OS X, however I'm having tons of issues in Windows, which is the main reason I'm delaying this.
