### ISSUE TITLE
Possible idiot question, how to uninstall (Arch Linux, Gnome)

### ISSUE THREAD

**Issue by da-n** [resin-io/etcher#451]
OK so I really like Etcher, but I need to remove it now. It is as simple as deleting the .AppImage file and the .desktop file created by the installer? Thanks.

**Comment by jviotti** [comment]
Hi @da-n,

Thanks for reaching out! That's right, deleting the AppImage and the `.desktop` file should be enough!

**Comment by da-n** [comment]
OK brilliant, thanks for confirming @jviotti, my first experience with an AppImage! Guess I can close this off.
