### ISSUE TITLE
Provide a way for users to bypass the Etcher system drive protection layer

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#480]
There might be advanced users that really know what they're doing.

We could either:

- Document the use of an environment variable, like `ETCHER_ADVANCED_MODE=1`. Advanced users will feel confortable doing so, and the feature will be nicely isolated from newbies.

- Provide a checkbox in the drive selector modal saying something like "Advanced usage" with a big warning that will make system drives appear on the modal.

**Comment by msupon** [comment]
I like the env var option, and I appreciate the distro without the check in it.
![screen shot 2016-06-13 at 8 07 42 pm](https://cloud.githubusercontent.com/assets/16903961/16027294/c50aed04-31a2-11e6-9e9f-db469db5f785.jpg)

booted off the drive and it worked perfectly.

**Comment by jviotti** [comment]
Sounds good. Possible names for the environment variable:

- `ETCHER_ADVANCED_MODE`
- `ETCHER_UNSAFE_MODE`
- `ETCHER_RUN_UNSAFE`

I personally like the second one.

**Comment by alexandrosm** [comment]
@jviotti how about an option in the settings?

**Comment by jviotti** [comment]
@alexandrosm Yeah, I think that'd work even better. Propagating env vars from the main process to the renderer process is a pain, so I'm all for a more simplistic option.

**Comment by alexandrosm** [comment]
maybe with a red "dangerous" label next to it, and a warning modal when the user wants to enable it?

**Comment by jviotti** [comment]
I personally think the dangerous label is enough, and a warning modal is just annoying, but maybe that's just me. @taahirisaacs?

**Comment by alexandrosm** [comment]
they'll only see it once anyway, not a big deal, and want to make sure
someone doesn't blow out their hard drive and blame etcher

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by jviotti** [comment]
![unsafe-mode-300616](https://cloud.githubusercontent.com/assets/2192773/16523547/15324ebc-3f72-11e6-8a6a-aa94e84d84f5.png)

**Comment by jmsaltzman** [comment]
I found this thread looking for details on this setting, and while "Allow writing system drive [DANGEROUS]" or other text for this setting would be more correct, this text, as-is, is too hilarious to ever change!!

"Unsafe mode" is mysterious, but the "Dangerous" makes it delicious as well!

It's like a red button with a label next to it saying "DO NOT PRESS THIS BUTTON."

**Comment by lurch** [comment]
https://github.com/balena-io/etcher/blob/master/lib/gui/app/pages/settings/templates/settings.tpl.html#L63
:slightly_smiling_face: :fire:
