### ISSUE TITLE
Thank you <3 (not an issiue (sorry for abusing this, i know its for reall issiues))

### ISSUE THREAD

**Issue by alugarius** [resin-io/etcher#507]
I tried hours to get http://www.lakka.tv/ on my BananaPi Pro

This dd commandline thing never worked and I serached houers for a solution...

Then i found etcher and it was just done... !
This tool is so amazing!

I try to suggest you as default solution for flashig on LakkaTV

**Comment by jviotti** [comment]
Hey there @alugarius ,

Thank you very much for your words! We're very happy to hear we helped you out, and we're very honoured that you recommended us as the default tool on LakkaTV, very appreciated!

I'm closing this issue now, but I encourage you to join our Gitter channel (https://gitter.im/resin-io/chat), where you can say hello to other members of the Etcher community, and to the Etcher team itself!

Have an awesome day!
