### ISSUE TITLE
Allow passing a URL and streaming an image to the drive.

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#54]
This is a major feature that needs to re-architect the code to pass a readable stream directly instead of a file name to the writer first.
- Implement UI to be able to paste a URL as the first step.
- Handle network error conditions gracefully.
- Handle invalid URLs or other invalid condition.

**Comment by jviotti** [comment]
In Etcher, we want to allow the user to pass a URL to an image hosted on the internet, and stream directly to the device. The scope of this project is to implement a new function in etcher-image-stream called “.getFromURL()” that sends an HTTP request to the provided endpoint and makes use of the provided response headers to determine the image size, format, compression, etc to return all the needed information.

If the image is compressed, the function should return the appropriate transform stream that can deal with it (see examples on the same modules).

This functionality should be tested by an end to end suite that starts a local HTTP server to serve example images, and uses those endpoints to write the image to a temporary location, and assert that the image was written and decompressed correctly (if needed).

**Comment by alexandrosm** [comment]
For v1 we are ok with two stage download and write, right?

**Comment by jviotti** [comment]
> For v1 we are ok with two stage download and write, right?

Yeah, we'll do first download, then write, and we'll improve in the
future.

On Thu, Dec 01, 2016 at 08:08:46PM -0800, Alexandros Marinos wrote:
> For v1 we are ok with two stage download and write, right?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io/etcher/issues/54#issuecomment-264368920

-- 
Juan Cruz Viotti
Software Engineer

**Comment by konmouz** [comment]
Following #975 concept, would it be possible to have a widget on publisher's webpage that will preload Etcher with a specific image? For instance, on Raspberry Pi's Rasbian page, there could be 3 CTA's: `Download Torrent` `Download Zip` `Flash with Etcher` or `Load to Etcher`.

<img width="910" alt="screen shot 2016-12-29 at 11 16 55" src="https://cloud.githubusercontent.com/assets/15323961/21542776/5a2bd9e6-cdb8-11e6-9821-f41b8947bb1a.png">
 image

**Comment by alexandrosm** [comment]
i guess a widget with a dual call to action -> "download including Etcher"
and "open with etcher" (better names needed) would be the ultimate nirvana
for several of our publisher integration efforts. I think there are several
background pieces needed to be aligned, as there are binary signing issues
to sort out, but I love the idea and want to figure out what's needed to
get there.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by konmouz** [comment]
Exactly, pretty much the same way torrents and magnets work.

**Comment by jviotti** [comment]
We should re-use https://github.com/zenflow/node-fast-download for this task:

> node module and command-line program for accelerated (multiple connections) http download Stream

**Comment by lurch** [comment]
Given the current plans for v2, should this issue be closed?

**Comment by jviotti** [comment]
Yeah, lets do it. Given the complexity of streaming *any* kind of images, we decided to only support streaming on our internal image catalog.
