### ISSUE TITLE
Add support for .hddimg 

### ISSUE THREAD

**Issue by rexstjohn** [resin-io/etcher#549]
Wanted to request a simple update which is to support ".hddimg" files (generated by Yocto Linux). This format is a simple disk image, if you rename to .iso will already work with Etcher. 

Thank you for your excellent work (and for adding .dsk support last time). Etcher is very useful!

**Comment by jviotti** [comment]
Hi @rexstjohn ,

Thanks for reaching out, I'll be sending PRs to support `.hddimg` today, and they will be available in the next Etcher release!
