### ISSUE TITLE
Does this program works for Bootable images too?

### ISSUE THREAD

**Issue by highacid** [resin-io/etcher#564]
Hello,

I am curious to know if this programs allows to create bootable USB from existing ISO images, such as Windows, Linux, etc.

**Comment by jviotti** [comment]
Hi @highacid ,

Etcher allows to write any image (like `img`, `iso`, etc) to *any* removable drive, including but not limited to SD Cards.

**Comment by jviotti** [comment]
I'm closing this as resolved!
