### ISSUE TITLE
Congratulations Thrown Errrors Went away on Multi Boot W10 - 4-Linux's!

### ISSUE THREAD

**Issue by jmjeffers** [resin-io/etcher#628]
- **Etcher version:** beta 13
- **Operating system and architecture:** W10 14393.10 Home-64
- **Do you see any meaningful error information on DevTools?** NONE!

This machine multi-boots Ubuntu/Mate/Mint Rosa/OpenSuse 13.2 from grub2 all os's are 64 bits.

Java no longer throws errors on this machine (suspected it was seeing the other EXT4 drives (SDA to 14) via doeky driver 4 /home partitions were mounted to Win 10)  No other machines threw these errors, they did not have ext4 partitions mounted to Win10. Previously this machine always threw errors then it went about it's business.

Thought you would like to know. 

Thanks John

**Comment by jviotti** [comment]
Hi @jmjeffers ,

That's really great to hear, thanks a lot for letting me know. Please don't hesitate in pinging us if you experience the similar error again!

All the best,
