### ISSUE TITLE
Use tooltip instead of "SHOW IN FULL"

### ISSUE THREAD

**Issue by dlech** [resin-io/etcher#634]
- **Etcher version:** 1.0.0-beta.13
- **Operating system and architecture:** Ubuntu 16.04 amd64
- **Do you see any meaningful error information on DevTools?** N/A

Not a serious issue, just polish. It would be more intuitive to show the full filename using a tooltip when hovering rather than requiring the user to click and open a separate window to show the full file name.

If a tooltip is not technically possible, I would suggest changing the text to "show full file name". It is not clear what "show in full" might mean.

![selection_009](https://cloud.githubusercontent.com/assets/963645/17712315/ff453fde-63ba-11e6-9c02-1c60858a7a68.png)

**Comment by jviotti** [comment]
Hi @dlech ,

Thanks a lot for the suggestions! I'd personally have to avoid having two ways of showing the file name (tooltip + modal) if possible, just for simplicity purposes.

I do like the "SHOW FULL FILE NAME" suggestion.

I'll loop @taahirisaacs , Etcher's designer, in this conversation to have his opinion as well.
