### ISSUE TITLE
Read to .img

### ISSUE THREAD

**Issue by Bottersnike** [resin-io/etcher#641]
It's less of an issue (more of a request), but I was going to completely replace win32diskImager with Etcher then I realised that Etcher has no way to read from a disk to an img and as such can't be used to backup or duplicate disks. I'd love to see that in a future release as I'd love to be able to switch over all the way (from w32di to etcher).

**Comment by jviotti** [comment]
Hey there!

Thanks a lot for the suggestion. This something we are definitely
looking forward to provide in the near future.

We have an issue for it over here: https://github.com/resin-io/etcher/issues/266,
so lets continue discussion there :)

On Mon, Aug 22, 2016 at 03:13:17AM -0700, Bottersnike wrote:
> It's less of an issue (more of a request), but I was going to completely replace win32diskImager with Etcher then I realised that Etcher has no way to read from a disk to an img and as such can't be used to backup or duplicate disks. I'd love to see that in a future release as I'd love to be able to switch over all the way.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io/etcher/issues/641

-- 
Juan Cruz Viotti
Software Engineer
