### ISSUE TITLE
When run on Jessie you get an error window but after you press ok Etcher runs

### ISSUE THREAD

**Issue by Ntemis** [resin-io/etcher#668]
- **Etcher version:**
Beta 13
- **Operating system and architecture:**
Linux solydxk 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
This is what it reports as error:
Error: /tmp/.org.chromium.Chromium.fvo3eI: line 12: blkid: command not found
/tmp/.org.chromium.Chromium.fvo3eI: line 12: blkid: command not found
/tmp/.org.chromium.Chromium.fvo3eI: line 12: blkid: command not found
/tmp/.org.chromium.Chromium.fvo3eI: line 12: blkid: command not found
/tmp/.org.chromium.Chromium.fvo3eI: line 12: blkid: command not found
/tmp/.org.chromium.Chromium.fvo3eI: line 12: blkid: command not found

    at /tmp/.mount_o4fOjH/usr/bin/resources/app.asar/node_modules/drivelist/build/scripts.js:27:23
    at ChildProcess.exithandler (child_process.js:205:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)

**Comment by jviotti** [comment]
Hi @Ntemis ,

This error was reported and resolved in https://github.com/resin-io/etcher/issues/640. The new Etcher's version will search for `blkid` on its standard location, but as a temporary fix, make sure `/sbin` is in your path.

**Comment by Ntemis** [comment]
Gracias.
Great app btw keep up the good work :)

**Comment by jviotti** [comment]
De nada! Let us know if you encounter any other issue!

On Mon, Aug 29, 2016 at 03:11:44AM -0700, Ntemis wrote:
> Gracias.
> Great app btw keep up the good work :)
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io/etcher/issues/668#issuecomment-243086144

-- 
Juan Cruz Viotti
Software Engineer
