### ISSUE TITLE
Uncaught TypeError: modal.dismiss is not a function

### ISSUE THREAD

**Issue by WasabiFan** [resin-io/etcher#672]
- **Etcher version:** Beta 13
- **Operating system and architecture:** Windows 10 x64
- **Do you see any meaningful error information on DevTools?** Yes; see below.

After Etcher finished flashing my drive, it printed an error to the console. The error doesn't seem to have affected operation in any way.

![image](https://cloud.githubusercontent.com/assets/3310349/18154409/2a211ce6-6fb9-11e6-8f42-59c9df8c1e54.png)

**Comment by jviotti** [comment]
Hi @WasabiFan ,

Thanks a lot for reporting this. Luckily, this issue has been fixed recently by https://github.com/resin-io/etcher/pull/645, and should land in the next release!

**Comment by WasabiFan** [comment]
Oh, great! GitHub's search is pretty unforgiving and apparently I didn't use it quite right.
