### ISSUE TITLE
Incorrect write of some gz compressed images with `etcher-image-write` v7.0.1

### ISSUE THREAD

**Issue by imrehg** [resin-io/etcher#709]
- **Etcher version:** commit 893f42a124375d04d45bfcb2b1b454431231642f (`etcher-image-write` to v7.0.1)
- **Operating system and architecture:** ArchLinux x64
- **Do you see any meaningful error information on DevTools?** no

When burning some compressed images, it can result in validation error (likely actually wrongly burned images). Bisected it to the commit above.

Found example file that triggers: https://www.dropbox.com/s/yk2f5bifkzjum1b/resin-hostname-1.8.0-1.13.0-7ad55d1c946b.img.gz?dl=0 Burning this `gz` results in full write but then receive validation error. No error message in the console. 

Uncompressing and burning image works fine.  The same image compressed with `xz` or `zip` burns fine and validates. `bz2` fails in this commit too, but looks like an unrelated issue (appears earlier in commit history) just mentioning not to hold up the investigation (will check that separately).

**Comment by jviotti** [comment]
Turns out this is related to https://github.com/resin-io/etcher/issues/710, and the same fix worked for both.
