### ISSUE TITLE
Win10 during verification phase: events.js:160 Unhandled 'error' event

### ISSUE THREAD

**Issue by BertLindeman** [resin-io/etcher#724]
So pleased with the ability to simply take a zip file and in a simple way end up with an image on an sd-card. Thank you!
- **Etcher version:1.0.0.beta.15**
- **Operating system and architecture:Windows 10 x64**
- **Do you see any meaningful error information on DevTools?**
  Sorry . . . Closed etcher before I decided to enter an issue for this.
  And the target sdcard is in use now.

Is there a log-file somewhere on disk that contains similar info?
Pity the screens cannot be copied as text, so I have to paste some images:

![etcher_crash_in_verify](https://cloud.githubusercontent.com/assets/8142081/18893165/f871b912-850c-11e6-844d-274ed9fbc0a0.png)

![js_error](https://cloud.githubusercontent.com/assets/8142081/18893177/037d31f6-850d-11e6-81c8-6a002af08ef4.png)

Did not have the patience to do the exercise again, so just used the sd-card.
Have not seen any problems (yet), so this is an issue with a low priority as far as I am concerned.

**Comment by jviotti** [comment]
I'll close this ticket in favor of https://github.com/resin-io/etcher/issues/834. Lets continue discussion and investigation on that one!
