### ISSUE TITLE
Don't forget previous image when cancelling file-selection dialog

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher#730]
- **Etcher version: 1.0.0-beta.15**
- **Operating system and architecture: Ubuntu 14.04 x64**
- **Do you see any meaningful error information on DevTools? No**

Consider the following scenario:
 1. No image-file is selected in Etcher, and "Select image" is highlighted
 2. You click on "Select image" and select an image-file using the file selector-dialog
 3. Etcher changes to show the name of the image-file, and "Connect a drive" is highlighted
 4. You click on the "Change" button to select a different image, but then click Cancel in the file-selector dialog

At this point I'd expect Etcher to go back to step 3, but it actually goes all the way back to step 1!

**Comment by jviotti** [comment]
Thanks for finding and reporting this. The suggestion makes perfect sense. I'm looking forward to fix it very soon.
