### ISSUE TITLE
Display "nicer" error message when selecting an invalid zipfile

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher#731]
- **Etcher version: 1.0.0-beta.15**
- **Operating system and architecture: Ubuntu 14.04 x64**
- **Do you see any meaningful error information on DevTools?**
![screenshot from 2016-09-29 14 45 34](https://cloud.githubusercontent.com/assets/476186/18956463/729c741a-8653-11e6-84be-fc2e25841a84.png)

If I select a zip file, which **doesn't** contain a disk-image file, then I get this rather ugly error message:
![screenshot from 2016-09-29 14 44 08](https://cloud.githubusercontent.com/assets/476186/18956526/9d07b318-8653-11e6-8957-654be6bb8670.png)

It would be nice if you could catch this error, and display a nicer-looking error message :-)

**Comment by jviotti** [comment]
Ugh, it's indeed very ugly. The stack trace shouldn't be coming through in this case. I wonder if there was a change on the error processing and showing logic that changed recently and caused this regression. 

I'll investigate and report back!

**Comment by jviotti** [comment]
Fixed in https://github.com/resin-io/etcher/pull/752
