### ISSUE TITLE
Add a "burn another" button on completion

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#74]
The completion screen will then have two buttons:

1. Completely start over by reseting every selection.

2. Burning the same image you selected before to another drive (basically keeps the image selection and resets the rest).

**Comment by taahirisaacs** [comment]
This method should work @jviotti 

![screen shot 2016-01-18 at 10 14 57 am](https://cloud.githubusercontent.com/assets/15251376/12386215/64077c92-bdcc-11e5-9dfd-d5a58c5672cc.png)

**Comment by jviotti** [comment]
@fedealconada Can you implement the above design? (only the separation between the buttons and explanation. The new footer design is coming in another PR).

**Comment by jviotti** [comment]
Re-opening as a reminder to finish the design side of this feature.
