### ISSUE TITLE
add option to restore sdcard?

### ISSUE THREAD

**Issue by mpvader** [resin-io/etcher#741]
- **Operating system and architecture:** Windows

after writing an image file, the sdcard is often much smaller. Under windows it is rather difficult to restore it again to its normal site: needs diskpart. Would be super to have a button in etcher to restore the disk to one big single partition again.

any thoughts? Other than liking it, I must admin that I probably won't be spending time on this myself anytime soon.. :smile:

**Comment by lurch** [comment]
See also #273

**Comment by mpvader** [comment]
That's it indeed! Great.
