### ISSUE TITLE
Use info icon button instead of "SHOW FULL FILENAME"

### ISSUE THREAD

**Issue by dlech** [resin-io/etcher#742]
![etcher-info-icon](https://cloud.githubusercontent.com/assets/963645/19023117/ceccd112-88ab-11e6-82d8-211029e5c44b.png)

Info icon buttons are becoming a fairly ubiquitous way to indicate that detailed information is available if you click the icon.

For images that contain extended metadata (#740), this could be a way to display some of the informational items. For images without extended metadata, clicking this icon could show the full file name and the size of the file.

**Comment by alexandrosm** [comment]
sounds good to me. The long text there always bothered me. @jviotti @taahirisaacs, thoughts?

**Comment by dlech** [comment]
I almost forgot... Another important part of my suggestion here is that the text in the info window can be copied to the clipboard. This way, when we ask someone which image they are using, they can just copy the info from here and paste it somewhere.

**Comment by jviotti** [comment]
Sounds good! Regarding copying text to the clipboard, the reason why it doesn't work at the moment is that text selection collides with the fact that we allow the window to be dragged from anywhere, but maybe there is a way we can allow this in certain element (e.g: a CSS class that when put on an element, disables dragging and enables text selection).

Maybe we should create a separate ticket for that?

**Comment by jviotti** [comment]
Regarding showing extended metadata information, we could display a list saying what is available, similarly to what we currently output on DevTools when an extended archive is selected. For example:

- Bmap (tick logo)
- Logo (tick logo)
- Etc.

**Comment by lurch** [comment]
Or you could have a "copy to clipboard" button?

**Comment by jviotti** [comment]
That mitigates the issue but doesn't solve it completely. The fact that people can't select text has been a recurrent complaint that applies to several sections of the application, and unless we can to put dozens of "copy to clipboard" buttons all over the place, we must find something that scales.

A certain CSS class that gets applies to certain areas (like in modals, by default, for example), should be good enough I think.

**Comment by dlech** [comment]
> Regarding copying text to the clipboard, the reason why it doesn't work at the moment is that text selection collides with the fact that we allow the window to be dragged from anywhere, but maybe there is a way we can allow this in certain element (e.g: a CSS class that when put on an element, disables dragging and enables text selection).
> 
> Maybe we should create a separate ticket for that?

A copy to clipboard icon that copies everything might be OK too.

**Comment by lurch** [comment]
Isn't showing the presence / absence of bmap files etc. more of a 'developer feature' (for publishers) though, rather than an end-user feature? (who shouldn't need to know or care what bmaps are)

**Comment by alexandrosm** [comment]
We'd discussed having a "turbo mode" in the write progress bar, maybe a
lightning icon, that provides some hook for interested users to know what's
going on, but other than that, then yeah, we shouldn't be exposing that
much to the user.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by jviotti** [comment]
Yeah, good points, lets only display the full image name (and size potentially).
