### ISSUE TITLE
[feature] Confirm exiting application while flashing image

### ISSUE THREAD

**Issue by waspinator** [resin-io/etcher#744]
- v1.0.0-beta.15 - 2016-09-26
- macOS x86

While an image is being flashed, it's too easy to close Etcher unintentionally. I believe it would be a helpful feature to show a `confirm()` dialog before quitting while an image is being flashed.

**Comment by jviotti** [comment]
Great idea! I'm sure Electron provides a way to intercept a close event. The `FlashStateModel` component also provides a nice `isFlashing()` method that can be used to either allow the user to close the app directly, or show the confirmation modal.

**Comment by taahirisaacs** [comment]
Created a simple warning modal to alert the user if they close the application while an image is being flashed.

![exit](https://cloud.githubusercontent.com/assets/15251376/20099201/ff230436-a5bf-11e6-817a-9d334245e3b4.png)

**Comment by lurch** [comment]
Looks good. But I think "...sure you want to..." is more idiomatic than "...sure you would like to..."

**Comment by WasabiFan** [comment]
It's worth noting that the implications of this action aren't immediately clear to the user. I think that adding a sentence explaining what will happen would be nice. Also, currently "what will happen" is that Etcher will continue flashing headless :laughing:

**Comment by lurch** [comment]
Hmm, given that the dialog in #840 says "You will be able to overwrite your system drives if you're not careful.", maybe this dialog could also say something like "This may leave your drive in an unusable state." ?

> Also, currently "what will happen" is that Etcher will continue flashing headless :laughing:

Yeah, that's a bug #850

**Comment by taahirisaacs** [comment]
Updated copy on design.

![exit confirmation](https://cloud.githubusercontent.com/assets/15251376/20103212/baec2984-a5d1-11e6-9db0-3227730db291.png)

**Comment by jviotti** [comment]
@taahirisaacs Looks good! Following @konmouz line of thoughts regarding these kinds of modals, I think we can remove the "Cancel" button and just present "Yes, continue". The user can dismiss the modal by clicking somewhere else or in the top right corner cross icon.

**Comment by WasabiFan** [comment]
> I think we can remove the "Cancel" button and just present "Yes, continue".

No! Please, no! Having just a "dismiss" button on actions like this is detrimental for the user. I have yet to see an existing app by a notable company or group that doesn't have a "no" option on dialog boxes like this, and there's a good reason for that: "dismissing" the warning of imminent danger is *not* the same as aborting the action that caused it. In the other recent case of the "unsafe mode" dialog, there wasn't an immediate threat, so I didn't have a significant issue with it; but in this case, it really does matter.

Having the "dismiss" button is great and gives the user a quick and natural choice, but it doesn't work for all cases, especially when the user intentionally initiated the offending action.

**Comment by konmouz** [comment]
@taahirisaacs we can just remove the 'X' on this modal. In general when there is a question we need to have 'yes and no' CTAs. On the contrary when you need to make a selection (like when you select a drive) there could be just a 'continue' CTA and an 'X' one to dismiss.
