### ISSUE TITLE
[Feature Request]Add persistence option for etcher!

### ISSUE THREAD

**Issue by dinosaurfiles** [resin-io/etcher#748]
Universal USB Installer employs a persistence option as shown in the picture below but the software is only available in Windows! I hope etcher could also get this option.
![](http://www.howtogeek.com/wp-content/uploads/2010/04/531x415xsshot711.png.pagespeed.gp+jp+jw+pj+js+rj+rp+rw+ri+cp+md.ic.EgUo_ZQLVY.png)

**Comment by lurch** [comment]
Same as #413 ?

**Comment by jviotti** [comment]
Thanks a lot guys! I'll close as duplicate and we can continue discussion on the other one.
