### ISSUE TITLE
ISO flash ok but it is not correctly

### ISSUE THREAD

**Issue by DiegoAccorinti** [resin-io/etcher#759]
- **Etcher version:**   v1.0.0-beta.15
- **Operating system and architecture:**  Debian Jessie AMD64

When trying to flash an ISO image, the procedure ends OK but seeing the results in Gparted are:

![pantallazo-1](https://cloud.githubusercontent.com/assets/4205235/19355739/cad89430-9141-11e6-9f4d-4fabfddf405a.png)

ISO itself flashed with unetbootin is as follows:

![pantallazo](https://cloud.githubusercontent.com/assets/4205235/19355752/d376a618-9141-11e6-88d6-87272041aec3.png)

why it is marked as "hidden"? and why the image does not occupy the entire space as it does with netbooting?
In addition, it clarified that the pen drive fails when trying to boot the ISO.
regards.

**Comment by lurch** [comment]
See https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#flashing-ubuntu-isos and https://github.com/resin-io/etcher/search?q=unetbootin for more info.

**Comment by DiegoAccorinti** [comment]
tnks,  but dont solute the problem. The pen don't boots.

**Comment by DiegoAccorinti** [comment]
ok   the pendrive boots OK in a non-EFI PC.   tnks
