### ISSUE TITLE
Windows portable version

### ISSUE THREAD

**Issue by tooomm** [resin-io/etcher#760]
- **Operating system and architecture:** Win 10 64bit

I would highly appreciate to see a portable version of this sweet tool! ❤️

**Comment by jviotti** [comment]
Hi @tooomm,

Thanks for the suggestion! We do build a portable version at one point during the packaging, but only re-distribute the final installer. Uploading the portable version as well sounds like a good idea!

**Comment by tooomm** [comment]
You already somehow build it? That sounds great.
Makes just distributing it an easier task. :)

**Comment by jviotti** [comment]
The installer gets created around an standalone version of the app. Of course, the standalone version consists of many files (dlls and other resources) but can be run from anywhere. 

Is this what you're looking for, or do you mean a single standalone executable instead?

**Comment by lurch** [comment]
I'm assuming he meant something along the lines of http://portableapps.com/ i.e. that can just be run by extracting a zipfile to a local folder?

**Comment by tooomm** [comment]
Actually 
>many files (dlls and other resources) but can be run from anywhere

is pretty much what i'm looking for. 
Is there are a version hosted somehwere that i can test?

I don't use suits like portableapps.com, having just a single executable file is easier to handle for sure!

**Comment by jviotti** [comment]
@tooomm

Sounds good! We don't have builds like that uploaded anywhere, but you can build one from source if you like (see https://github.com/resin-io/etcher/blob/master/docs/RUNNING-LOCALLY.md. Once you have a locally running build, you can run `.\scripts\build\windows.bat package <arch>` to get the portable build).

**Comment by tooomm** [comment]
I happily wait for a official distribution then. ;)

**Comment by DJuego** [comment]
Me too. 👍  Please! :-) 
Thanks!
DJuego

P.S.  I have discovered this tool from ev3dev project.

**Comment by lurch** [comment]
Just in case the people who've commented on this issue haven't seen this yet:
https://talk.resin.io/t/etcher-1-0-0-beta16-release/379
