### ISSUE TITLE
Elaborate Error when writing to disk. What is wrong?

### ISSUE THREAD

**Issue by mendeldesign** [resin-io/etcher#773]
![schermafbeelding 2016-10-25 om 14 25 43](https://cloud.githubusercontent.com/assets/831082/19686078/f246373e-9abf-11e6-9903-116f7f954782.png)

![schermafbeelding 2016-10-25 om 14 26 07](https://cloud.githubusercontent.com/assets/831082/19685919/22907f0e-9abf-11e6-91d2-bb93b69c6dfd.png)

- **Etcher version: 1.0.0-beta.15**
- **Operating system and architecture: OSX 10.11.6**
- **Do you see any meaningful error information on DevTools?**

**Comment by mendeldesign** [comment]
It seems to be saying that the image file was not ok, but that img file actually worked a month ago on a different SD card.

**Comment by lurch** [comment]
Looks like it's going wrong because of the `&` in the file-path? See also #738

**Comment by mendeldesign** [comment]
O wow you are right, dragged it to the desktop and it works. Thank you for the quick reply, I was already downloading new images from the raspberry website.
