### ISSUE TITLE
Website download instructions advise users to attempt to execute a zip file as an executable.

### ISSUE THREAD

**Issue by emctague** [resin-io/etcher#785]
- **Etcher version:** 1.0.0
- **Operating system and architecture:** linux x64
- **Do you see any meaningful error information on DevTools?** no

It seems that the installation instructions for the linux version of etcher are broken. It currently advises the user to `chmod +x` the downloaded zip file, instead of extracting it and performing operations on the AppImage it contains.

![screenshot from 2016-10-28 20 30 30](https://cloud.githubusercontent.com/assets/22970065/19825882/6c5f81ee-9d4d-11e6-971e-346454fd9d21.png)

It also seems to give the same advice for the windows download:

![screenshot from 2016-10-28 20 31 19](https://cloud.githubusercontent.com/assets/22970065/19825894/89dc42fc-9d4d-11e6-8f44-18de5ff9eb86.png)

**Comment by jviotti** [comment]
Thanks for the heads up! Fixed by https://github.com/resin-io/etcher-homepage/commit/3335846b447d0b86b0cf2c1cb0185605d09a05c7

**Comment by jviotti** [comment]
I've opened a new ticket for the fact that the GNU/Linux instructions are being shown for Windows: https://github.com/resin-io/etcher-homepage/issues/20
