### ISSUE TITLE
Rename "Standalone" version

### ISSUE THREAD

**Issue by imrehg** [resin-io/etcher#793]
There's a new set of "Standalone" Windows versions of Etcher to download. It was pretty confusing trying to figure out what it means. It would be great to mark that "Portable" for clarity, and possibly "Installer" the other version, for clarification.

**Comment by jviotti** [comment]
I'll change "Standalone" to "Portable" and add "Installer" to the other ones as suggested. I think we should aim to obviousness rather than conciseness.

**Comment by WasabiFan** [comment]
Alternately, you could make it two steps: First select your OS and then select the type. Or, maybe add OS headers in the list. As it is, it takes some real thinking to figure out which one you want.

**Comment by lurch** [comment]
Yeah, having 7 different download options in a single drop-down menu might be a bit overwhelming for some people.

**Comment by jviotti** [comment]
@lurch @WasabiFan I agree with all feedback. We should put more serious efforts in re-designing the site and add new improvements. /cc @craig-mulligan @taahirisaacs

**Comment by alexandrosm** [comment]
I guess the obvious improvement is to have something like:

Download now!
[Windows V] - [x64 V] - [Installer V]

Where the V is the down arrow in a dropdown. Basically have sane defaults
and let people choose if they want to alter any individual dimension.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by imrehg** [comment]
@alexandrosm please don't do multi-dropdown, IMHO that's truly horrendous :/

**Comment by WasabiFan** [comment]
> please don't do multi-dropdown, IMHO that's truly horrendous :/

I think it's better than it is now, especially considering that the drop-downs would (presumably) default to your auto-detected OS. I can't think of any better options at the moment either.

**Comment by lurch** [comment]
Given that Windows is the only platform with separate Portable / Installer builds, if you select e.g. Linux as the OS, would the third dropdown disappear? ;)

**Comment by alexandrosm** [comment]
yeap, but keep in mind that there are other "package types" like "debian
package" we may want to highlight here.

And wait till we get to "GUI vs CLI" editions!

@imrehg I agree it can be done very badly, but I also suspect we can do it
decently well if we pay attention to it. It's just a lot more fiddly to get
right than other UIs, but I trust this crowd to smash it until it's perfect
:)

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by craig-mulligan** [comment]
@jviotti did you see the site revision yesterday? https://craig-mulligan.github.io/etcher-website/

It connects to #792 and only pulls the new downloads when the site is built. 

I've moved the downloads to a table, and then do an auto-detect os/arch and populate the main download button in the section. 

I quite like node.js download page: 

Where they highlight defaults and list other options: 
https://nodejs.org/en/download/current/

**Comment by lurch** [comment]
> I quite like node.js download page:
Where they highlight defaults and list other options:
https://nodejs.org/en/download/current/

Side note: The thing I hate about the node.js download page is that they offer binary downloads for Linux, but **nowhere** (that I could find) do they give instructions on how to install them! :-(
(I ended up using https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions instead)

**Comment by WasabiFan** [comment]
@craig-mulligan One thing I think really needs improvement on that revision concept you linked to is the architecture column of the table. It's very hard to scan the list and figure out which one is the one you want. Could you write out "32-bit" and "64-bit" instead of the shortcut notations?

**Comment by jviotti** [comment]
The revision looks very nice already, I like the table layout for the
downloads. I don't like the main action button text very much though.
"Try Etcher" feels like if we're offering a trial to users. Maybe
"Download Etcher"?

On Wed, Nov 02, 2016 at 01:12:46AM -0700, Craig Mulligan wrote:
> @jviotti did you see the site revision yesterday? https://craig-mulligan.github.io/etcher-website/
> 
> It connects to #792 and only pulls the new downloads when the site is built. 
> 
> I've moved the downloads to a table, and then do an auto-detect os/arch and populate the main download button in the section. 
> 
> I quite like node.js download page: 
> 
> Where they highlight defaults and list other options: 
> https://nodejs.org/en/download/current/
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io/etcher/issues/793#issuecomment-257798553

-- 
Juan Cruz Viotti
Software Engineer

**Comment by WasabiFan** [comment]
A few pedantic notes:
- Could you hyphenate "Hard drive friendly"? 
- Is the conclusion that "etcher" is capitalized or not? I think it would seem more logical (especially in a title) if it were capitalized.

Over all, I think it's a significant usability improvement over the existing site (which is the main reason I'm participating in these discussions). Nice job!

P.S. It would be really cool if the preview gif included the progress bar filling up :laughing:

**Comment by dlech** [comment]
I like sites that offer you the most sensible download based on your browser info and then have a link for "more download options" that takes you to a downloads page that lists *all* of the available options with some helpful explanations.

**Comment by alexandrosm** [comment]
Yeah, i think that would be ideal.. a sane default and a link to more
options. The table could be a bit more condensed and not lead with the long
filename maybe?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by craig-mulligan** [comment]
Okay so in the header section we replace the 'Try etcher' with 'Download etcher for `<os>`' and then have a link below the takes them to the table of downloads. I think we should keep the downloads section on the homepage, I don't think it's necessary to add it's own page until we have more download options.

In the table we simplify the filename and add `portable/installer` where appropriate. Also, make `32-bit/64-bit` more prominent (bold?)

All in agreement?

**Comment by lurch** [comment]
Could there also maybe be a "separator bar" or something between the downloads for the different OSes?
