### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher#794]
Now that http://etcher.io redirects to https://www.etcher.io/ , the URL in this repo's description should probably be updated too?

**Comment by lurch** [comment]
And I wonder if all the other references https://github.com/resin-io/etcher/search?utf8=%E2%9C%93&q=%22http%3A%2F%2Fetcher.io%22&type=Code should be updated too?

P.S. Why does http://etcher.io/ redirect to the 'www' subdomain, when http://resin.io/ and http://resinos.io/ don't do that?

**Comment by jviotti** [comment]
Good catch! I've updated the repository description and all references in the code base! I'll PR soon.
