### ISSUE TITLE
README.md doesn't match "style guide"

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher#797]
According to https://github.com/resin-io/docs#style-manual **resin.io** shouldn't be capitalised, whereas `README.md` in this repo currently says "the Resin.io team".
I won't submit a PR to fix this myself, because it's unclear whether "the Resin.io team" should be updated to "the resin.io team" or "the resin team".

**Comment by lurch** [comment]
This is also present in `SUPPORT.md`

**Comment by alexandrosm** [comment]
you got it right. feel free to PR. it should be all-lowercase.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by lurch** [comment]
So, which is correct: "the resin.io team" or "the resin team" ?

And I guess all the docs should similarly be updated to lower-case 'etcher' instead of 'Etcher'?

**Comment by alexandrosm** [comment]
the former. I'm not sure we have similar guidelines for Etcher, let's
discuss next week?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by jviotti** [comment]
@alexandrosm The link @lurch shared also mentions that "Etcher" should be "etcher" instead. Lets do both changes I guess.

**Comment by dlech** [comment]
Names stylized with a leading lower-case letter are annoying (I know first hand from "ev3dev"). Please don't use "etcher". (Unless you are also doing something else to stylize it, like making it bold or using a different color or adding &#8482; or &reg; or something like that.)

**Comment by dlech** [comment]
Names that come from urls aren't so bad, so "resin.io" doesn't bother me so much.

**Comment by jviotti** [comment]
Yeah, I agree with @dlech that "Etcher" looks *way* better than "etcher".

**Comment by WasabiFan** [comment]
And it's a real word as well, so capitalizing it makes it clear that Etcher is a product.

**Comment by lurch** [comment]
Ping @sonyagreen and @shaunmulligan  (because of https://github.com/resin-io/docs/pull/345 )

**Comment by lurch** [comment]
> And it's a real word as well, so capitalizing it makes it clear that Etcher is a product.

The same could be said for 'resin'.

**Comment by lurch** [comment]
...and on the subject of "style guides", both the repo description and the README.md say
> Flash OS images to SD cards & USB drives, safe & easy.

whereas package.json says
> An image flasher with support for Windows, OS X and GNU/Linux.

and the website says
> Burn. Better.
Burn images to SD cards & USB drives, safe & easy.

It might be worth settling on a single "official slogan"? ;-)

**Comment by WasabiFan** [comment]
Note from my pedant side: "safe & easy" should be "safely and easily" if that one is going to go into more widespread use. Alternately, it could be "It's safe and easy".

**Comment by lurch** [comment]
@WasabiFan I totally agree. I'd been trying to silence my pedantism by reading the comma as a silent "it's" ;-)

**Comment by jviotti** [comment]
I think this issue is covered already. Please feel free to re-open if not!

**Comment by lurch** [comment]
So, if we're settling on "Etcher" rather than "etcher", does https://github.com/resin-io/docs#style-manual need to be updated?

And should the Copyright strings be saying "Resinio Ltd." instead of "resin.io" ?

**Comment by jviotti** [comment]
> So, if we're settling on "Etcher" rather than "etcher", does https://github.com/resin-io/docs#style-manual need to be updated?

Re-pinging @shaunmulligan and @sonyagreen.

> And should the Copyright strings be saying "Resinio Ltd." instead of "resin.io" ?

Resinio Ltd is the company name, where "resin.io" is one product of the company. I think the copyright string (as well as the "company name" in the Windows build script) should refer to the former. @alexandrosm ?

**Comment by lurch** [comment]
Re-opening issue, pending feedback from other people.

**Comment by sonyagreen** [comment]
I'm hoping @alisondavis17 can weigh in on the capitalization of products (the one in question is 'Etcher' vs 'etcher').

**Comment by lurch** [comment]
Now that the "slogan" seems to have been settled on as `Flash OS images to SD cards & USB drives, safely and easily.`, should that also be set as the description on the [Gitter channel](https://gitter.im/resin-io/etcher) ?

**Comment by WasabiFan** [comment]
Electron's site also uses the old slogan, FYI. I don't know how if that is manual or automatic though.

**Comment by lurch** [comment]
> Electron's site also uses the old slogan, FYI.

Good spot, thanks! https://github.com/electron/electron.atom.io/pull/608

**Comment by jviotti** [comment]
I've updated the Gitter description!
