### ISSUE TITLE
drag-and-drop images

### ISSUE THREAD

**Issue by imrehg** [resin-io/etcher#815]
Would be nice to be able to drag-and-drop an image onto Etcher in the image selection phase for example (ie. just after starting, not having pressed any button yet), and select that.

**Comment by jviotti** [comment]
Hi @imrehg ,

This is indeed the case already. We recently hit a regression with this functionality that was fixed in v1.0.0-beta.16 (see https://github.com/resin-io/etcher/pull/766). 

Does it still fail for you?
