### ISSUE TITLE
Drive-filtering suggestion

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher#830]
After https://github.com/resin-io-modules/drivelist/issues/98 has been implemented (i.e. we can get info about _all_ the mountpoints which are used by each physical drive), we could filter out the drive on which the image we're going to be flashing is stored on.

Currently, this scenario is possible (which would be prevented if this issue is implemented) :
 1. User has a USB Flash drive (e.g. `/dev/sdb`) and a USB SD-reader (e.g. `/dev/sdc`) connected to their computer
 2. User is running out of space on their computer's HDD, so they download e.g. `2016-09-23-raspbian-jessie-lite.zip` to their USB Flash drive
 3. User launches Etcher, and selects the `2016-09-23-raspbian-jessie-lite.zip` file they've stored on their USB Flash drive
 4. User accidentally selects `/dev/sdb` as the drive they want to flash to
 5. User clicks `Flash!`
 6. ???? (I didn't actually try this myself to see what happens)

If this issue was fixed, `/dev/sdb` would automatically be filtered out (until the user selects an image _not_ stored on their USB Flash drive), and Etcher would auto-select `/dev/sdc`.

**Comment by jviotti** [comment]
Very good observation, we should definitely be doing this, so I'll mark it as a bug.

**Comment by jviotti** [comment]
Should we omit the drive altogether, or display a warning label somehow describing that the drive is the place where the image resides?

This is what we do for locked SD Cards for example (although this is an old screenshot the labels are being shown below the drive information at the moment):

![37227a66-2fea-11e6-8ebc-baa15d9b55f9](https://cloud.githubusercontent.com/assets/2192773/20153196/438d635e-a6ca-11e6-81e7-8f31e82a29b3.png)

@konmouz ?

**Comment by WasabiFan** [comment]
Side-note: It would be great if labels like this "locked" one explained _why_ the device is locked. I could easily imagine a user looking at this and thinking that _Etcher_ locked it as opposed to the device being locked by the OS/hardware. Is there a tooltip already there that serves this purpose?

**Comment by jviotti** [comment]
Very good point! Something for @konmouz and @taahirisaacs to help us with.

**Comment by lurch** [comment]
I noticed this evening that an 'unselectable' drive (in my specific case I was experimenting with an image bigger than the drive) in that dialog still displays a hand-cursor when you mouse-hover over it, which it probably shouldn't.

**Comment by jviotti** [comment]
@lurch Good catch, we should correctly set the `cursor` CSS property there. Do you mind opening an issue for it?

**Comment by lurch** [comment]
> @lurch Good catch, we should correctly set the cursor CSS property there. Do you mind opening an issue for it?

Done, #865

**Comment by alexandrosm** [comment]
@jviotti should we close this?

**Comment by jviotti** [comment]
I think this feature is still valid, and haven't been done yet.

**Comment by konmouz** [comment]
@jviotti we can follow #993 here or just a tooltip. Please, also check [zeplin](https://zpl.io/Z2LGn4) for label reference.

**Comment by jviotti** [comment]
@konmouz Not sure I'm seeing the Zeplin screen you're referring to. How would a tooltip/popover work here? Maybe we should disable such drive with a nice badge that somehow conveys to the user that this is the drive that contains the image instead?

**Comment by lurch** [comment]
> Maybe we should disable such drive with a nice badge that somehow conveys to the user that this is the drive that contains the image instead?

That's what I was thinking, yes.

**Comment by jviotti** [comment]
That is an easy fix. The hard part is to figure out what to put in the badge. I can't think of anything short while descriptive. "IMAGE IS IN DRIVE"?

**Comment by lurch** [comment]
"SOURCE DRIVE" ?

**Comment by konmouz** [comment]
@jviotti I am referring to drive labels in general (e.g zeplin page: Step 2/select drive/modal/inactive). Also, labels should be below title, not above - if possible.
@lurch "SOURCE DRIVE" sounds great. We can use just a normal black tooltip for details.

**Comment by jviotti** [comment]
@konmouz What do you think of https://github.com/resin-io/etcher/pull/1066?
