### ISSUE TITLE
Support for CDR files

### ISSUE THREAD

**Issue by amiltonjr** [resin-io/etcher#836]
- **Etcher version: 1.0.0-beta.16**
- **Operating system and architecture: MAC OS X**

Hi, is Etcher for MAC going to support another image files besides ISO? It would be great having support for CDR and DMG as well.

**Comment by lurch** [comment]
Etcher now supports DMG files :-D

**Comment by jhermsmeier** [comment]
Just for reference, support for DMG/UDIF was initially added in https://github.com/resin-io/etcher/pull/1257

**Comment by lurch** [comment]
(There's a bit more discussion about the CDR format in https://github.com/resin-io-modules/etcher-image-stream/pull/42 )

**Comment by jviotti** [comment]
Let's close this for now. We will consider this in the future.
