### ISSUE TITLE
Increase image drag and drop area

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#848]
We currently support drag and drop, however the user needs to make sure he drags the image onto the first step. For better UX purposes, the user should be able to drag and drop to any part of the application.

**Comment by lurch** [comment]
Merge this with #849 ?

**Comment by jviotti** [comment]
I think they serve different clearly defined purposes, and thus make more sense as separate issues. This is about increasing the drag and drop area, while the other one about putting an overlay during hover. I guess https://github.com/resin-io/etcher/issues/849 somewhat depends on this one though.

**Comment by jviotti** [comment]
By reading this again after a while, I agree with @lurch that it should be closed in favor of the other issue. Sorry for the non-sense :)
