### ISSUE TITLE
Publishers' extended archive creation tools

### ISSUE THREAD

**Issue by konmouz** [resin-io/etcher#852]

**Comment by jviotti** [comment]
Some ideas:

- Create a CLI, or desktop application (even inside Etcher itself)
- Maybe expose a service with a nice wizard-like web UI that generates the final package and allows the user to download
- Create a tool that "lints" a manually built package (for more hardcore users)

**Comment by konmouz** [comment]
Just to add:
- Simple UI customising tool with UI preview and CL style export of selected settings
- Implement instructions in a responsive and adaptive UI to accommodate relevant info and steps
- Accessible instructions without the need to flash an img

**Comment by jviotti** [comment]
This is not going to be needed anymore given recent changes to the extended archive format.
