### ISSUE TITLE
Button to generate "debug report" for users

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher#857]
Sometimes when users report problems with Etcher, it's difficult to get all the info from them we need.

Perhaps there should be an button in the Etcher GUI somewhere (ping @konmouz ) that we could ask the users to click on that would generate a "debug report" they could send to us, which would contain all kinds of useful information, like:
 * Etcher version
 * OS (and version) that Etcher is being run on
 * Name of the image that was selected
 * Name of the drive that was selected
 * Output of the DevTools console
 * Output of the `drivelist` command
 * etc.

**Comment by jviotti** [comment]
We should make sure we are super clear about what information we're retrieving though.

**Comment by lurch** [comment]
Of course. We should also allow the user to view all the info in the report, before they send it to us. Perhaps we could just dump a text file in the same location as the Etcher binary (if that dir is writable) or in the user's home directory otherwise?

**Comment by konmouz** [comment]
We can have an option in settings, where user can also review report's content and choose where to save, or send it directly to us (i.e. Apple has a very similar flow for this when something goes wrong.

**Comment by taahirisaacs** [comment]
Me and @konmouz were chatting about this, and thought it might be interesting to prompt the user on initial start-up of Etcher. They could still find the option within settings.

**Comment by lurch** [comment]
Hmmm, _what_ would it prompt the user for on initial start-up?
Hopefully most users won't encounter errors, so we won't need to bother them about debug reports... ;-)

**Comment by konmouz** [comment]
This is in case we need to always get auto-generated reports when something goes wrong. Indeed it is an extra step, but if you think it could be something useful we can explore how this can be implemented.

**Comment by lurch** [comment]
IMHO asking every user at start-up about debug reports, might give the user the wrong impression that we *expect* Etcher to have problems? :-S

**Comment by konmouz** [comment]
This could be indeed an issue. So for now we can have an option in settings and just a dialog when something goes wrong.

**Comment by jviotti** [comment]
I personally don't think we should bother with automatic error reporting, since as @lurch , this will be the exception rather than the rule, and we're pretty much covered in that aspect by TrackJS.

I propose to develop a button that users can click to generate a file containing all sorts of information about their system (generic stuff, no personal information), and they can send it to us by themselves (on a GitHub issue, or attaching to Gitter).

**Comment by konmouz** [comment]
I was thinking a modal with direct option to 'send to Resin' or 'just save'. Visuals will follow soon.

**Comment by jviotti** [comment]
Lets do a "just save" for now. We don't know how beneficial these reports will be to us, so lets wait for some real benefits before polishing and automating the feature.

**Comment by konmouz** [comment]
<img width="923" alt="screen shot 2016-12-01 at 16 06 18" src="https://cloud.githubusercontent.com/assets/15323961/20801246/27c5496c-b7e0-11e6-963a-793793c364a9.png">
<img width="923" alt="screen shot 2016-12-01 at 16 06 04" src="https://cloud.githubusercontent.com/assets/15323961/20801249/293789fe-b7e0-11e6-88c3-0fb01bea2720.png">

**Comment by konmouz** [comment]
The ignore button redirects back to the settings. I guess that the 'debug report' modal can also appear after an unexpected error. In this case the ignore button will just dismiss the modal window.

**Comment by jviotti** [comment]
I feel that having the "debug report" button inside the settings dialog feels a bit weird. We have this question mark icon right next to the settings that currently redirects user to https://github.com/resin-io/etcher/blob/master/SUPPORT.md. What about having that icon open a modal that allows you to either open such document *or* generate the bug report?

**Comment by konmouz** [comment]
This is a bit tricky. Indeed settings is not the best place to have the debug report, however, I am not sure if it a good practice to create a new modal to host basically just two options and complicate the help flow (which currently is very direct). Another concern is that normally users avoid 'help' unless they are really stuck (here we need some analytics to double check).

**Comment by jviotti** [comment]
Yeah, I agree its a tricky one. Lets go with settings if you feel that's
the best thing we can do at this point!

On Thu, Dec 01, 2016 at 09:21:36AM -0800, Konstantinos Mouzakis wrote:
> This is a bit tricky. Indeed settings is not the best place to have the debug report, however, I am not sure if it a good practice to create a new modal to host basically just two options and complicate the help flow (which currently is very direct). Another concern is that normally users avoid 'help' unless they are really stuck (here we need some analytics to double check).
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io/etcher/issues/857#issuecomment-264235773

-- 
Juan Cruz Viotti
Software Engineer

**Comment by konmouz** [comment]
@jviotti do we have analytics regarding how many people use 'help' and at what stage?

**Comment by jviotti** [comment]
@konmouz We don't have any event for the icon, even though we should (maybe @Shou can handle?). What we do have is GitHub analytics of how many times https://github.com/resin-io/etcher/blob/master/SUPPORT.md was visited here: https://github.com/resin-io/etcher/graphs/traffic, and its the second most viewed page in our GitHub repository (after the landing page).

**Comment by konmouz** [comment]
@jviotti can we find out where they are coming from?

**Comment by lurch** [comment]
I guess as far as GitHub is concerned, they can't tell the difference between people clicking on the 'help' button in Etcher, and people just typing https://github.com/resin-io/etcher/blob/master/SUPPORT.md directly into the URL bar of their browser.

**Comment by jviotti** [comment]
Yeah, we can't know for sure, however its unlikely that users will open `SUPPORT.md` out of nowhere. I'd say at least 80% of those come from the application, but again, we don't know for sure.

**Comment by lurch** [comment]
> Yeah, we can't know for sure, however its unlikely that users will open SUPPORT.md out of nowhere

Agreed. So presumably all visits with no referrer are coming direct from the application. It obviously doesn't account for the "long tail" effect, but adding up the top 10 "Popular content" views gives a total of 5,484 views, and adding up the top 10 "Referring sites" views gives a total of 4667 views, meaning 817 views have no referrer.

Interestingly, two of the top 10 Referring sites are from non-English webpages. I guess the simplicity of the Etcher interface makes it easy to use for non-English speakers :-)
(but perhaps it adds more weight to #308 ?)

**Comment by jviotti** [comment]
As proposed by @lurch in https://github.com/resin-io/etcher/issues/953#issuecomment-265456988, lets start prototyping this as an internal feature available through DevTools.

**Comment by jviotti** [comment]
Apparently Sentry has support to generate and display error reports /cc @stefan-mihaila
