### ISSUE TITLE
Error on apt-key

### ISSUE THREAD

**Issue by Cascador** [resin-io/etcher#859]
Hello,

sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 379CE192D401AB61 doesn't work.

The key is missing on pgp.mit.edu ?

Thanks.

**Comment by lurch** [comment]
Works fine for me? What error message do you get?

**Comment by Cascador** [comment]
Problem solved with : sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 379CE192D401AB61

Probably a firewall or proxy problem, see here : http://unix.stackexchange.com/questions/75892/keyserver-timed-out-when-trying-to-add-a-gpg-public-key

Thanks.

**Comment by lurch** [comment]
Thanks for letting us know @Cascador .

@jviotti @dlech should this info be added to https://github.com/resin-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64 ?

**Comment by Cascador** [comment]
sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 379CE192D401AB61 works on more cases (especially at work). 

FYI in Docker sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 (https://docs.docker.com/engine/installation/linux/ubuntulinux/)
