### ISSUE TITLE
Improve visual feedback on element :focus

### ISSUE THREAD

**Issue by Shou** [resin-io/etcher#860]
Navigation using the tab key is tough because visual feedback is either too subtle or nonexistent when an element gains `:focus`, e.g. the "Select image" button, or warning dialog button(s).

**Comment by jviotti** [comment]
Pinging @taahirisaacs and @konmouz for input on visual feedback.

**Comment by jhermsmeier** [comment]
This is happening in https://github.com/resin-io/etcher/pull/1745

**Comment by lurch** [comment]
Closing as duplicate of #1734
