### ISSUE TITLE
'disabled' drives have wrong cursor

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher#865]
- **Etcher version:** 1.0.0-beta16
- **Operating system and architecture:** Linux x64

When a drive in the select-a-drive list is 'disabled' (whether because the drive is read-only, too small for the selected image, etc.) like shown in https://github.com/resin-io/etcher/issues/830#issuecomment-259515129 , it still displays a hand-cursor when you mouse-hover over it, implying that it's clickable when it isn't.

**Comment by jviotti** [comment]
Tweaking `cursor` should do it.
