### ISSUE TITLE
Implement OS X and Windows installers

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#88]
- [x] OS X installer
- [x] Windows installer

**Comment by jviotti** [comment]
OS X installer -> https://github.com/resin-io/resin-etcher/pull/79

**Comment by jviotti** [comment]
Windows installer -> https://github.com/resin-io/etcher/pull/152

**Comment by lurch** [comment]
@jviotti No idea why this has been re-labelled as "in progress" - should that be removed?

**Comment by jviotti** [comment]
Ah, the Wafflebot... its behaviour is a bit weird sometimes. I wonder why he assigned you here.

**Comment by lurch** [comment]
The comment in #79 said "Partially fixes #79" (i.e. a circular loop), so I edited it yesterday to say "Partially fixes #88". But dunno why that triggered wafflebot :-S
