### ISSUE TITLE
Support double-click in drivelist dialog?

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher#880]
- **Etcher version:** 1.0.0-beta16

UX issue, so pinging @taahirisaacs and @konmouz too...

If you have multiple drives connected before running Etcher, when you get to the "Select drive" dialog you get a list of available drives displayed. Currently you have to single-click on one of the drives, and then click CONTINUE (which closes the dialog).
I wonder if it might also make sense for double-clicking on a drive to automatically select that drive and close the dialog?

**Comment by jviotti** [comment]
This is a very good one. Assigning @Shou... Lets go for it.

**Comment by konmouz** [comment]
That would be great!
