### ISSUE TITLE
Persistent Live USB

### ISSUE THREAD

**Issue by nilabja10201992** [resin-io/etcher#887]
It's just a request, the software is truly awesome, adding an option to make Linux LIVE USB Persistent will be an added advantage.
Thank You

**Comment by jviotti** [comment]
Hi @nilabja10201992 ,

Thanks a lot for the suggestion! I'm happy to like Etcher :)

This issue is currently being tracked at https://github.com/resin-io/etcher/issues/413, so I'll close this as a duplicate. Keep an eye on that!
