### ISSUE TITLE
Show list of supported file extensions in alphabetical ordering

### ISSUE THREAD

**Issue by tooomm** [resin-io/etcher#984]
- **Etcher version:** Etcher-1.0.0-beta.17-win32-x64

`Open Image` window should have a ordered list of supported formats, preferably in alphabetical order. It's a bit of a mess right now: :)

![untitled](https://cloud.githubusercontent.com/assets/9874850/21412209/d3a04a5c-c7ee-11e6-9ec1-724664d993c5.png)

**Comment by lurch** [comment]
Haha, reminds me of #787 ;-)

For this particular fix though, we'd either need to modify https://github.com/resin-io/etcher/blob/master/lib/gui/models/supported-formats.js#L101 to always sort the extensions alphabetically (or use some other well-defined ordering method), or modify the order the items are stored in https://github.com/resin-io-modules/etcher-image-stream/blob/master/lib/supported.js

**Comment by jviotti** [comment]
Let's sort in alphabetical order here and keep our "relevance" based order everywhere else.

**Comment by tooomm** [comment]
This can be closed I guess...

**Comment by jviotti** [comment]
Ah, good catch. Turns out the commit referenced this issue with "See" instead of "Closes"/"Fixes".
