### ISSUE TITLE
Make website visits coming from the update prompt on etcher identifiable

### ISSUE THREAD

**Issue by alexandrosm** [resin-io/etcher#987]
This should be simple to do but v. valuable. We should make the link to the etcher.io website coming from the "update" link be identifiable, perhaps by attaching a `?ref=etcher_update` querystring. That will allow us to separate that traffic in the analytics, and perhaps even offer a slightly different landing page.

**Comment by lurch** [comment]
I guess we could also do something similar for the Etcher logo displayed at the bottom of the main program window, e.g. have it link to `https://etcher.io/?ref=etcher`.
And would we then want to use a link like `https://etcher.io/?ref=github` for links in the README and documentation?

**Comment by jviotti** [comment]
Sounds good, and its a really easy improvement. I assigned @Shou to it.

**Comment by alexandrosm** [comment]
Check the source code :) but the github one, yes!

**Comment by jviotti** [comment]
What do you mean? Editing https://github.com/resin-io/etcher/blob/master/lib/gui/components/update-notifier/templates/update-notifier-modal.tpl.html#L15 should do it.

**Comment by lurch** [comment]
@alexandrosm 

> but the github one, yes!

Does that mean that you **do** still want the links from github.com to etcher.io to have referrer query-URLs? And if so, should this issue be re-opened?

**Comment by alexandrosm** [comment]
actually, I think github has proper referrer, because we can see it in our
analytics. so no real problem there!

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm
