### ISSUE TITLE
16GB flash drive turned into 64mb RAW after buring

### ISSUE THREAD

**Issue by SaifAM** [resin-io/etcher#988]
Etcher version: 1.0.0-beta.17
Windows 10 Pro 
no error came up while burning the drive

**Comment by lurch** [comment]
That's expected (i.e. not an error), and depends entirely on which disk-image you're writing - disk-images often contain secondary partitions which Windows isn't able to read.

If you want to revert your flash drive "back to normal" see https://github.com/resin-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#recovering-broken-drives

**Comment by SaifAM** [comment]
Thank you for the response. Some how I was able to bring my flash drive back to normal, but thank you for the information
